import { log } from '../../../agent/logger.js';
import type { BrandProfile } from '../../../config/types.js';

export interface DesignBrief {
  instruction: string;
  format: string;
  platform: string;
  brand?: BrandProfile;
}

export interface CanvaDesignSpec {
  workflowId: string;
  brief: DesignBrief;
  designGuidance: string;
  colorPalette?: string[];
  typography?: string;
  layout?: string;
}

export const consultCanvaSpecialist = async (
  brief: DesignBrief,
): Promise<CanvaDesignSpec> => {
  log.info('[CanvaSpecialist] consulted', { format: brief.format });

  return {
    workflowId: `design-${Date.now()}`,
    brief,
    designGuidance: 'Design spec generated by Canva Specialist.',
    colorPalette: ['#000000', '#FFFFFF'],
    typography: 'modern-sans',
    layout: 'balanced',
  };
};

export default {
  consultCanvaSpecialist,
};
