import { beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('../../../src/agent/tokenRouter.js', () => ({
  askJson: vi.fn(async () => ({
    text: 'Claro, te ayudo con eso!',
    intent: 'comercial',
    rationale: 'respuesta de prueba',
    confidence: 0.9,
    shouldEscalate: false,
    suggestedActions: [],
  })),
  ask: vi.fn(async () => ({ text: 'Claro, te ayudo con eso!' })),
}));
vi.mock('../../../src/brain/bridge/brainEnrichment.js', () => ({
  injectIntoDMPrompt: vi.fn(async (_brand: unknown, _handle: string, basePrompt: string) => basePrompt),
}));
vi.mock('../../../src/brain/bridge/interactionLearner.js', () => ({
  learnFromInteraction: vi.fn(async () => undefined),
}));

import { ingestMessage, suggestReply, getConversation } from '../../../src/capabilities/community/dmInbox.js';
import type { BrandProfile } from '../../../src/config/types.js';

const mockBrand = {
  name: 'MarcaTest',
  type: 'empresa',
  niche: 'skincare',
  audience: { description: 'creators', pains: [], desires: [], locale: 'es-AR' },
  voice: { tone: ['directo'], forbidden: [], referenceQuotes: [] },
  visual: {
    palette: [],
    typography: [],
    style: 'minimalista',
    mood: 'profesional',
    photographyStyle: 'natural',
    compositionRules: [],
    allowedIconography: [],
    forbiddenIconography: [],
    moodboardUrls: [],
    density: 'medium',
    imageTextRatio: 'balanced',
  },
  goals: { primary: 'engagement', metricsToWatch: [] },
} as unknown as BrandProfile;

let uid = 0;
const freshThreadId = (): string => `thread-window-test-${Date.now()}-${uid++}`;

beforeEach(() => {
  uid = 0;
});

describe('suggestReply: ventana de 24h de Instagram Messaging (INT-005)', () => {
  it('dentro de la ventana (mensaje reciente): auto-envía normalmente', async () => {
    const threadId = freshThreadId();
    const conv = ingestMessage({ threadId, contactUsername: 'user1', text: '¿cuánto cuesta?' });

    const suggestion = await suggestReply(conv.id, { brand: mockBrand, autoSend: true });
    expect(suggestion?.shouldEscalate).toBe(false);

    const after = getConversation(conv.id);
    expect(after?.messages.some((m) => m.sender === 'us' && m.isAutoGenerated)).toBe(true);
  });

  it('fuera de la ventana (>24h desde el último mensaje del usuario): fuerza escalar, nunca auto-envía', async () => {
    const threadId = freshThreadId();
    const conv = ingestMessage({
      threadId,
      contactUsername: 'user2',
      text: 'hola, alguna promo?',
      timestamp: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(), // 30h atrás
    });

    const suggestion = await suggestReply(conv.id, { brand: mockBrand, autoSend: true });
    expect(suggestion?.shouldEscalate).toBe(true);
    expect(suggestion?.rationale).toMatch(/24h/);

    const after = getConversation(conv.id);
    expect(after?.status).toBe('escalated');
    expect(after?.messages.some((m) => m.sender === 'us' && m.isAutoGenerated)).toBe(false);
  });

  it('sin autoSend, la ventana de 24h no fuerza nada (solo aplica al intento de auto-envío)', async () => {
    const threadId = freshThreadId();
    const conv = ingestMessage({
      threadId,
      contactUsername: 'user3',
      text: 'hola',
      timestamp: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    });

    const suggestion = await suggestReply(conv.id, { brand: mockBrand, autoSend: false });
    // El mock de askJson siempre devuelve shouldEscalate:false — sin autoSend, no se toca.
    expect(suggestion?.shouldEscalate).toBe(false);
  });
});
