-- Batch 100: Product/Service Video Prompts (200)
-- Parameterizable product video prompts: [PRODUCT], [PRICE], [BENEFIT], [TARGET_AUDIENCE]
-- Categories: Unboxing, demo, before-after, lifestyle integration, testimonial, problem-solution, explainer

INSERT INTO prompts (batch_id, category, prompt_text, model, parameters, tags) VALUES

-- CATEGORY: Product Unboxing (25 prompts)
(100, 'unboxing', 'Luxury unboxing: [PRODUCT] presented in premium packaging, slow reveal, hands showing detailed box opening, close-ups of product quality, ambient lighting, ASMR unwrapping sounds, satisfying reveal', 'veo-3.1', '{"product":"[PRODUCT]","style":"luxury","tone":"premium"}', 'unboxing,product,premium,luxury'),
(100, 'unboxing', 'Tech product unboxing: [PRODUCT] with all accessories laid out, showing box contents organization, professional product photography lighting, detailed feature showcase, minimalist aesthetic', 'veo-3.1', '{"product":"[PRODUCT]","category":"tech","detail_level":"high"}', 'unboxing,product,tech,detailed'),
(100, 'unboxing', 'Fashion item unboxing: [PRODUCT] styled presentation, showing packaging details, full product display on model, outfit coordination shown, retail setting with professional lighting', 'veo-3.1', '{"product":"[PRODUCT]","category":"fashion","styling":"yes"}', 'unboxing,product,fashion,lifestyle'),
(100, 'unboxing', 'Home product unboxing: [PRODUCT] unpacking in natural home setting, showing how it fits in actual space, relatable home aesthetic, warm lighting, practical showcase', 'veo-3.1', '{"product":"[PRODUCT]","category":"home","setting":"residence"}', 'unboxing,product,home,practical'),
(100, 'unboxing', 'Cosmetics haul unboxing: [PRODUCT] multiple items displayed, organized arrangement, swatching shown, excitement captured, beauty lighting setup, influencer-style showcase', 'veo-3.1', '{"product":"[PRODUCT]","category":"beauty","items":"multiple"}', 'unboxing,product,beauty,haul'),

(100, 'unboxing', 'Sustainable packaging reveal: [PRODUCT] with eco-friendly unboxing, packaging materials highlighted, sustainability story told, careful unwrapping, environmental angle emphasized', 'veo-3.1', '{"product":"[PRODUCT]","angle":"sustainable","packaging":"eco"}', 'unboxing,product,sustainable,eco'),
(100, 'unboxing', 'Mystery box style unboxing: [PRODUCT] with surprise reveal, suspenseful opening, genuine reaction to item, entertainment-focused, engaging energy, viewer excitement mirrored', 'veo-3.1', '{"product":"[PRODUCT]","style":"mystery","entertainment":"high"}', 'unboxing,product,entertainment,mystery'),
(100, 'unboxing', 'Professional product unboxing: [PRODUCT] in studio setting, expert handling, product features explained during opening, polished production quality, educational narration, detailed inspection', 'veo-3.1', '{"product":"[PRODUCT]","style":"professional","narration":"yes"}', 'unboxing,product,professional,educational'),
(100, 'unboxing', 'ASMR focused unboxing: [PRODUCT] with ambient sound focus, satisfying texture sounds, quiet narration or no dialogue, relaxation aesthetic, close microphone, soothing experience', 'veo-3.1', '{"product":"[PRODUCT]","style":"asmr","audio":"ambient"}', 'unboxing,product,asmr,relaxing'),
(100, 'unboxing', 'Quick unboxing: [PRODUCT] fast-paced reveal, trending audio synced, entertainment focus, quick cuts, energetic music, social media optimized, short format', 'veo-3.1', '{"product":"[PRODUCT]","pace":"fast","duration":"15-30s"}', 'unboxing,product,fast,trending'),

(100, 'unboxing', 'Child-friendly product unboxing: [PRODUCT] toy or kids item, joyful opening, excitement expressed, kid perspective shown, bright colors emphasized, fun energy, family relatable', 'veo-3.1', '{"product":"[PRODUCT]","audience":"children","tone":"joyful"}', 'unboxing,product,kids,family'),
(100, 'unboxing', 'Luxury jewelry unboxing: [PRODUCT] precious item careful reveal, velvet box opening, close-up sparkle shots, dramatic lighting, premium presentation, elegant aesthetic', 'veo-3.1', '{"product":"[PRODUCT]","category":"jewelry","tone":"elegant"}', 'unboxing,product,luxury,jewelry'),
(100, 'unboxing', 'Food product unboxing: [PRODUCT] snacks or specialty food, opening and sampling, taste reaction captured, packaging design highlighted, appetite appeal, food styling', 'veo-3.1', '{"product":"[PRODUCT]","category":"food","sampling":"yes"}', 'unboxing,product,food,tasting'),
(100, 'unboxing', 'Gadget tech unboxing: [PRODUCT] cutting-edge device, features demo during opening, specifications mentioned, innovation highlighted, tech enthusiast appeal', 'veo-3.1', '{"product":"[PRODUCT]","category":"gadget","innovation":"yes"}', 'unboxing,product,tech,innovation'),
(100, 'unboxing', 'Luxury handbag unboxing: [PRODUCT] designer item careful reveal, craftsmanship details shown, compartment tour, size demonstration, premium luxury aesthetic', 'veo-3.1', '{"product":"[PRODUCT]","category":"accessories","luxury_level":"high"}', 'unboxing,product,luxury,fashion'),

(100, 'unboxing', 'Sustainable beauty unboxing: [PRODUCT] eco-friendly cosmetics, green packaging emphasized, cruelty-free highlighted, brand story told, conscious consumer appeal', 'veo-3.1', '{"product":"[PRODUCT]","angle":"sustainable","category":"beauty"}', 'unboxing,product,sustainable,ethical'),
(100, 'unboxing', 'Gaming product unboxing: [PRODUCT] console or gaming gear, excitement authentic, features explained, setup shown, gamer aesthetic, technical specs highlighted', 'veo-3.1', '{"product":"[PRODUCT]","category":"gaming","audience":"gamers"}', 'unboxing,product,gaming,tech'),
(100, 'unboxing', 'Sports equipment unboxing: [PRODUCT] athletic gear, durability emphasized, material quality shown, usage potential demonstrated, performance focus, athlete energy', 'veo-3.1', '{"product":"[PRODUCT]","category":"sports","angle":"performance"}', 'unboxing,product,sports,athletic'),
(100, 'unboxing', 'Limited edition unboxing: [PRODUCT] exclusive item, collectibility highlighted, rarity emphasized, special packaging, prestige focused, collector appeal', 'veo-3.1', '{"product":"[PRODUCT]","type":"limited-edition","appeal":"collectible"}', 'unboxing,product,exclusive,limited'),
(100, 'unboxing', 'Personalized product unboxing: [PRODUCT] customized item, personal customization shown, uniqueness emphasized, emotional connection created, heartfelt moment', 'veo-3.1', '{"product":"[PRODUCT]","type":"personalized","emotion":"sentimental"}', 'unboxing,product,personalized,sentimental'),

(100, 'unboxing', 'Budget-friendly unboxing: [PRODUCT] affordable item, value-for-money highlighted, quality shown despite price point, budget shopper appeal, practical angle', 'veo-3.1', '{"product":"[PRODUCT]","price_point":"budget","angle":"value"}', 'unboxing,product,budget,value'),
(100, 'unboxing', 'Premium brand unboxing: [PRODUCT] high-end item, brand heritage mentioned, luxury experience emphasized, prestige focused, aspirational appeal', 'veo-3.1', '{"product":"[PRODUCT]","brand_tier":"premium","tone":"aspirational"}', 'unboxing,product,luxury,premium'),

-- CATEGORY: Product Demo & Features (35 prompts)
(100, 'demo', '[PRODUCT] in action: demonstrating core features, functionality shown step-by-step, close-ups of important details, user interacting with product, real-world usage scenario', 'veo-3.1', '{"product":"[PRODUCT]","focus":"features","usage":"real-world"}', 'demo,product,features,tutorial'),
(100, 'demo', '[PRODUCT] durability test: showing robustness, quality materials proven, stress testing shown, reliability emphasized, confidence building, practical assurance', 'veo-3.1', '{"product":"[PRODUCT]","angle":"durability","tone":"assuring"}', 'demo,product,durability,quality'),
(100, 'demo', '[PRODUCT] speed comparison: performance tested against alternatives, efficiency shown, time-saving benefits demonstrated, results quantified, competitive advantage', 'veo-3.1', '{"product":"[PRODUCT]","comparison":"yes","metric":"speed"}', 'demo,product,performance,comparison'),
(100, 'demo', '[PRODUCT] ease of use walkthrough: simple operation shown, minimal learning curve, user-friendly interface explained, accessibility highlighted, novice-friendly appeal', 'veo-3.1', '{"product":"[PRODUCT]","angle":"ease-of-use","user_level":"beginner"}', 'demo,product,tutorial,user-friendly'),
(100, 'demo', '[PRODUCT] advanced features deep dive: technical capabilities explored, power-user features shown, expert-level usage, mastery path outlined, enthusiast appeal', 'veo-3.1', '{"product":"[PRODUCT]","depth":"advanced","audience":"experts"}', 'demo,product,advanced,technical'),

(100, 'demo', '[PRODUCT] compatibility showcase: works with existing systems, integration shown, seamless setup, ecosystem fit, practical utility', 'veo-3.1', '{"product":"[PRODUCT]","angle":"compatibility","setup":"yes"}', 'demo,product,integration,practical'),
(100, 'demo', '[PRODUCT] customization options: personalization features shown, settings explained, user control highlighted, flexibility emphasized', 'veo-3.1', '{"product":"[PRODUCT]","feature":"customization","control":"user"}', 'demo,product,customization,features'),
(100, 'demo', '[PRODUCT] maintenance & care: proper usage guidelines shown, longevity tips given, durability preservation, expert advice, practical knowledge', 'veo-3.1', '{"product":"[PRODUCT]","angle":"maintenance","educational":"yes"}', 'demo,product,care,maintenance'),
(100, 'demo', '[PRODUCT] unboxing to usage flow: complete journey from package to full operation, setup walkthrough, initial impressions shared, seamless transition shown', 'veo-3.1', '{"product":"[PRODUCT]","flow":"complete","steps":"unboxing-to-use"}', 'demo,product,tutorial,flow'),
(100, 'demo', '[PRODUCT] problem-solving capability: shows how product addresses common issues, pain points solved, relief demonstrated, solution validation', 'veo-3.1', '{"product":"[PRODUCT]","angle":"problem-solving","benefit":"relief"}', 'demo,product,solution,benefit'),

(100, 'demo', '[PRODUCT] comparative feature chart: visual comparison with competitors, advantages highlighted, value proposition clear, competitive analysis', 'veo-3.1', '{"product":"[PRODUCT]","format":"comparison","competitors":"included"}', 'demo,product,comparison,features'),
(100, 'demo', '[PRODUCT] in professional environment: workplace/studio usage shown, productivity boost demonstrated, professional context, business application', 'veo-3.1', '{"product":"[PRODUCT]","environment":"professional","context":"business"}', 'demo,product,professional,productivity'),
(100, 'demo', '[PRODUCT] gaming/entertainment use: fun factor highlighted, entertainment value shown, joy of use captured, lifestyle integration', 'veo-3.1', '{"product":"[PRODUCT]","use_case":"entertainment","tone":"fun"}', 'demo,product,entertainment,lifestyle'),
(100, 'demo', '[PRODUCT] time-saving benefits: workflow optimization shown, hours saved calculated, efficiency gains visualized, productivity angle', 'veo-3.1', '{"product":"[PRODUCT]","benefit":"time-saving","metric":"hours"}', 'demo,product,productivity,efficiency'),
(100, 'demo', '[PRODUCT] cost-benefit analysis: value over time shown, ROI calculated, long-term savings highlighted, investment justified', 'veo-3.1', '{"product":"[PRODUCT]","angle":"investment","metric":"ROI"}', 'demo,product,value,investment'),

(100, 'demo', '[PRODUCT] accessibility features: inclusive design shown, different user types accommodated, universal usability, diverse ability support', 'veo-3.1', '{"product":"[PRODUCT]","angle":"accessibility","inclusion":"yes"}', 'demo,product,accessibility,inclusive'),
(100, 'demo', '[PRODUCT] environmental impact: eco-friendly features highlighted, sustainability story, green benefits emphasized, conscious consumer appeal', 'veo-3.1', '{"product":"[PRODUCT]","angle":"sustainable","audience":"eco-conscious"}', 'demo,product,sustainability,ethical'),
(100, 'demo', '[PRODUCT] multi-purpose uses: versatility shown, multiple applications demonstrated, flexibility emphasized, broad appeal', 'veo-3.1', '{"product":"[PRODUCT]","angle":"versatility","uses":"multiple"}', 'demo,product,versatile,multi-purpose'),
(100, 'demo', '[PRODUCT] safety features: security highlighted, protective mechanisms shown, reliability assured, trust building', 'veo-3.1', '{"product":"[PRODUCT]","angle":"safety","tone":"assuring"}', 'demo,product,safety,security'),
(100, 'demo', '[PRODUCT] quality verification: testing shown, standards met, certification highlighted, confidence assured', 'veo-3.1', '{"product":"[PRODUCT]","angle":"quality","verification":"yes"}', 'demo,product,quality,certified'),

(100, 'demo', '[PRODUCT] partnership/collaboration benefits: works better with complementary products, ecosystem value, integration benefits highlighted', 'veo-3.1', '{"product":"[PRODUCT]","angle":"ecosystem","partnership":"yes"}', 'demo,product,integration,ecosystem'),
(100, 'demo', '[PRODUCT] warranty & support: peace of mind offered, customer support shown, guarantee explained, risk reduction', 'veo-3.1', '{"product":"[PRODUCT]","angle":"support","tone":"reassuring"}', 'demo,product,support,warranty'),
(100, 'demo', '[PRODUCT] size & portability: compact design praised, travel-friendly features, mobility advantages shown, on-the-go utility', 'veo-3.1', '{"product":"[PRODUCT]","angle":"portability","benefit":"mobility"}', 'demo,product,portable,practical'),
(100, 'demo', '[PRODUCT] storage solutions: organization benefits, space-saving design, utility maximized, practical advantage', 'veo-3.1', '{"product":"[PRODUCT]","benefit":"storage","angle":"organization"}', 'demo,product,organization,practical'),
(100, 'demo', '[PRODUCT] battery/power performance: longevity tested, charging speed compared, energy efficiency shown, reliability assured', 'veo-3.1', '{"product":"[PRODUCT]","focus":"power","metric":"hours"}', 'demo,product,performance,technical'),

(100, 'demo', '[PRODUCT] water/weather resistance: durability in conditions, protection proven, reliability shown, real-world toughness', 'veo-3.1', '{"product":"[PRODUCT]","feature":"weather-resistant","test":"yes"}', 'demo,product,durability,rugged'),
(100, 'demo', '[PRODUCT] design aesthetic: visual appeal highlighted, styling praised, modern/classic design, form meets function', 'veo-3.1', '{"product":"[PRODUCT]","focus":"design","tone":"aesthetic"}', 'demo,product,design,aesthetic'),
(100, 'demo', '[PRODUCT] comfort & ergonomics: user comfort prioritized, design for long-use shown, physical feedback positive, usability focus', 'veo-3.1', '{"product":"[PRODUCT]","angle":"comfort","focus":"ergonomics"}', 'demo,product,comfort,ergonomic'),
(100, 'demo', '[PRODUCT] connectivity options: wireless capabilities, connection speed, seamless pairing, technology integration', 'veo-3.1', '{"product":"[PRODUCT]","feature":"connectivity","tech":"wireless"}', 'demo,product,tech,connectivity'),
(100, 'demo', '[PRODUCT] app/software integration: companion app features, control options, data sync, digital ecosystem', 'veo-3.1', '{"product":"[PRODUCT]","integration":"software","platform":"mobile"}', 'demo,product,digital,integration'),

-- CATEGORY: Before & After (25 prompts)
(100, 'before_after', '[PRODUCT] transformation: before problem shown, product applied, after result displayed, visible improvement captured, solution proven', 'veo-3.1', '{"product":"[PRODUCT]","angle":"transformation","before_after":"yes"}', 'before-after,product,transformation,results'),
(100, 'before_after', '[PRODUCT] space makeover: before cluttered/inefficient space, [PRODUCT] integrated, after organized/beautiful space, improvement dramatic', 'veo-3.1', '{"product":"[PRODUCT]","angle":"organization","type":"space"}', 'before-after,product,organization,lifestyle'),
(100, 'before_after', '[PRODUCT] performance upgrade: before slow/inefficient process, [PRODUCT] solution applied, after accelerated/optimized performance, efficiency gain shown', 'veo-3.1', '{"product":"[PRODUCT]","angle":"performance","benefit":"speed"}', 'before-after,product,performance,upgrade'),
(100, 'before_after', '[PRODUCT] aesthetic improvement: before plain/boring look, [PRODUCT] enhancement, after stylish/appealing result, visual transformation', 'veo-3.1', '{"product":"[PRODUCT]","angle":"aesthetic","type":"visual"}', 'before-after,product,aesthetic,transformation'),
(100, 'before_after', '[PRODUCT] problem resolution: before issue present, [PRODUCT] addresses problem, after issue resolved, solution validated', 'veo-3.1', '{"product":"[PRODUCT]","angle":"solution","benefit":"relief"}', 'before-after,product,solution,resolution'),

(100, 'before_after', '[PRODUCT] lifestyle upgrade: before limited capability, [PRODUCT] enables new experiences, after enriched lifestyle shown, quality of life improvement', 'veo-3.1', '{"product":"[PRODUCT]","angle":"lifestyle","benefit":"experience"}', 'before-after,product,lifestyle,upgrade'),
(100, 'before_after', '[PRODUCT] time-saving impact: before time-consuming task, [PRODUCT] automates/accelerates, after time freed up, productivity gain visualized', 'veo-3.1', '{"product":"[PRODUCT]","benefit":"time-saving","metric":"visible"}', 'before-after,product,productivity,efficiency'),
(100, 'before_after', '[PRODUCT] comfort enhancement: before uncomfortable situation, [PRODUCT] comfort solution, after comfort level improved, relief expressed', 'veo-3.1', '{"product":"[PRODUCT]","benefit":"comfort","emotion":"relief"}', 'before-after,product,comfort,lifestyle'),
(100, 'before_after', '[PRODUCT] quality upgrade: before lower quality, [PRODUCT] premium option, after quality improvement visible/felt, upgrade clear', 'veo-3.1', '{"product":"[PRODUCT]","angle":"quality","benefit":"upgrade"}', 'before-after,product,quality,premium'),
(100, 'before_after', '[PRODUCT] health/wellness improvement: before health concern, [PRODUCT] wellness solution, after improvement documented, wellbeing enhanced', 'veo-3.1', '{"product":"[PRODUCT]","category":"wellness","benefit":"health"}', 'before-after,product,wellness,health'),

(100, 'before_after', '[PRODUCT] skill development: before lacking capability, practice with [PRODUCT], after skill mastered, learning journey shown', 'veo-3.1', '{"product":"[PRODUCT]","angle":"learning","benefit":"skill"}', 'before-after,product,learning,development'),
(100, 'before_after', '[PRODUCT] confidence boost: before self-doubt, [PRODUCT] empowers, after increased confidence shown, psychological transformation', 'veo-3.1', '{"product":"[PRODUCT]","benefit":"confidence","emotion":"empowerment"}', 'before-after,product,psychological,empowerment'),
(100, 'before_after', '[PRODUCT] home improvement: before dated/worn space, [PRODUCT] refresh/upgrade, after modern/renewed look, home transformation', 'veo-3.1', '{"product":"[PRODUCT]","category":"home","angle":"renovation"}', 'before-after,product,home,lifestyle'),
(100, 'before_after', '[PRODUCT] financial impact: before expensive process, [PRODUCT] cost-saving solution, after savings documented, financial benefit clear', 'veo-3.1', '{"product":"[PRODUCT]","benefit":"cost-saving","metric":"money"}', 'before-after,product,financial,value'),
(100, 'before_after', '[PRODUCT] environmental improvement: before wasteful method, [PRODUCT] eco-friendly alternative, after environmental impact reduction shown', 'veo-3.1', '{"product":"[PRODUCT]","angle":"sustainable","benefit":"eco"}', 'before-after,product,sustainability,ethical'),

(100, 'before_after', '[PRODUCT] work efficiency: before inefficient workflow, [PRODUCT] optimization, after streamlined process, productivity multiplication', 'veo-3.1', '{"product":"[PRODUCT]","category":"professional","benefit":"efficiency"}', 'before-after,product,professional,productivity'),
(100, 'before_after', '[PRODUCT] appearance transformation: before imperfect appearance, [PRODUCT] enhances, after polished look achieved, confidence evident', 'veo-3.1', '{"product":"[PRODUCT]","category":"beauty","benefit":"appearance"}', 'before-after,product,beauty,transformation'),
(100, 'before_after', '[PRODUCT] functionality upgrade: before limited function, [PRODUCT] full capabilities, after possibilities expanded, feature advantage clear', 'veo-3.1', '{"product":"[PRODUCT]","angle":"features","benefit":"capability"}', 'before-after,product,features,capability'),
(100, 'before_after', '[PRODUCT] stress reduction: before stressful situation, [PRODUCT] stress-relief solution, after calm achieved, wellbeing improved', 'veo-3.1', '{"product":"[PRODUCT]","benefit":"stress-relief","emotion":"calm"}', 'before-after,product,wellness,stress-relief'),
(100, 'before_after', '[PRODUCT] protection/safety: before vulnerable/exposed, [PRODUCT] protective solution, after safety assured, security improved', 'veo-3.1', '{"product":"[PRODUCT]","benefit":"protection","angle":"safety"}', 'before-after,product,safety,protection'),

(100, 'before_after', '[PRODUCT] accessibility improvement: before difficult/impossible task, [PRODUCT] enables access, after capability achieved, independence enabled', 'veo-3.1', '{"product":"[PRODUCT]","angle":"accessibility","benefit":"empowerment"}', 'before-after,product,accessibility,inclusion'),
(100, 'before_after', '[PRODUCT] organization transformation: before chaotic system, [PRODUCT] brings order, after clear/organized result, structure visible', 'veo-3.1', '{"product":"[PRODUCT]","benefit":"organization","angle":"structure"}', 'before-after,product,organization,lifestyle'),

-- CATEGORY: Testimonial & User Stories (30 prompts)
(100, 'testimonial', '[TARGET_AUDIENCE] sharing how [PRODUCT] changed life: personal story, genuine emotion, specific benefit explained, authentic experience shared', 'veo-3.1', '{"product":"[PRODUCT]","audience":"[TARGET_AUDIENCE]","format":"story"}', 'testimonial,user-story,authentic,emotional'),
(100, 'testimonial', 'Professional praising [PRODUCT]: expert user, endorsement given, credibility high, professional context, authority lending', 'veo-3.1', '{"product":"[PRODUCT]","speaker_type":"professional","credibility":"high"}', 'testimonial,professional,expert,endorsement'),
(100, 'testimonial', '[PRODUCT] long-term user reflection: after [BENEFIT] experienced, loyalty demonstrated, sustained satisfaction shown, long-term value proved', 'veo-3.1', '{"product":"[PRODUCT]","user_duration":"long-term","benefit":"[BENEFIT]"}', 'testimonial,loyalty,long-term,satisfaction'),
(100, 'testimonial', '[PRODUCT] skeptical convert: initial doubt expressed, trials overcome objection, full endorsement now, journey authentic', 'veo-3.1', '{"product":"[PRODUCT]","journey":"skeptic-to-convert","authenticity":"high"}', 'testimonial,authentic,conversion,compelling'),
(100, 'testimonial', 'Family/group using [PRODUCT]: shared experience, collective benefit shown, relational angle, family values angle', 'veo-3.1', '{"product":"[PRODUCT]","context":"family/group","tone":"shared"}', 'testimonial,family,relational,shared-experience'),

(100, 'testimonial', '[PRODUCT] solved specific problem for [TARGET_AUDIENCE]: targeted solution, specific use case, problem-to-solution journey', 'veo-3.1', '{"product":"[PRODUCT]","problem":"specific","audience":"[TARGET_AUDIENCE]"}', 'testimonial,problem-solution,targeted,authentic'),
(100, 'testimonial', '[PRODUCT] exceeded expectations: positive surprise, hopes surpassed, joy of discovery, delight evident', 'veo-3.1', '{"product":"[PRODUCT]","expectation":"exceeded","emotion":"delight"}', 'testimonial,positive-surprise,authentic,emotional'),
(100, 'testimonial', 'Competitor switcher endorsing [PRODUCT]: previous alternative used, switch justified, [PRODUCT] advantages highlighted', 'veo-3.1', '{"product":"[PRODUCT]","context":"switcher","comparison":"implied"}', 'testimonial,competitive,authentic,endorsement'),
(100, 'testimonial', '[PRODUCT] customer loyalty: repeat purchase, brand devotion, organic advocacy, authentic enthusiasm', 'veo-3.1', '{"product":"[PRODUCT]","type":"loyalty","behavior":"repeat"}', 'testimonial,loyalty,authentic,advocacy'),
(100, 'testimonial', '[PRODUCT] recommendation chain: user recommends to friend, word-of-mouth power, organic advocacy shown', 'veo-3.1', '{"product":"[PRODUCT]","type":"recommendation","format":"wom"}', 'testimonial,advocacy,word-of-mouth,organic'),

(100, 'testimonial', '[PRODUCT] daily life integration: [TARGET_AUDIENCE] showing routine use, essential product shown, lifestyle integration', 'veo-3.1', '{"product":"[PRODUCT]","integration":"daily-routine","audience":"[TARGET_AUDIENCE]"}', 'testimonial,lifestyle,essential,relatable'),
(100, 'testimonial', '[PRODUCT] emergency/critical moment: product saved day, hero moment, authenticity high, emotional peak', 'veo-3.1', '{"product":"[PRODUCT]","scenario":"critical","emotion":"heroic"}', 'testimonial,authentic,emotional,dramatic'),
(100, 'testimonial', '[PRODUCT] parent perspective: parent endorsing for children/family, protective angle, family values', 'veo-3.1', '{"product":"[PRODUCT]","perspective":"parent","audience":"family"}', 'testimonial,family-values,parental-endorsement'),
(100, 'testimonial', '[PRODUCT] caregiver testimonial: helper/caregiver endorsing for those they care for, compassion evident, relational angle', 'veo-3.1', '{"product":"[PRODUCT]","perspective":"caregiver","emotion":"compassion"}', 'testimonial,compassion,relational,authentic'),
(100, 'testimonial', '[PRODUCT] accessibility enabler: person with specific need, product enables capability, empowerment shown, life-changing angle', 'veo-3.1', '{"product":"[PRODUCT]","angle":"accessibility","impact":"life-changing"}', 'testimonial,accessibility,empowerment,authentic'),

(100, 'testimonial', '[PRODUCT] budget-friendly praise: affordability highlighted, value emphasized, wallet-friendly endorsement', 'veo-3.1', '{"product":"[PRODUCT]","angle":"affordability","audience":"budget-conscious"}', 'testimonial,value,affordability,authentic'),
(100, 'testimonial', '[PRODUCT] luxury experience: premium user, sophistication appreciated, prestige angle, quality emphasis', 'veo-3.1', '{"product":"[PRODUCT]","tier":"luxury","tone":"sophisticated"}', 'testimonial,luxury,premium,authentic'),
(100, 'testimonial', '[PRODUCT] business success story: entrepreneurial user, [PRODUCT] business impact, profit/growth shown, success narrative', 'veo-3.1', '{"product":"[PRODUCT]","context":"business","impact":"revenue"}', 'testimonial,business,success,authentic'),
(100, 'testimonial', '[PRODUCT] wellness journey: health/wellness benefit documented, progress shown, wellbeing transformation, authentic experience', 'veo-3.1', '{"product":"[PRODUCT]","category":"wellness","journey":"progress"}', 'testimonial,wellness,health,authentic'),
(100, 'testimonial', '[PRODUCT] time-saving transformation: before/after time usage, productivity gained, life improvement felt', 'veo-3.1', '{"product":"[PRODUCT]","benefit":"time-saving","measurement":"visible"}', 'testimonial,productivity,authentic,transformation'),

(100, 'testimonial', '[PRODUCT] unexpected use case: original purpose plus creative use, versatility proven, innovation by user', 'veo-3.1', '{"product":"[PRODUCT]","angle":"versatility","use_case":"creative"}', 'testimonial,versatility,creative,authentic'),
(100, 'testimonial', '[PRODUCT] gift-giver testimony: gave as gift, recipient joy captured, relational angle, gift success', 'veo-3.1', '{"product":"[PRODUCT]","context":"gift","emotion":"joy"}', 'testimonial,gift,relational,authentic'),
(100, 'testimonial', '[PRODUCT] student/learner endorsement: educational use, learning enhanced, student perspective, academic angle', 'veo-3.1', '{"product":"[PRODUCT]","audience":"student","context":"educational"}', 'testimonial,educational,student,authentic'),
(100, 'testimonial', '[PRODUCT] seasonal/timely testimonial: seasonal usage, perfect timing, relevance angle, timely endorsement', 'veo-3.1', '{"product":"[PRODUCT]","context":"seasonal","relevance":"timely"}', 'testimonial,seasonal,timely,authentic'),
(100, 'testimonial', '[PRODUCT] multi-generation endorsement: families across generations using, legacy value, timeless appeal shown', 'veo-3.1', '{"product":"[PRODUCT]","scope":"multigenerational","theme":"legacy"}', 'testimonial,family,legacy,authentic'),

-- CATEGORY: Problem-Solution (20 prompts)
(100, 'problem_solution', 'Problem: [BENEFIT] struggle shown. Solution: [PRODUCT] introduced. Result: problem resolved, solution validated', 'veo-3.1', '{"product":"[PRODUCT]","structure":"problem-solution-result","benefit":"[BENEFIT]"}', 'problem-solution,educational,authentic,benefit'),
(100, 'problem_solution', 'Common problem [TARGET_AUDIENCE] faces: relatable scenario set up. [PRODUCT] solution shown. After result: relief evident', 'veo-3.1', '{"product":"[PRODUCT]","audience":"[TARGET_AUDIENCE]","problem_type":"common"}', 'problem-solution,relatable,empathetic,benefit'),
(100, 'problem_solution', 'Industry pain point: problem context explained, why alternatives fail shown, [PRODUCT] unique solution, competitive edge clear', 'veo-3.1', '{"product":"[PRODUCT]","problem_type":"industry","context":"professional"}', 'problem-solution,professional,competitive,educational'),
(100, 'problem_solution', 'Time waste problem: inefficient process shown, time cost quantified, [PRODUCT] accelerates, time saved calculated', 'veo-3.1', '{"product":"[PRODUCT]","problem":"time-waste","metric":"hours"}', 'problem-solution,productivity,efficiency,benefit'),
(100, 'problem_solution', 'Cost problem: expensive alternative shown, budget strain evident, [PRODUCT] affordable solution, savings highlighted', 'veo-3.1', '{"product":"[PRODUCT]","problem":"cost","metric":"savings"}', 'problem-solution,affordability,value,benefit'),

(100, 'problem_solution', 'Frustration narrative: frustration situation set, emotional tension, [PRODUCT] removes frustration, relief shown', 'veo-3.1', '{"product":"[PRODUCT]","emotion":"frustration-to-relief","journey":"emotional"}', 'problem-solution,emotional,empathetic,relatable'),
(100, 'problem_solution', 'Complexity problem: complicated process shown, confusion evident, [PRODUCT] simplifies, clarity achieved', 'veo-3.1', '{"product":"[PRODUCT]","problem":"complexity","solution_angle":"simplification"}', 'problem-solution,simplification,clarity,benefit'),
(100, 'problem_solution', 'Risk/safety problem: vulnerability shown, danger implied or explicit, [PRODUCT] protects, safety assured', 'veo-3.1', '{"product":"[PRODUCT]","problem":"risk","solution_angle":"protection"}', 'problem-solution,safety,protection,reassuring'),
(100, 'problem_solution', 'Limitation problem: constrained situation, capability needed, [PRODUCT] enables, possibility achieved', 'veo-3.1', '{"product":"[PRODUCT]","problem":"limitation","solution_angle":"enablement"}', 'problem-solution,enablement,capability,benefit'),
(100, 'problem_solution', 'Quality problem: poor quality result from current method, [PRODUCT] improves quality, excellence achieved', 'veo-3.1', '{"product":"[PRODUCT]","problem":"quality","metric":"improvement"}', 'problem-solution,quality,excellence,benefit'),

(100, 'problem_solution', 'Accessibility problem: someone struggling with task, [PRODUCT] enables access, independence achieved, empowerment felt', 'veo-3.1', '{"product":"[PRODUCT]","problem":"accessibility","solution_angle":"inclusion"}', 'problem-solution,accessibility,inclusion,empowerment'),
(100, 'problem_solution', 'Environmental problem: wasteful practice shown, eco-concern, [PRODUCT] sustainable alternative, environmental impact improved', 'veo-3.1', '{"product":"[PRODUCT]","problem":"environmental","solution_angle":"sustainability"}', 'problem-solution,sustainability,ethical,benefit'),
(100, 'problem_solution', 'Compatibility problem: device/system incompatibility struggle, [PRODUCT] bridges gap, seamless integration achieved', 'veo-3.1', '{"product":"[PRODUCT]","problem":"compatibility","solution_angle":"integration"}', 'problem-solution,integration,technical,benefit'),
(100, 'problem_solution', 'Learning curve problem: difficulty learning shown, steep curve, [PRODUCT] easy adoption, quick mastery', 'veo-3.1', '{"product":"[PRODUCT]","problem":"learning-curve","solution_angle":"ease"}', 'problem-solution,education,ease-of-use,benefit'),
(100, 'problem_solution', 'Maintenance problem: high maintenance burden shown, [PRODUCT] low-maintenance alternative, time freed', 'veo-3.1', '{"product":"[PRODUCT]","problem":"maintenance","benefit":"time-saving"}', 'problem-solution,productivity,maintenance-reduction,benefit'),

(100, 'problem_solution', 'Scalability problem: growth outpaces current solution, bottleneck shown, [PRODUCT] scales, future-proof solution', 'veo-3.1', '{"product":"[PRODUCT]","problem":"scalability","benefit":"growth"}', 'problem-solution,scalability,growth,benefit'),
(100, 'problem_solution', 'Collaboration problem: team coordination difficulty, miscommunication shown, [PRODUCT] enables collaboration, teamwork smooth', 'veo-3.1', '{"product":"[PRODUCT]","problem":"collaboration","benefit":"teamwork"}', 'problem-solution,collaboration,teamwork,benefit'),
(100, 'problem_solution', 'Storage problem: limited space or organization issues, clutter shown, [PRODUCT] storage solution, organization achieved', 'veo-3.1', '{"product":"[PRODUCT]","problem":"storage","solution_angle":"organization"}', 'problem-solution,organization,storage,benefit'),
(100, 'problem_solution', 'Performance problem: slow/sluggish experience, frustration shown, [PRODUCT] boosts performance, speed improvement felt', 'veo-3.1', '{"product":"[PRODUCT]","problem":"performance","metric":"speed"}', 'problem-solution,performance,efficiency,benefit'),
(100, 'problem_solution', 'Reliability problem: unreliable current solution, failure risks shown, [PRODUCT] dependable alternative, trust restored', 'veo-3.1', '{"product":"[PRODUCT]","problem":"reliability","solution_angle":"trustworthiness"}', 'problem-solution,reliability,trust,benefit'),

-- CATEGORY: Service-Specific Prompts (30 prompts)
(100, 'service', '[PRODUCT] fitness service: workout guidance shown, training program explained, results transformation captured, health journey', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"fitness","benefit":"health"}', 'service,fitness,health,transformation'),
(100, 'service', '[PRODUCT] consulting service: expert advice given, business problem solved, strategic guidance, professional context', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"consulting","expertise":"professional"}', 'service,professional,expertise,business'),
(100, 'service', '[PRODUCT] educational service: learning content, skill development, transformation shown, educational value', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"education","benefit":"knowledge"}', 'service,education,learning,development'),
(100, 'service', '[PRODUCT] beauty/wellness service: pampering experience, relaxation focus, self-care narrative, luxury appeal', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"beauty","tone":"luxurious"}', 'service,beauty,wellness,luxury'),
(100, 'service', '[PRODUCT] financial service: money guidance, investment advice, wealth building, financial security', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"financial","benefit":"security"}', 'service,financial,wealth,security'),

(100, 'service', '[PRODUCT] childcare/tutoring service: child development, parent perspective, safety emphasis, growth shown', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"childcare","audience":"parent"}', 'service,childcare,family,education'),
(100, 'service', '[PRODUCT] home service: professional expertise, quality work, home improvement, transformation shown', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"home","transformation":"yes"}', 'service,home,professional,quality'),
(100, 'service', '[PRODUCT] healthcare service: medical expertise, patient outcome, health improvement, trustworthiness', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"healthcare","benefit":"health"}', 'service,healthcare,professional,trust'),
(100, 'service', '[PRODUCT] legal service: professional advice, problem resolution, peace of mind, expertise shown', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"legal","benefit":"security"}', 'service,legal,professional,expertise'),
(100, 'service', '[PRODUCT] transportation service: convenience, reliability, time-saving, travel ease emphasized', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"transportation","benefit":"convenience"}', 'service,transportation,convenience,reliability'),

(100, 'service', '[PRODUCT] pet care service: pet health, animal welfare, owner peace of mind, care quality', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"pet","focus":"animal-wellness"}', 'service,pets,wellness,caregiving'),
(100, 'service', '[PRODUCT] wedding service: event special, celebration captured, emotional moments, joy reflected', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"wedding","emotion":"joy"}', 'service,events,celebration,emotional'),
(100, 'service', '[PRODUCT] tech support service: problem solving, troubleshooting, technical expertise, customer success', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"tech-support","expertise":"technical"}', 'service,support,technical,expertise'),
(100, 'service', '[PRODUCT] catering service: food quality, event experience, culinary expertise, hospitality shown', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"catering","focus":"hospitality"}', 'service,food,hospitality,professional'),
(100, 'service', '[PRODUCT] photography service: visual storytelling, memory preservation, professional results, emotional value', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"photography","benefit":"memory-preservation"}', 'service,photography,storytelling,professional'),

(100, 'service', '[PRODUCT] moving service: logistics expertise, stress reduction, smooth relocation, professional efficiency', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"moving","benefit":"stress-reduction"}', 'service,logistics,professional,efficiency'),
(100, 'service', '[PRODUCT] repair service: expert fixing, product restoration, quality craftsmanship, problem solved', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"repair","focus":"restoration"}', 'service,repair,craftsmanship,expertise'),
(100, 'service', '[PRODUCT] cleaning service: cleanliness achieved, time-saving, property protection, professional quality', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"cleaning","benefit":"time-saving"}', 'service,cleaning,professional,efficiency'),
(100, 'service', '[PRODUCT] event planning service: seamless execution, stress-free coordination, memorable experience, professional management', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"event-planning","benefit":"stress-reduction"}', 'service,events,planning,professional'),
(100, 'service', '[PRODUCT] coaching service: performance improvement, personal growth, expert guidance, mentorship shown', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"coaching","benefit":"growth"}', 'service,coaching,mentorship,development'),

(100, 'service', '[PRODUCT] design service: creative vision, professional aesthetics, brand transformation, visual impact', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"design","focus":"creativity"}', 'service,design,professional,aesthetic'),
(100, 'service', '[PRODUCT] writing/copywriting service: persuasive content, professional writing, communication power, impact shown', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"writing","focus":"persuasion"}', 'service,writing,professional,communication'),
(100, 'service', '[PRODUCT] translation service: language bridge, cultural understanding, communication enabled, professional quality', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"translation","benefit":"communication"}', 'service,translation,communication,professional'),
(100, 'service', '[PRODUCT] accounting service: financial organization, tax expertise, business clarity, peace of mind', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"accounting","benefit":"security"}', 'service,accounting,professional,expertise'),
(100, 'service', '[PRODUCT] marketing service: campaign expertise, growth strategy, brand visibility, business results', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"marketing","benefit":"growth"}', 'service,marketing,strategy,business-results'),

(100, 'service', '[PRODUCT] real estate service: property expertise, market knowledge, successful transactions, professional guidance', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"real-estate","expertise":"market"}', 'service,real-estate,professional,expertise'),
(100, 'service', '[PRODUCT] insurance service: risk protection, peace of mind, coverage explained, security provided', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"insurance","benefit":"security"}', 'service,insurance,protection,peace-of-mind'),
(100, 'service', '[PRODUCT] recruitment service: talent placement, career opportunity, right fit, professional matching', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"recruitment","benefit":"opportunity"}', 'service,recruitment,professional,career'),
(100, 'service', '[PRODUCT] subscription service: ongoing value, recurring benefit, convenience, loyalty rewards', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"subscription","benefit":"convenience"}', 'service,subscription,loyalty,recurring'),
(100, 'service', '[PRODUCT] membership service: exclusive benefits, community belonging, special access, value for money', 'veo-3.1', '{"product":"[PRODUCT]","service_type":"membership","benefit":"belonging"}', 'service,membership,community,exclusive'),

-- CATEGORY: Lifestyle & Aspirational (20 prompts)
(100, 'lifestyle', '[PRODUCT] luxury lifestyle aesthetic: product integrated seamlessly into high-end setting, premium ambiance, sophistication, aspirational living, editorial styling, cinematic lighting', 'veo-3.1', '{"product":"[PRODUCT]","tone":"luxury","setting":"premium"}', 'lifestyle,luxury,aspirational,aesthetic'),
(100, 'lifestyle', '[PRODUCT] daily essentials showcase: product shown as indispensable in routine, morning/evening integration, practical yet beautiful, relatable lifestyle moment, soft natural lighting', 'veo-3.1', '{"product":"[PRODUCT]","integration":"daily","tone":"practical"}', 'lifestyle,routine,relatable,daily-essential'),
(100, 'lifestyle', '[PRODUCT] wellness ritual: product part of self-care moment, holistic wellbeing emphasized, calming aesthetic, mindfulness theme, spa-like ambiance, peaceful energy', 'veo-3.1', '{"product":"[PRODUCT]","category":"wellness","ritual":"self-care"}', 'lifestyle,wellness,mindfulness,self-care'),
(100, 'lifestyle', '[PRODUCT] productivity hack integration: product streamlines workflow, workspace organization, efficiency boost shown, modern minimalist aesthetic, professional but approachable', 'veo-3.1', '{"product":"[PRODUCT]","angle":"productivity","tone":"modern"}', 'lifestyle,productivity,efficiency,professional'),
(100, 'lifestyle', '[PRODUCT] adventure/travel companion: product enables travel experiences, adventure readiness, exploration theme, dynamic scenery, wanderlust inspiration', 'veo-3.1', '{"product":"[PRODUCT]","context":"travel","tone":"adventurous"}', 'lifestyle,travel,adventure,exploration'),

(100, 'lifestyle', '[PRODUCT] social gathering moment: product enhances gatherings, host appeal, entertaining angle, joyful energy, connection facilitation, group enjoyment', 'veo-3.1', '{"product":"[PRODUCT]","context":"social","emotion":"joyful"}', 'lifestyle,social,entertainment,gathering'),
(100, 'lifestyle', '[PRODUCT] creative expression enabler: product supports artistic pursuit, creative freedom, artistic energy, inspiration captured, maker/creator angle', 'veo-3.1', '{"product":"[PRODUCT]","angle":"creativity","audience":"creators"}', 'lifestyle,creative,artistic,inspiration'),
(100, 'lifestyle', '[PRODUCT] parent/caregiver essentials: product simplifies parenting/caregiving, reliability emphasized, peace of mind, family-first narrative, genuine care shown', 'veo-3.1', '{"product":"[PRODUCT]","context":"family","audience":"parent"}', 'lifestyle,family,caregiving,practical'),
(100, 'lifestyle', '[PRODUCT] milestone/celebration moment: product part of special occasion, celebration energy, emotional significance, joy captured, memorable experience', 'veo-3.1', '{"product":"[PRODUCT]","context":"celebration","emotion":"joy"}', 'lifestyle,celebration,emotional,memorable'),
(100, 'lifestyle', '[PRODUCT] seasonal/timely aesthetic: product perfectly suited for season, environmental relevance, timely appeal, seasonal living, relevant imagery', 'veo-3.1', '{"product":"[PRODUCT]","timing":"seasonal","relevance":"high"}', 'lifestyle,seasonal,timely,relevant'),

(100, 'lifestyle', '[PRODUCT] personal identity expression: product reflects personal style/values, identity component, self-expression, authenticity, individuality emphasized', 'veo-3.1', '{"product":"[PRODUCT]","angle":"identity","expression":"personal"}', 'lifestyle,identity,authenticity,personal'),
(100, 'lifestyle', '[PRODUCT] transformation milestone: product marks transition point, new chapter, growth moment, progression shown, aspirational shift', 'veo-3.1', '{"product":"[PRODUCT]","arc":"transformation","emotion":"hopeful"}', 'lifestyle,transformation,growth,aspiration'),
(100, 'lifestyle', '[PRODUCT] quiet moment aesthetic: product part of peaceful solitude, introspection, calm energy, meditative atmosphere, serene setting', 'veo-3.1', '{"product":"[PRODUCT]","tone":"peaceful","activity":"solitude"}', 'lifestyle,calm,meditation,serene'),
(100, 'lifestyle', '[PRODUCT] relationship/connection enabler: product brings people together, relationship deepening, bonding moment, connection theme, togetherness', 'veo-3.1', '{"product":"[PRODUCT]","theme":"connection","emotion":"warmth"}', 'lifestyle,relationship,connection,togetherness'),
(100, 'lifestyle', '[PRODUCT] aspirational goal visualization: product helps achieve goal, vision alignment, future self connection, motivation captured, goal-oriented narrative', 'veo-3.1', '{"product":"[PRODUCT]","narrative":"goal-pursuit","motivation":"high"}', 'lifestyle,aspiration,motivation,goal-oriented'),

(100, 'lifestyle', '[PRODUCT] cultural moment integration: product part of cultural trend/moment, relevance to zeitgeist, contemporary angle, timely connection', 'veo-3.1', '{"product":"[PRODUCT]","angle":"cultural","relevance":"moment"}', 'lifestyle,cultural,trend,contemporary'),
(100, 'lifestyle', '[PRODUCT] sustainability/values alignment: product reflects ethical values, conscious choice, values-based purchase, principle-driven narrative, impact shown', 'veo-3.1', '{"product":"[PRODUCT]","angle":"values","ethics":"conscious"}', 'lifestyle,sustainability,ethical,values-driven'),
(100, 'lifestyle', '[PRODUCT] confidence/empowerment moment: product enables confidence, self-belief, empowerment energy, strength expressed, capability highlighted', 'veo-3.1', '{"product":"[PRODUCT]","emotion":"empowerment","narrative":"self-belief"}', 'lifestyle,empowerment,confidence,strength'),
(100, 'lifestyle', '[PRODUCT] indulgence/treat moment: product as deserved treat, self-rewarding, pleasure centered, joy of enjoyment, guilt-free indulgence', 'veo-3.1', '{"product":"[PRODUCT]","tone":"indulgent","narrative":"self-reward"}', 'lifestyle,indulgence,pleasure,self-care'),
(100, 'lifestyle', '[PRODUCT] legacy/heirloom angle: product lasting investment, generational value, heirloom potential, quality endurance, timeless nature', 'veo-3.1', '{"product":"[PRODUCT]","angle":"legacy","duration":"long-term"}', 'lifestyle,legacy,investment,timeless'),

-- CATEGORY: Limited-Time Offer & Urgency (15 prompts)
(100, 'limited_offer', '[PRODUCT] exclusive launch moment: limited availability emphasized, first-mover advantage, scarcity introduced, urgency natural, FOMO element subtle, early-access highlight', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"launch","availability":"limited"}', 'limited-offer,urgency,exclusive,scarcity'),
(100, 'limited_offer', '[PRODUCT] flash sale energy: time-limited discount, countdown urgency, deal value highlighted, competitive rush implied, action-now messaging', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"flash-sale","duration":"limited"}', 'limited-offer,urgency,deal,flash-sale'),
(100, 'limited_offer', '[PRODUCT] seasonal limited edition: seasonal exclusivity, collector appeal, uniqueness emphasized, time-bound availability, collectibility angle', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"seasonal-limited","appeal":"collector"}', 'limited-offer,exclusive,seasonal,collector'),
(100, 'limited_offer', '[PRODUCT] waitlist/pre-order narrative: high demand indicated, supply scarcity, exclusivity messaging, early access opportunity, VIP treatment angle', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"pre-order","angle":"exclusivity"}', 'limited-offer,exclusive,pre-order,scarcity'),
(100, 'limited_offer', '[PRODUCT] bundle deal value: multiple items/services combined, value multiplication obvious, limited-time combo, savings emphasized, package appeal', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"bundle","benefit":"value"}', 'limited-offer,deal,bundle,value'),

(100, 'limited_offer', '[PRODUCT] loyalty reward exclusive: existing customer benefit, exclusive access, special treatment, relationship recognition, VIP status', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"loyalty","audience":"existing-customers"}', 'limited-offer,exclusive,loyalty,vip'),
(100, 'limited_offer', '[PRODUCT] regional/geo-exclusive: location-specific availability, regional launch, limited geographic reach, local exclusivity, travel incentive', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"geo-exclusive","scope":"regional"}', 'limited-offer,exclusive,regional,geo-limited'),
(100, 'limited_offer', '[PRODUCT] referral bonus highlight: reward for referring friends, word-of-mouth incentive, mutual benefit shown, sharing encouraged, growth mechanism', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"referral","incentive":"mutual"}', 'limited-offer,referral,growth,incentive'),
(100, 'limited_offer', '[PRODUCT] early-bird discount: time-limited price advantage, early action rewarded, urgency incentivized, countdown timer visual, deadline approach', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"early-bird","benefit":"discount"}', 'limited-offer,urgency,discount,time-limited'),
(100, 'limited_offer', '[PRODUCT] price increase coming: current price is best, future cost higher, buy-now justification, scarcity pricing, value capture window', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"price-increase-notice","urgency":"financial"}', 'limited-offer,urgency,pricing,scarcity'),

(100, 'limited_offer', '[PRODUCT] stock-running-low: inventory countdown, supply depletion, scarcity messaging, availability warning, don''t-miss-out energy', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"stock-limited","metric":"inventory"}', 'limited-offer,urgency,scarcity,inventory'),
(100, 'limited_offer', '[PRODUCT] limited quantity per customer: purchase cap, fairness messaging, equal access, scarcity management, responsible supply', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"quantity-limited","fairness":"yes"}', 'limited-offer,scarcity,fairness,limits'),
(100, 'limited_offer', '[PRODUCT] bonus with purchase: free item/service added, added value emphasized, savings multiplication, incentive sweetening, special bonus highlight', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"bonus","value":"added"}', 'limited-offer,bonus,incentive,value'),
(100, 'limited_offer', '[PRODUCT] expiring coupon/code: activation deadline, code scarcity, urgency introduced, deadline approach, use-it-or-lose-it narrative', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"coupon","expiry":"yes"}', 'limited-offer,urgency,discount,deadline'),
(100, 'limited_offer', '[PRODUCT] last chance messaging: final stock/deadline near, opportunity window closing, dramatic urgency, now-or-never energy, finality expressed', 'veo-3.1', '{"product":"[PRODUCT]","offer_type":"last-chance","emotion":"urgency"}', 'limited-offer,urgency,scarcity,dramatic'),

-- CATEGORY: Educational & Explainer (10 prompts)
(100, 'educational', '[PRODUCT] how-it-works explainer: mechanism/process revealed, innovation explained, technical breakdown, feature tour, educational deep-dive', 'veo-3.1', '{"product":"[PRODUCT]","format":"explainer","depth":"detailed"}', 'educational,explainer,how-it-works,technical'),
(100, 'educational', '[PRODUCT] science-backed benefits: research validation shown, scientific evidence, credibility building, mechanism explained, proof presented', 'veo-3.1', '{"product":"[PRODUCT]","angle":"science","credibility":"high"}', 'educational,science,credibility,evidence'),
(100, 'educational', '[PRODUCT] industry insights: expert perspective, professional context, market knowledge, insider viewpoint, authority lending', 'veo-3.1', '{"product":"[PRODUCT]","angle":"expert","authority":"industry"}', 'educational,expert,insights,authority'),
(100, 'educational', '[PRODUCT] common misconceptions addressed: myth-busting, education correcting, clarity provided, misinformation challenged, truth revealed', 'veo-3.1', '{"product":"[PRODUCT]","format":"myth-busting","education":"corrective"}', 'educational,myth-busting,clarification,education'),
(100, 'educational', '[PRODUCT] comparison guide: alternatives evaluated, differences highlighted, features mapped, educational comparison, informed choice enabled', 'veo-3.1', '{"product":"[PRODUCT]","format":"comparison","depth":"detailed"}', 'educational,comparison,guide,informed-choice'),

(100, 'educational', '[PRODUCT] use-case scenarios: real-world applications shown, practical usage examples, context demonstrated, versatility highlighted, application variety', 'veo-3.1', '{"product":"[PRODUCT]","format":"use-cases","variety":"multiple"}', 'educational,use-cases,practical,examples'),
(100, 'educational', '[PRODUCT] troubleshooting guide: common issues addressed, problem resolution, support provided, customer empowerment, solution shown', 'veo-3.1', '{"product":"[PRODUCT]","format":"troubleshooting","support":"proactive"}', 'educational,support,troubleshooting,help'),
(100, 'educational', '[PRODUCT] certification/standards explanation: compliance highlighted, quality standards met, regulation adherence, trust building, verification shown', 'veo-3.1', '{"product":"[PRODUCT]","angle":"compliance","credibility":"standards"}', 'educational,compliance,standards,certification'),
(100, 'educational', '[PRODUCT] sustainability explained: environmental impact detailed, eco-friendly features explained, manufacturing process shown, green messaging, impact transparency', 'veo-3.1', '{"product":"[PRODUCT]","angle":"sustainability","transparency":"yes"}', 'educational,sustainability,transparency,environmental'),
(100, 'educational', '[PRODUCT] investment justification: value breakdown, long-term ROI explained, cost-benefit analysis, financial justification, smart-purchase framing', 'veo-3.1', '{"product":"[PRODUCT]","angle":"financial","format":"roi-breakdown"}', 'educational,financial,investment,value');
