-- Batch 99: Person-Based Video Prompts (100)
-- High-quality, diverse person video prompts with [PERSON_IMAGE] parameterization
-- Categories: UGC, lifestyle, transformation, challenge, testimonial, tutorial, storytelling

INSERT INTO prompts (batch_id, category, prompt_text, model, parameters, tags) VALUES

-- CATEGORY: UGC Authentic (15 prompts)
(99, 'ugc_authentic', 'Close-up of [PERSON_IMAGE] looking directly at camera with genuine smile, soft natural lighting, casual home setting, speaking about daily routine, 9:16 vertical, authentic phone vlog aesthetic, warm color grading', 'veo-3.1', '{"person_image":"required","tone":"authentic","duration":"15-30s"}', 'ugc,authentic,relatable,direct-to-camera'),
(99, 'ugc_authentic', '[PERSON_IMAGE] holding coffee mug in bright morning kitchen, golden hour sunlight streaming through window, candid laugh, natural movement, lifestyle morning vlog, 4K vertical video', 'veo-3.1', '{"person_image":"required","prop":"coffee","setting":"kitchen"}', 'ugc,lifestyle,morning,relatable'),
(99, 'ugc_authentic', 'First-person POV: [PERSON_IMAGE] walking through farmer''s market, picking fresh produce, pointing to items with enthusiasm, natural lighting, handheld camera movement, 9:16 vertical', 'veo-3.1', '{"person_image":"required","location":"market","activity":"shopping"}', 'ugc,lifestyle,shopping,authentic'),
(99, 'ugc_authentic', '[PERSON_IMAGE] sitting on living room couch, scrolling phone, looking up with surprised expression, genuine reaction to something on screen, soft indoor lighting, intimate camera angle', 'veo-3.1', '{"person_image":"required","emotion":"surprised","setting":"home"}', 'ugc,reaction,authentic,emotional'),
(99, 'ugc_authentic', 'Mid-shot: [PERSON_IMAGE] getting ready for day, applying skincare product, speaking to camera, natural bathroom lighting, authentic morning routine, no makeup, relatable content', 'veo-3.1', '{"person_image":"required","routine":"skincare","setting":"bathroom"}', 'ugc,tutorial,routine,authentic'),

-- CATEGORY: Transformation Story (15 prompts)
(99, 'transformation', '[PERSON_IMAGE] before-transformation look: casual home clothes, tired expression. Quick transition to after: styled outfit, confident posture, glowing skin, same location but enhanced lighting, emotional journey arc', 'veo-3.1', '{"person_image":"required","before_after":"yes","transformation_type":"style"}', 'transformation,before-after,empowerment,journey'),
(99, 'transformation', '[PERSON_IMAGE] doing workout: starting tired and breathless, progressing through exercises, final shot confident and energized, home gym setting, real sweat, authentic strain then relief', 'veo-3.1', '{"person_image":"required","activity":"workout","intensity":"high"}', 'transformation,fitness,motivation,journey'),
(99, 'transformation', 'Time-lapse: [PERSON_IMAGE] getting glam makeover over 60 seconds - hair styling, makeup application, outfit change, final twirl reveal, professional lighting, dramatic transformation', 'veo-3.1', '{"person_image":"required","type":"glam_makeover","duration":"60s"}', 'transformation,makeover,glamour,dramatic'),
(99, 'transformation', '[PERSON_IMAGE] skill progression: awkward beginner attempt at dance move, cut to fluid professional execution, side-by-side split screen comparison, same choreography, clear improvement arc', 'veo-3.1', '{"person_image":"required","skill":"dance","progression":"yes"}', 'transformation,skill,progression,before-after'),
(99, 'transformation', '[PERSON_IMAGE] confidence journey: hunched shy posture, voice-over of internal doubt, transitions to open shoulders, direct eye contact, clear voice, uplifting music, empowerment narrative', 'veo-3.1', '{"person_image":"required","theme":"confidence","arc":"emotional"}', 'transformation,empowerment,mindset,emotional'),

-- CATEGORY: Reaction & Emotional (15 prompts)
(99, 'reaction', '[PERSON_IMAGE] watching something off-screen with extreme suspense, edge-of-seat tension, eyes wide, biting nails, sudden shock reaction, genuine surprise, close-up emotional capture, 4K', 'veo-3.1', '{"person_image":"required","emotion":"shock","intensity":"high"}', 'reaction,emotional,suspense,entertainment'),
(99, 'reaction', '[PERSON_IMAGE] laughing uncontrollably at joke or meme, contagious genuine laugh, can''t catch breath, tears forming, relatable humor moment, overhead lighting, intimate moment', 'veo-3.1', '{"person_image":"required","emotion":"joy","trigger":"humor"}', 'reaction,emotional,humor,relatable'),
(99, 'reaction', '[PERSON_IMAGE] seeing unexpected gift or surprise, gasps, hand over mouth, eyes lighting up, genuine gratitude expression, emotional peak moment, warm lighting, intimate framing', 'veo-3.1', '{"person_image":"required","emotion":"joy","trigger":"surprise"}', 'reaction,emotional,surprise,gratitude'),
(99, 'reaction', '[PERSON_IMAGE] focused intense stare, contemplative expression, deep thought moment, soft natural lighting, vulnerable introspective shot, no dialogue, powerful emotion, 30-second silence', 'veo-3.1', '{"person_image":"required","emotion":"contemplative","duration":"30s"}', 'reaction,emotional,introspective,vulnerable'),
(99, 'reaction', '[PERSON_IMAGE] failing at something funny, recovery laugh, self-deprecating humor, oops moment, relatable struggle, authentic reaction, light-hearted failure captured honestly', 'veo-3.1', '{"person_image":"required","scenario":"failure","tone":"humorous"}', 'reaction,emotional,humor,relatable,authentic'),

-- CATEGORY: Tutorial & How-To (15 prompts)
(99, 'tutorial', '[PERSON_IMAGE] teaching skincare routine: demonstrating product application step-by-step, clear close-ups of hands and face, explaining each step, professional lighting, beauty studio aesthetic, 4K', 'veo-3.1', '{"person_image":"required","topic":"skincare","steps":"5-7"}', 'tutorial,how-to,beauty,educational'),
(99, 'tutorial', '[PERSON_IMAGE] cooking lesson: prep ingredients, walking through recipe, tasting final dish with satisfied expression, kitchen setting, overhead and side angles, professional food lighting', 'veo-3.1', '{"person_image":"required","topic":"cooking","cuisine":"variable"}', 'tutorial,how-to,food,culinary'),
(99, 'tutorial', '[PERSON_IMAGE] home workout coach: demonstrating exercise with correct form, counting reps, encouraging energy, showing modifications for different levels, mirror angle, home gym aesthetic', 'veo-3.1', '{"person_image":"required","topic":"fitness","exercise_type":"variable"}', 'tutorial,how-to,fitness,health'),
(99, 'tutorial', '[PERSON_IMAGE] makeup tutorial: transformation focus, product recommendations, brush techniques, before/after comparison, professional lighting, clear close-ups, step-by-step narration', 'veo-3.1', '{"person_image":"required","topic":"makeup","technique":"variable"}', 'tutorial,how-to,beauty,makeup'),
(99, 'tutorial', '[PERSON_IMAGE] productivity hack demonstration: showing organization system, explaining time-saving technique, desk tour, before/after workspace, practical tips, office lighting', 'veo-3.1', '{"person_image":"required","topic":"productivity","hack":"variable"}', 'tutorial,how-to,productivity,lifestyle'),

-- CATEGORY: Challenge & Dare (12 prompts)
(99, 'challenge', '[PERSON_IMAGE] attempting viral challenge: trending dance, sound effect synced, full body visible, enthusiastic energy, multiple takes, playful mistakes included, fun competitive spirit', 'veo-3.1', '{"person_image":"required","challenge_type":"dance","difficulty":"medium"}', 'challenge,entertainment,trend,viral'),
(99, 'challenge', '[PERSON_IMAGE] extreme reaction challenge: tasting spicy food, immediate shock reaction, chugging water, sweating, genuine discomfort then relief laugh, close-up emotion capture', 'veo-3.1', '{"person_image":"required","challenge_type":"spicy","intensity":"extreme"}', 'challenge,entertainment,extreme,reaction'),
(99, 'challenge', '[PERSON_IMAGE] speed challenge: organizing closet or workspace within time limit, rapid movement, countdown timer, focused determination, before/after reveal, quick-cut editing', 'veo-3.1', '{"person_image":"required","challenge_type":"speed","activity":"organization"}', 'challenge,entertainment,productivity,time-lapse'),
(99, 'challenge', '[PERSON_IMAGE] trying new skill in 60 seconds: learning TikTok dance, basic juggling, or quick skill, awkward attempts, growing confidence, blooper moments, energetic music', 'veo-3.1', '{"person_image":"required","challenge_type":"skill","duration":"60s"}', 'challenge,entertainment,skill-learn,viral'),
(99, 'challenge', '[PERSON_IMAGE] duet/collaboration challenge: split-screen with someone else, mirrored movements, synchronized dance or action, playful competition, engaging energy, entertainment focus', 'veo-3.1', '{"person_image":"required","challenge_type":"duet","format":"split-screen"}', 'challenge,entertainment,duet,collaboration'),

-- CATEGORY: Testimonial & Story (15 prompts)
(99, 'testimonial', '[PERSON_IMAGE] sharing personal story: looking at camera, genuine emotion, vulnerability, speaking from heart about life lesson learned, authentic background, warm lighting, 60-second depth', 'veo-3.1', '{"person_image":"required","story_type":"personal","emotion":"vulnerable"}', 'testimonial,authentic,emotional,story'),
(99, 'testimonial', '[PERSON_IMAGE] product review: holding product, demonstrating features, explaining benefits, honest opinion expressed, real-life usage shown, natural lighting, authentic feedback tone', 'veo-3.1', '{"person_image":"required","product":"variable","tone":"honest"}', 'testimonial,review,product,authentic'),
(99, 'testimonial', '[PERSON_IMAGE] success story: achieving goal, showing results, explaining journey, inspirational narrative, before/after elements, motivational energy, documentary-style storytelling', 'veo-3.1', '{"person_image":"required","story_type":"success","arc":"transformation"}', 'testimonial,motivation,success,inspiring'),
(99, 'testimonial', '[PERSON_IMAGE] sharing advice: wisdom about life, career, or relationships, direct eye contact, thoughtful delivery, experience-based guidance, mentor energy, soft professional lighting', 'veo-3.1', '{"person_image":"required","topic":"advice","style":"mentoring"}', 'testimonial,advice,wisdom,educational'),
(99, 'testimonial', '[PERSON_IMAGE] grateful reflection: thanking someone or something, genuine appreciation, emotional moment, sincere delivery, natural setting, introspective tone, heartfelt moment', 'veo-3.1', '{"person_image":"required","emotion":"gratitude","format":"reflection"}', 'testimonial,emotional,gratitude,authentic'),

-- CATEGORY: Lifestyle & Daily Vlog (13 prompts)
(99, 'lifestyle', '[PERSON_IMAGE] morning routine montage: waking up, stretching, breakfast, getting ready, starting day with purpose, golden hour lighting, uplifting music, motivational energy', 'veo-3.1', '{"person_image":"required","time":"morning","tone":"motivational"}', 'lifestyle,routine,morning,montage'),
(99, 'lifestyle', '[PERSON_IMAGE] evening wind-down: self-care activities, skincare, journal writing, tea time, cozy lighting, relaxation focus, peaceful music, calming aesthetic', 'veo-3.1', '{"person_image":"required","time":"evening","tone":"relaxing"}', 'lifestyle,routine,evening,self-care'),
(99, 'lifestyle', '[PERSON_IMAGE] getting dressed: outfit styling from closet, showing coordination, fashion choices explained, full-length mirror shot, confidence expression, fashionable energy', 'veo-3.1', '{"person_image":"required","activity":"styling","focus":"fashion"}', 'lifestyle,fashion,styling,routine'),
(99, 'lifestyle', '[PERSON_IMAGE] workspace setup: organizing desk, arranging supplies, showing productivity system, explaining setup choices, professional or creative aesthetic, bright lighting', 'veo-3.1', '{"person_image":"required","activity":"workspace","style":"professional"}', 'lifestyle,productivity,workspace,organization'),
(99, 'lifestyle', '[PERSON_IMAGE] self-care day: spa activities, relaxation moments, pampering routine, luxurious aesthetic, calming music, wellness focus, indulgent but healthy vibe', 'veo-3.1', '{"person_image":"required","activity":"self-care","tone":"luxurious"}', 'lifestyle,wellness,self-care,luxury'),

-- CATEGORY: Motivational & Inspirational (10 prompts)
(99, 'motivational', '[PERSON_IMAGE] overcoming obstacle: showing struggle, perseverance, breakthrough moment, emotional intensity, triumph feeling, uplifting music, inspiring narrative arc, powerful cinematography', 'veo-3.1', '{"person_image":"required","theme":"perseverance","emotion":"triumph"}', 'motivational,inspiring,emotional,powerful'),
(99, 'motivational', '[PERSON_IMAGE] goal achievement celebration: excited expression, genuine joy, success moment captured, celebratory movement, encouraging others vibe, infectious enthusiasm, bright lighting', 'veo-3.1', '{"person_image":"required","theme":"achievement","emotion":"joy"}', 'motivational,inspiring,celebratory,emotional'),
(99, 'motivational', '[PERSON_IMAGE] speaking motivational message: direct address to camera, confidence in delivery, inspiring words, eye contact, professional framing, powerful message, dramatic lighting', 'veo-3.1', '{"person_image":"required","theme":"motivation","format":"speech"}', 'motivational,inspiring,educational,powerful'),
(99, 'motivational', '[PERSON_IMAGE] showing growth: comparing past self to present, visible improvement, authentic reflection, proud expression, journey acknowledged, inspirational tone, documentary style', 'veo-3.1', '{"person_image":"required","theme":"growth","format":"comparison"}', 'motivational, inspiring,growth,transformation'),
(99, 'motivational', '[PERSON_IMAGE] paying it forward: helping someone else, mentoring moment, generous action, positive impact shown, feel-good narrative, uplifting music, community spirit', 'veo-3.1', '{"person_image":"required","theme":"generosity","action":"helping"}', 'motivational,inspiring,emotional,community'),

-- CATEGORY: Comedy & Entertainment (10 prompts)
(99, 'comedy', '[PERSON_IMAGE] comedy skit: exaggerated expressions, physical humor, funny scenario setup, unexpected punchline, comedic timing, entertaining premise, energetic delivery, audience laughter vibes', 'veo-3.1', '{"person_image":"required","style":"skit","tone":"comedic"}', 'comedy,entertainment,humor,skit'),
(99, 'comedy', '[PERSON_IMAGE] relatable fails: funny mistakes, awkward moments, recovery laugh, self-deprecating humor, authentic blooper, light-hearted energy, humanizing moment, entertaining capture', 'veo-3.1', '{"person_image":"required","style":"blooper","tone":"funny"}', 'comedy,entertainment,relatable,blooper'),
(99, 'comedy', '[PERSON_IMAGE] parody or impersonation: exaggerated character portrayal, funny mimicking, entertainment-focused, comedic expression, over-the-top energy, entertaining performance', 'veo-3.1', '{"person_image":"required","style":"parody","tone":"comedic"}', 'comedy,entertainment,parody,performance'),
(99, 'comedy', '[PERSON_IMAGE] comedy lip-sync: synced to funny audio, exaggerated expressions, physical comedy, entertainment energy, viral potential, fun movement, comedic timing', 'veo-3.1', '{"person_image":"required","style":"lip-sync","tone":"comedic"}', 'comedy,entertainment,lip-sync,viral'),
(99, 'comedy', '[PERSON_IMAGE] trying trending sounds: audio-synced content, exaggerated reactions, comedic interpretation, entertainment focus, trend-following energy, fun movement, audience engagement', 'veo-3.1', '{"person_image":"required","style":"trending_sound","tone":"comedic"}', 'comedy,entertainment,trend,viral'),
