/**
 * User Tier Tracking (Database Schema + CRUD)
 * Stripe integration + subscription management
 */

import { getPool } from '../db/postgres-real.js';

export type UserTier = 'free' | 'starter' | 'pro' | 'agency';

export interface UserTierRecord {
  userId: string;
  email: string;
  tier: UserTier;
  stripeCustomerId: string | null;
  stripeSubscriptionId: string | null;
  campaignsUsedThisMonth: number;
  campaignsLimit: number;
  batchLimit: number;
  carouselsLimit: number;
  storiesLimit: number;
  videosLimit: number;
  profilesLimit: number;
  storageGb: number;
  customBrandKit: boolean;
  analyticsDepth: 'basic' | 'advanced';
  supportLevel: 'community' | 'email' | 'email-24h' | '24h-priority';
  monthlyPriceUsd: number;
  monthlyPriceArs: number;
  createdAt: Date;
  updatedAt: Date;
  subscriptionEndDate: Date | null;
  autoRenew: boolean;
}

// Per-format monthly quotas. "videos" covers reels + TikTok content — both are
// short vertical video generated by the same pipeline at the same cost, just
// published to different platforms, so a single shared quota reflects the
// actual cost driver instead of splitting it by destination.
// Exported as the single source of truth for tier limits/pricing — Stripe
// checkout, Mercado Pago checkout, and the pricing/checkout pages should all
// read from here instead of hand-copying numbers (that drift is exactly how
// Mercado Pago ended up billing $79 ARS — the USD digits copy-pasted with the
// wrong currency).
export const tierConfig = {
  free: {
    campaignsLimit: 5,
    batchLimit: 1,
    carouselsLimit: 3,
    storiesLimit: 2,
    videosLimit: 0,
    profilesLimit: 1,
    storageGb: 0.5,
    customBrandKit: false,
    analyticsDepth: 'basic' as const,
    supportLevel: 'community' as const,
    monthlyPriceUsd: 0,
    monthlyPriceArs: 0,
  },
  starter: {
    campaignsLimit: 20,
    batchLimit: 3,
    carouselsLimit: 12,
    storiesLimit: 6,
    videosLimit: 2,
    profilesLimit: 2,
    storageGb: 5,
    customBrandKit: false,
    analyticsDepth: 'basic' as const,
    supportLevel: 'email' as const,
    monthlyPriceUsd: 19,
    monthlyPriceArs: 29900,
  },
  pro: {
    campaignsLimit: 50,
    batchLimit: 10,
    carouselsLimit: 25,
    storiesLimit: 15,
    videosLimit: 10,
    profilesLimit: 6,
    storageGb: 50,
    customBrandKit: true,
    analyticsDepth: 'advanced' as const,
    supportLevel: 'email-24h' as const,
    monthlyPriceUsd: 79,
    monthlyPriceArs: 119900,
  },
  agency: {
    campaignsLimit: 500,
    batchLimit: 100,
    carouselsLimit: 250,
    storiesLimit: 150,
    videosLimit: 100,
    profilesLimit: 20,
    storageGb: 500,
    customBrandKit: true,
    analyticsDepth: 'advanced' as const,
    supportLevel: '24h-priority' as const,
    monthlyPriceUsd: 499,
    monthlyPriceArs: 749900,
  },
};

/**
 * Initialize user_tiers table
 */
export const initializeUserTiersTable = async (): Promise<void> => {
  try {
    console.log('[UserTiers] Initializing user_tiers table');

    await getPool().query(`
      CREATE TABLE IF NOT EXISTS user_tiers (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL UNIQUE,
        email TEXT NOT NULL,
        tier TEXT NOT NULL CHECK (tier IN ('free', 'starter', 'pro', 'agency')),
        stripe_customer_id TEXT,
        stripe_subscription_id TEXT,
        campaigns_used_this_month INTEGER DEFAULT 0,
        campaigns_limit INTEGER NOT NULL,
        batch_limit INTEGER NOT NULL,
        carousels_limit INTEGER NOT NULL DEFAULT 3,
        stories_limit INTEGER NOT NULL DEFAULT 2,
        videos_limit INTEGER NOT NULL DEFAULT 0,
        profiles_limit INTEGER NOT NULL DEFAULT 1,
        storage_gb NUMERIC(10,2) NOT NULL DEFAULT 0.5,
        custom_brand_kit BOOLEAN DEFAULT false,
        analytics_depth TEXT DEFAULT 'basic',
        support_level TEXT DEFAULT 'community',
        monthly_price DECIMAL(10,2) DEFAULT 0,
        monthly_price_usd DECIMAL(10,2) DEFAULT 0,
        monthly_price_ars DECIMAL(12,2) DEFAULT 0,
        subscription_end_date TIMESTAMP,
        auto_renew BOOLEAN DEFAULT true,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
      );

      -- Table pre-dates the starter tier + per-format quotas: add the new
      -- columns/values for deployments where it already exists.
      ALTER TABLE user_tiers ADD COLUMN IF NOT EXISTS carousels_limit INTEGER NOT NULL DEFAULT 3;
      ALTER TABLE user_tiers ADD COLUMN IF NOT EXISTS stories_limit INTEGER NOT NULL DEFAULT 2;
      ALTER TABLE user_tiers ADD COLUMN IF NOT EXISTS videos_limit INTEGER NOT NULL DEFAULT 0;
      ALTER TABLE user_tiers ADD COLUMN IF NOT EXISTS profiles_limit INTEGER NOT NULL DEFAULT 1;
      ALTER TABLE user_tiers ADD COLUMN IF NOT EXISTS storage_gb NUMERIC(10,2) NOT NULL DEFAULT 0.5;
      ALTER TABLE user_tiers ADD COLUMN IF NOT EXISTS monthly_price_usd DECIMAL(10,2) DEFAULT 0;
      ALTER TABLE user_tiers ADD COLUMN IF NOT EXISTS monthly_price_ars DECIMAL(12,2) DEFAULT 0;

      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1 FROM pg_constraint WHERE conname = 'user_tiers_tier_check'
        ) THEN
          ALTER TABLE user_tiers DROP CONSTRAINT user_tiers_tier_check;
        END IF;
        ALTER TABLE user_tiers ADD CONSTRAINT user_tiers_tier_check
          CHECK (tier IN ('free', 'starter', 'pro', 'agency'));
      END $$;

      CREATE INDEX IF NOT EXISTS idx_user_tiers_user_id ON user_tiers (user_id);
      CREATE INDEX IF NOT EXISTS idx_user_tiers_email ON user_tiers (email);
      CREATE INDEX IF NOT EXISTS idx_user_tiers_stripe_customer ON user_tiers (stripe_customer_id);
    `);

    console.log('[UserTiers] Table initialized');
  } catch (err) {
    console.error('[UserTiers] Failed to initialize:', err);
    throw err;
  }
};

/**
 * Create or update user tier record
 */
export const upsertUserTier = async (
  userId: string,
  email: string,
  tier: UserTier,
  stripeCustomerId?: string,
): Promise<UserTierRecord> => {
  try {
    const config = tierConfig[tier];
    const recordId = `tier_${userId}`;

    const result = await getPool().query(
      `INSERT INTO user_tiers
       (id, user_id, email, tier, stripe_customer_id, campaigns_limit, batch_limit,
        carousels_limit, stories_limit, videos_limit, profiles_limit, storage_gb,
        custom_brand_kit, analytics_depth, support_level,
        monthly_price, monthly_price_usd, monthly_price_ars, updated_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $16, $17, NOW())
       ON CONFLICT (user_id) DO UPDATE SET
         tier = $4,
         stripe_customer_id = COALESCE($5, user_tiers.stripe_customer_id),
         campaigns_limit = $6,
         batch_limit = $7,
         carousels_limit = $8,
         stories_limit = $9,
         videos_limit = $10,
         profiles_limit = $11,
         storage_gb = $12,
         custom_brand_kit = $13,
         analytics_depth = $14,
         support_level = $15,
         monthly_price = $16,
         monthly_price_usd = $16,
         monthly_price_ars = $17,
         updated_at = NOW()
       RETURNING *`,
      [
        recordId,
        userId,
        email,
        tier,
        stripeCustomerId || null,
        config.campaignsLimit,
        config.batchLimit,
        config.carouselsLimit,
        config.storiesLimit,
        config.videosLimit,
        config.profilesLimit,
        config.storageGb,
        config.customBrandKit,
        config.analyticsDepth,
        config.supportLevel,
        config.monthlyPriceUsd,
        config.monthlyPriceArs,
      ],
    );

    if (!result.rows || result.rows.length === 0) {
      throw new Error(`Failed to upsert tier for user ${userId}`);
    }

    return parseUserTierRecord(result.rows[0]);
  } catch (err) {
    console.error('[UserTiers] Upsert failed:', err);
    throw err;
  }
};

/**
 * Get user tier by ID
 */
export const getUserTier = async (userId: string): Promise<UserTierRecord | null> => {
  try {
    const result = await getPool().query(`SELECT * FROM user_tiers WHERE user_id = $1`, [userId]);

    if (!result.rows || result.rows.length === 0) {
      return null;
    }

    return parseUserTierRecord(result.rows[0]);
  } catch (err) {
    console.error('[UserTiers] Get failed:', err);
    return null;
  }
};

/**
 * Record campaign usage
 */
export const incrementCampaignUsage = async (userId: string, count: number = 1): Promise<boolean> => {
  try {
    const result = await getPool().query(
      `UPDATE user_tiers
       SET campaigns_used_this_month = campaigns_used_this_month + $1,
           updated_at = NOW()
       WHERE user_id = $2`,
      [count, userId],
    );

    return (result.rowCount || 0) > 0;
  } catch (err) {
    console.error('[UserTiers] Usage increment failed:', err);
    return false;
  }
};

/**
 * Reset monthly usage (call on 1st of month)
 */
export const resetMonthlyUsage = async (): Promise<void> => {
  try {
    await getPool().query(
      `UPDATE user_tiers
       SET campaigns_used_this_month = 0
       WHERE tier != 'free'`,
    );

    console.log('[UserTiers] Monthly usage reset');
  } catch (err) {
    console.error('[UserTiers] Reset failed:', err);
  }
};

/**
 * Link Stripe subscription to user
 */
export const linkStripeSubscription = async (
  userId: string,
  stripeCustomerId: string,
  stripeSubscriptionId: string,
  subscriptionEndDate: Date,
): Promise<boolean> => {
  try {
    const result = await getPool().query(
      `UPDATE user_tiers
       SET stripe_customer_id = $1,
           stripe_subscription_id = $2,
           subscription_end_date = $3,
           auto_renew = true,
           updated_at = NOW()
       WHERE user_id = $4`,
      [stripeCustomerId, stripeSubscriptionId, subscriptionEndDate, userId],
    );

    return (result.rowCount || 0) > 0;
  } catch (err) {
    console.error('[UserTiers] Stripe link failed:', err);
    return false;
  }
};

/**
 * Parse database row to UserTierRecord
 */
function parseUserTierRecord(row: Record<string, unknown>): UserTierRecord {
  return {
    userId: String(row.user_id || ''),
    email: String(row.email || ''),
    tier: (row.tier as UserTier) || 'free',
    stripeCustomerId: (row.stripe_customer_id as string | null) || null,
    stripeSubscriptionId: (row.stripe_subscription_id as string | null) || null,
    campaignsUsedThisMonth: Number(row.campaigns_used_this_month || 0),
    campaignsLimit: Number(row.campaigns_limit || 5),
    batchLimit: Number(row.batch_limit || 1),
    carouselsLimit: Number(row.carousels_limit ?? 3),
    storiesLimit: Number(row.stories_limit ?? 2),
    videosLimit: Number(row.videos_limit ?? 0),
    profilesLimit: Number(row.profiles_limit ?? 1),
    storageGb: Number(row.storage_gb ?? 0.5),
    customBrandKit: Boolean(row.custom_brand_kit || false),
    analyticsDepth: (row.analytics_depth as 'basic' | 'advanced') || 'basic',
    supportLevel: (row.support_level as 'community' | 'email' | 'email-24h' | '24h-priority') || 'community',
    monthlyPriceUsd: Number(row.monthly_price_usd ?? row.monthly_price ?? 0),
    monthlyPriceArs: Number(row.monthly_price_ars || 0),
    createdAt: new Date(String(row.created_at || Date.now())),
    updatedAt: new Date(String(row.updated_at || Date.now())),
    subscriptionEndDate: row.subscription_end_date
      ? new Date(String(row.subscription_end_date))
      : null,
    autoRenew: Boolean(row.auto_renew || true),
  };
}
