export const h=(e,t={},a=[])=>{const n=document.createElement(e);return Object.entries(t).forEach(([o,r])=>{r===!1||r===null||r===void 0||(o==="class"?n.className=r:o==="html"?n.innerHTML=r:o.startsWith("on")&&typeof r=="function"?n.addEventListener(o.slice(2).toLowerCase(),r):o==="style"&&typeof r=="object"?Object.assign(n.style,r):n.setAttribute(o,r))}),(Array.isArray(a)?a:[a]).forEach(o=>{o==null||o===!1||n.append(o instanceof Node?o:document.createTextNode(String(o)))}),n},escape=e=>String(e??"").replace(/[&<>"']/g,t=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[t]),empty=e=>`<div class="empty">${escape(e)}</div>`,fmt={num:e=>typeof e=="number"?e.toLocaleString():"\u2014",date:e=>e?new Date(e).toLocaleString():"\u2014",rel:e=>{if(!e)return"\u2014";const t=Date.now()-new Date(e).getTime(),a=Math.floor(t/6e4);if(a<60)return`hace ${a} min`;const n=Math.floor(a/60);return n<24?`hace ${n}h`:`hace ${Math.floor(n/24)}d`}},setView=(e,t)=>{e.innerHTML=t};const s=()=>{try{return window.self!==window.top}catch{return!0}},i=async e=>{document.querySelectorAll(".feedia-extlink-modal").forEach(n=>n.remove());const t=document.createElement("div");t.className="feedia-extlink-modal",t.innerHTML=`
    <div class="feedia-extlink-backdrop"></div>
    <div class="feedia-extlink-card">
      <div class="feedia-extlink-icon">\u{1F517}</div>
      <h3 class="feedia-extlink-title">Abrir en otra pesta\xF1a</h3>
      <p class="feedia-extlink-sub">Este entorno bloquea aperturas autom\xE1ticas. Toc\xE1 el link para abrirlo en una pesta\xF1a nueva, o copialo.</p>
      <a class="feedia-extlink-url" href="${e}" target="_blank" rel="noopener noreferrer">${e}</a>
      <div class="feedia-extlink-actions">
        <button class="feedia-extlink-copy">\u{1F4CB} Copiar URL</button>
        <button class="feedia-extlink-close">Cerrar</button>
      </div>
    </div>`,document.body.appendChild(t);const a=()=>t.remove();t.querySelector(".feedia-extlink-backdrop").addEventListener("click",a),t.querySelector(".feedia-extlink-close").addEventListener("click",a),t.querySelector(".feedia-extlink-copy").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(e);const n=t.querySelector(".feedia-extlink-copy");n.textContent="\u2713 Copiado",setTimeout(a,800)}catch{}}),document.addEventListener("keydown",function n(o){o.key==="Escape"&&(a(),document.removeEventListener("keydown",n))})};export const openExternal=async e=>{if(!e)return{opened:!1,shownModal:!1,url:e};if(s())return await i(e),{opened:!1,shownModal:!0,url:e};try{if(window.open(e,"_blank","noopener,noreferrer"))return{opened:!0,shownModal:!1,url:e}}catch{}return await i(e),{opened:!1,shownModal:!0,url:e}};
