const n=[{id:"home",label:"\u{1F3E0} Home",kw:"home inicio empezar",route:"home"},{id:"brujula",label:"\u{1F9ED} Br\xFAjula del D\xEDa",kw:"brujula plan tema hoy",route:"brujula"},{id:"handsfree",label:"\u{1F399}\uFE0F Manos Libres",kw:"manos libres voz dictar feedia",route:"handsfree"},{id:"brandkit",label:"\u{1F3A8} Brand Kit",kw:"brand kit colores marca tipografia logo",route:"brandkit"},{id:"studio-carousel",label:"\u{1F5BC}\uFE0F Carrusel",kw:"carrusel slides instagram crear",route:"studio-carousel"},{id:"studio-reel",label:"\u{1F3AC} Reel",kw:"reel video corto vertical",route:"studio-reel"},{id:"studio-stories",label:"\u{1F4F1} Historia",kw:"historia stories 9 16 frames",route:"studio-stories"},{id:"calendar",label:"\u{1F4C5} Calendario",kw:"calendar agenda planificar",route:"calendar"},{id:"agents",label:"\u{1F916} Agentes",kw:"agentes IA equipo",route:"agents"},{id:"community",label:"\u{1F4AC} Comunidad",kw:"comunidad community dm comentarios responder",route:"community"},{id:"analytics",label:"\u{1F4CA} Analytics",kw:"analytics metricas datos performance",route:"analytics"},{id:"settings",label:"\u2699\uFE0F Configuraci\xF3n",kw:"settings ajustes config cuenta",route:"settings"}],u=`
<div class="qp-overlay" id="qp-overlay">
  <div class="qp-panel">
    <input type="text" class="qp-input" id="qp-input" placeholder="Busc\xE1 vista, herramienta o acci\xF3n\u2026" autocomplete="off" />
    <div class="qp-list" id="qp-list"></div>
    <div class="qp-foot">\u2191\u2193 navegar \xB7 \u21B5 abrir \xB7 esc cerrar</div>
  </div>
</div>`,m=`
.qp-overlay{position:fixed;inset:0;background:rgba(0,0,0,.65);backdrop-filter:blur(8px);z-index:99999;display:flex;align-items:flex-start;justify-content:center;padding:14vh 16px 0;animation:qp-fade .15s ease-out;}
@keyframes qp-fade{from{opacity:0;}to{opacity:1;}}
.qp-panel{width:100%;max-width:560px;background:#0F0F14;border:1px solid rgba(255,255,255,.12);border-radius:14px;overflow:hidden;box-shadow:0 24px 80px rgba(0,0,0,.6);}
.qp-input{width:100%;background:transparent;border:none;border-bottom:1px solid rgba(255,255,255,.08);color:#fff;font-size:15px;padding:16px 18px;font-family:inherit;outline:none;}
.qp-input::placeholder{color:#6B7280;}
.qp-list{max-height:50vh;overflow-y:auto;padding:6px 0;}
.qp-item{display:flex;align-items:center;gap:10px;padding:9px 18px;cursor:pointer;font-size:13.5px;color:#D1D5DB;transition:background .1s;}
.qp-item.active,.qp-item:hover{background:rgba(168,85,247,.12);color:#fff;}
.qp-empty{padding:16px 18px;color:#6B7280;font-size:12.5px;}
.qp-foot{padding:10px 18px;font-size:11px;color:#4B5563;border-top:1px solid rgba(255,255,255,.05);letter-spacing:.5px;}
/* Scroll-to-top button */
.qp-stt{position:fixed;bottom:80px;right:24px;width:38px;height:38px;border-radius:50%;background:rgba(15,15,20,.85);border:1px solid rgba(255,255,255,.12);color:#a78bfa;font-size:16px;cursor:pointer;display:none;align-items:center;justify-content:center;backdrop-filter:blur(8px);z-index:9999;transition:transform .15s;}
.qp-stt.visible{display:flex;}
.qp-stt:hover{transform:translateY(-3px);}
/* Hint chip \u2318K */
.qp-hint{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);background:rgba(15,15,20,.92);color:#9CA3AF;border:1px solid rgba(255,255,255,.08);padding:5px 12px;border-radius:18px;font-size:11px;letter-spacing:.5px;backdrop-filter:blur(8px);z-index:9998;pointer-events:none;opacity:0;transition:opacity .3s ease;}
.qp-hint.show{opacity:1;}
.qp-hint kbd{background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.12);border-radius:4px;padding:1px 5px;font-family:inherit;margin:0 2px;}
`;let o=0,a=n;const b=e=>{const t=(e||"").toLowerCase().trim();return t?n.filter(i=>i.label.toLowerCase().includes(t)||i.kw.includes(t)):n},s=()=>{const e=document.getElementById("qp-list");if(e){if(!a.length){e.innerHTML='<div class="qp-empty">No encontr\xE9 nada \xB7 prob\xE1 "carrusel", "voz", "brand kit"\u2026</div>';return}e.innerHTML=a.map((t,i)=>`<div class="qp-item ${i===o?"active":""}" data-route="${t.route}">${t.label}</div>`).join(""),e.querySelectorAll(".qp-item").forEach(t=>{t.addEventListener("mouseenter",()=>{o=[...e.children].indexOf(t),e.querySelectorAll(".qp-item").forEach((i,d)=>i.classList.toggle("active",d===o))}),t.addEventListener("click",()=>c(t.dataset.route))})}},c=e=>{l(),window.location.hash="#"+e},f=()=>{if(document.getElementById("qp-overlay"))return;document.body.insertAdjacentHTML("beforeend",u),o=0,a=n,s();const e=document.getElementById("qp-input");e.focus(),e.addEventListener("input",t=>{a=b(t.target.value),o=0,s()}),document.getElementById("qp-overlay").addEventListener("click",t=>{t.target.id==="qp-overlay"&&l()})},l=()=>{document.getElementById("qp-overlay")?.remove()};document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault(),document.getElementById("qp-overlay")?l():f();return}if(document.getElementById("qp-overlay")&&(e.key==="Escape"&&(e.preventDefault(),l()),e.key==="ArrowDown"&&(e.preventDefault(),o=Math.min(a.length-1,o+1),s(),document.querySelectorAll(".qp-item")[o]?.scrollIntoView({block:"nearest"})),e.key==="ArrowUp"&&(e.preventDefault(),o=Math.max(0,o-1),s(),document.querySelectorAll(".qp-item")[o]?.scrollIntoView({block:"nearest"})),e.key==="Enter")){e.preventDefault();const t=a[o];t&&c(t.route)}});export const initQuickPanel=()=>{if(document.getElementById("qp-style"))return;const e=document.createElement("style");e.id="qp-style",e.textContent=m,document.head.appendChild(e);const t=document.createElement("button");t.className="qp-stt",t.setAttribute("aria-label","Subir"),t.innerHTML="\u2191",t.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"})),document.body.appendChild(t);let i=!1;window.addEventListener("scroll",()=>{i||(i=!0,requestAnimationFrame(()=>{t.classList.toggle("visible",window.scrollY>600),i=!1}))},{passive:!0});try{if(!(localStorage.getItem("feedia.qpHintSeen")==="1")){const r=document.createElement("div");r.className="qp-hint";const p=/Mac|iPhone|iPad/.test(navigator.platform);r.innerHTML=`tip \xB7 <kbd>${p?"\u2318":"Ctrl"}</kbd><kbd>K</kbd> para buscar vista al instante`,document.body.appendChild(r),setTimeout(()=>r.classList.add("show"),800),setTimeout(()=>{r.classList.remove("show"),setTimeout(()=>r.remove(),400)},5500),localStorage.setItem("feedia.qpHintSeen","1")}}catch{}};document.readyState==="complete"||document.readyState==="interactive"?setTimeout(initQuickPanel,100):document.addEventListener("DOMContentLoaded",initQuickPanel);
