/**
 * DM Inbox de FeedIA — bandeja de entrada con threading y contexto multi-turn.
 *
 * Reemplaza el inbox que un Community Manager humano gestiona. Mantiene el contexto
 * completo de cada conversación, clasifica por intención, prioriza, y sugiere/auto-genera
 * la próxima respuesta apropiada usando la voz de marca.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { log } from '../../agent/logger.js';
import { askJson as routerAskJson, ask as routerAsk } from '../../agent/tokenRouter.js';
import { loadBrandProfile } from '../../config/index.js';
import type { BrandProfile } from '../../config/types.js';
import { injectIntoDMPrompt } from '../../brain/bridge/brainEnrichment.js';
import { learnFromInteraction } from '../../brain/bridge/interactionLearner.js';

const INBOX_PATH = join(process.cwd(), 'data', 'community', 'dm-inbox.json');

// ── Tipos ─────────────────────────────────────────────────────────────────────

export type ConversationStatus =
  | 'new' // conversación recién abierta, sin respuesta nuestra
  | 'awaiting-reply' // ya respondimos, esperando al usuario
  | 'in-progress' // ida y vuelta activo (<24h del último mensaje)
  | 'stalled' // sin respuesta del usuario en 48h+
  | 'resolved' // cerrada (compra, escalada, sin más interacción)
  | 'escalated' // requiere humano
  | 'archived'; // archivada después de 30 días sin interacción

export type ConversationIntent =
  | 'comercial' // intención de compra
  | 'soporte' // problema con producto/servicio
  | 'feedback' // opinión, sugerencia, queja
  | 'pregunta-general' // duda informativa
  | 'colab' // propuesta de colaboración
  | 'press' // medios, prensa, entrevistas
  | 'spam' // ruido o automático
  | 'amor' // mensaje positivo, fan
  | 'troll' // hostil
  | 'desconocida';

export type ConversationPriority = 'critical' | 'high' | 'normal' | 'low';

export interface ConversationMessage {
  id: string;
  timestamp: string;
  sender: 'them' | 'us';
  text: string;
  media?: { type: 'image' | 'video' | 'audio' | 'story-reply'; url: string }[];
  reactions?: string[];
  isAutoGenerated?: boolean;
}

export interface Conversation {
  id: string;
  threadId: string; // ID del thread de IG
  contact: {
    username: string;
    displayName?: string;
    followerCount?: number;
    isFollower: boolean;
    isFollowing: boolean;
    profileUrl?: string;
  };
  messages: ConversationMessage[];
  intent: ConversationIntent;
  priority: ConversationPriority;
  status: ConversationStatus;
  tags: string[];
  assignedTo: 'lia' | 'luca' | 'gard' | 'talia' | 'human';
  sentiment: number; // -1 a +1
  qualifiedLeadScore?: number; // 0-100 si es prospect
  attachedGoalId?: string;
  notes: string[];
  createdAt: string;
  lastMessageAt: string;
  lastOurMessageAt?: string;
  resolvedAt?: string;
  customerJourney?: 'awareness' | 'consideration' | 'decision' | 'post-purchase';
  context: {
    referredPost?: string; // si vino comentando un post
    productInterest?: string;
    objectionsRaised: string[];
    promisesMade: string[]; // qué prometimos cumplir
  };
}

interface InboxStore {
  version: number;
  conversations: Conversation[];
  lastUpdated: string;
  stats: {
    totalConversations: number;
    avgResponseTimeMinutes: number;
    resolvedLast30Days: number;
    escalatedLast30Days: number;
  };
}

const DEFAULT_STORE: InboxStore = {
  version: 1,
  conversations: [],
  lastUpdated: new Date().toISOString(),
  stats: {
    totalConversations: 0,
    avgResponseTimeMinutes: 0,
    resolvedLast30Days: 0,
    escalatedLast30Days: 0,
  },
};

// ── Persistencia ──────────────────────────────────────────────────────────────

const ensureDir = (): void => {
  const dir = join(process.cwd(), 'data', 'community');
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
};

const loadInbox = (): InboxStore => {
  try {
    ensureDir();
    if (!existsSync(INBOX_PATH)) return structuredClone(DEFAULT_STORE);
    return JSON.parse(readFileSync(INBOX_PATH, 'utf8')) as InboxStore;
  } catch {
    return structuredClone(DEFAULT_STORE);
  }
};

const saveInbox = (store: InboxStore): void => {
  ensureDir();
  store.lastUpdated = new Date().toISOString();
  writeFileSync(INBOX_PATH, JSON.stringify(store, null, 2), 'utf8');
};

// ── Heurísticas de clasificación ──────────────────────────────────────────────

const INTENT_PATTERNS: Record<ConversationIntent, RegExp[]> = {
  comercial: [
    /\bprecio\b/i,
    /\bcost(o|a)\b/i,
    /\bcompr(o|ar)\b/i,
    /\bquiero\b/i,
    /\binteres\b/i,
    /\binformaci/i,
    /\bcuant/i,
    /\bdisponib/i,
    /\bpago/i,
    /\benvi/i,
  ],
  soporte: [
    /\bno (funciona|anda|me llega)\b/i,
    /\bproblem/i,
    /\bayud/i,
    /\berror/i,
    /\bdevoluci/i,
    /\breembols/i,
    /\breclam/i,
    /\bgaranti/i,
  ],
  feedback: [/\bsugerenc/i, /\bopini/i, /\brecomend/i, /\bser[ií]a bueno\b/i, /\bme gustar[ií]a\b/i, /\bporque no\b/i],
  'pregunta-general': [/\b(c[oó]mo|qu[eé]|qui[eé]n|d[oó]nde|cu[aá]ndo|por qu[eé])\b/i, /\?$/],
  colab: [/\bcolab/i, /\bpartnership\b/i, /\bsponsor/i, /\bunir(me|nos)\b/i, /\btrabajar (juntos|contigo)\b/i],
  press: [/\bentrevist/i, /\bmedio\b/i, /\bperiodist/i, /\bprensa\b/i, /\bnota\b/i],
  spam: [/💰💰💰/, /click here/i, /telegram\.me/i, /bit\.ly/i, /follow me/i, /seguime y te sigo/i],
  amor: [/te (amo|adoro)/i, /sos lo m[aá]s\b/i, /me encant/i, /\bgracias\b/i, /\bidol\b/i, /\bcrack\b/i],
  troll: [/\bestaf(a|ador)\b/i, /\bfraude\b/i, /\basqu/i, /\bbasur/i, /\bmenti(ra|roso)\b/i],
  desconocida: [],
};

const classifyIntent = (text: string): ConversationIntent => {
  const cleanText = text.toLowerCase().trim();
  for (const [intent, patterns] of Object.entries(INTENT_PATTERNS)) {
    if (patterns.some((p) => p.test(cleanText))) return intent as ConversationIntent;
  }
  return 'desconocida';
};

const computePriority = (
  intent: ConversationIntent,
  contact: Conversation['contact'],
  messageCount: number,
): ConversationPriority => {
  if (intent === 'troll' || intent === 'soporte') return 'critical';
  if (intent === 'comercial' && messageCount <= 2) return 'high';
  if (intent === 'press' || intent === 'colab') return 'high';
  if ((contact.followerCount ?? 0) > 10000) return 'high'; // influencer/figura
  if (intent === 'spam') return 'low';
  if (intent === 'amor' || intent === 'feedback') return 'normal';
  return 'normal';
};

const computeSentiment = (text: string): number => {
  const positives = [
    'gracias',
    'genial',
    'excelente',
    'amor',
    'crack',
    'lindo',
    'gracias',
    'sí',
    'perfecto',
    'increíble',
    'top',
  ];
  const negatives = [
    'malo',
    'pésimo',
    'horrible',
    'estafa',
    'mentira',
    'asco',
    'basura',
    'no me llega',
    'no funciona',
    'devolución',
  ];
  const lower = text.toLowerCase();
  let score = 0;
  positives.forEach((w) => {
    if (lower.includes(w)) score += 0.2;
  });
  negatives.forEach((w) => {
    if (lower.includes(w)) score -= 0.3;
  });
  return Math.max(-1, Math.min(1, score));
};

const assignTo = (intent: ConversationIntent, priority: ConversationPriority): Conversation['assignedTo'] => {
  if (priority === 'critical' && intent === 'soporte') return 'gard';
  if (intent === 'comercial') return 'luca';
  if (intent === 'colab' || intent === 'press') return 'talia';
  if (intent === 'troll' || intent === 'spam') return 'gard';
  return 'lia';
};

// ── CRUD de conversaciones ────────────────────────────────────────────────────

export interface IncomingMessage {
  threadId: string;
  contactUsername: string;
  contactDisplayName?: string;
  contactFollowerCount?: number;
  contactIsFollower?: boolean;
  contactIsFollowing?: boolean;
  text: string;
  media?: ConversationMessage['media'];
  referredPostId?: string;
  isStoryReply?: boolean;
  timestamp?: string;
}

export const ingestMessage = (incoming: IncomingMessage): Conversation => {
  const store = loadInbox();
  let conv = store.conversations.find((c) => c.threadId === incoming.threadId);

  const messageEntry: ConversationMessage = {
    id: `msg-${Date.now()}-${Math.floor(Math.random() * 9999)}`,
    timestamp: incoming.timestamp ?? new Date().toISOString(),
    sender: 'them',
    text: incoming.text,
    media: incoming.media,
  };

  if (!conv) {
    // Conversación nueva
    const intent = classifyIntent(incoming.text);
    const contact = {
      username: incoming.contactUsername,
      displayName: incoming.contactDisplayName,
      followerCount: incoming.contactFollowerCount,
      isFollower: incoming.contactIsFollower ?? false,
      isFollowing: incoming.contactIsFollowing ?? false,
      profileUrl: `https://instagram.com/${incoming.contactUsername}`,
    };
    const priority = computePriority(intent, contact, 1);
    const sentiment = computeSentiment(incoming.text);

    conv = {
      id: `conv-${Date.now()}-${Math.floor(Math.random() * 999)}`,
      threadId: incoming.threadId,
      contact,
      messages: [messageEntry],
      intent,
      priority,
      status: 'new',
      tags: [intent],
      assignedTo: assignTo(intent, priority),
      sentiment,
      notes: [],
      createdAt: messageEntry.timestamp,
      lastMessageAt: messageEntry.timestamp,
      context: {
        referredPost: incoming.referredPostId,
        objectionsRaised: [],
        promisesMade: [],
      },
    };
    store.conversations.push(conv);
    log.info(`[DMInbox] Conversación nueva con @${contact.username}: intent=${intent}, priority=${priority}`);
  } else {
    // Mensaje en conversación existente
    conv.messages.push(messageEntry);
    conv.lastMessageAt = messageEntry.timestamp;
    if (conv.status === 'resolved' || conv.status === 'archived' || conv.status === 'stalled') {
      conv.status = 'in-progress';
    }
    // Reclasificar intent si la conversación tomó otro rumbo (por keywords nuevas)
    const newIntent = classifyIntent(incoming.text);
    if (newIntent !== 'desconocida' && newIntent !== conv.intent) {
      conv.intent = newIntent;
      conv.priority = computePriority(newIntent, conv.contact, conv.messages.length);
      conv.assignedTo = assignTo(newIntent, conv.priority);
      conv.tags.push(newIntent);
    }
    // Actualizar sentiment como promedio rolling
    const newSent = computeSentiment(incoming.text);
    conv.sentiment = (conv.sentiment + newSent) / 2;
  }

  // Mantener últimas 500 conversaciones
  if (store.conversations.length > 500) store.conversations = store.conversations.slice(-500);
  store.stats.totalConversations = store.conversations.length;
  saveInbox(store);
  return conv;
};

export const appendOurReply = (
  conversationId: string,
  text: string,
  options: { isAutoGenerated?: boolean; note?: string } = {},
): Conversation | null => {
  const store = loadInbox();
  const conv = store.conversations.find((c) => c.id === conversationId);
  if (!conv) return null;

  const msg: ConversationMessage = {
    id: `msg-${Date.now()}-${Math.floor(Math.random() * 9999)}`,
    timestamp: new Date().toISOString(),
    sender: 'us',
    text,
    isAutoGenerated: options.isAutoGenerated ?? false,
  };
  conv.messages.push(msg);
  conv.lastOurMessageAt = msg.timestamp;
  if (conv.status === 'new') conv.status = 'awaiting-reply';
  if (options.note) conv.notes.push(`[${msg.timestamp}] ${options.note}`);

  saveInbox(store);
  return conv;
};

// ── Generación de respuesta con contexto completo ───────────────────────────

export interface SuggestReplyOptions {
  brand?: BrandProfile;
  customInstructions?: string;
  maxLength?: number;
  autoSend?: boolean; // si true, agrega la respuesta como nuestra
}

export interface SuggestedReply {
  text: string;
  intent: ConversationIntent;
  rationale: string;
  followUpQuestion?: string;
  confidence: number; // 0-1
  shouldEscalate: boolean;
  suggestedActions: string[]; // ej: 'follow-up-en-3-dias', 'agregar-a-pipeline'
}

export const suggestReply = async (
  conversationId: string,
  options: SuggestReplyOptions = {},
): Promise<SuggestedReply | null> => {
  const store = loadInbox();
  const conv = store.conversations.find((c) => c.id === conversationId);
  if (!conv) return null;

  const brand = options.brand ?? loadBrandProfile();
  const lastTwentyMessages = conv.messages.slice(-20);
  const conversationLog = lastTwentyMessages
    .map((m) => `${m.sender === 'us' ? 'NOSOTROS' : `@${conv.contact.username}`}: ${m.text}`)
    .join('\n');

  const promesas =
    conv.context.promisesMade.length > 0
      ? `\n\nPROMESAS QUE LE HICIMOS QUE TENEMOS QUE CUMPLIR:\n${conv.context.promisesMade.map((p) => `- ${p}`).join('\n')}`
      : '';

  const objeciones =
    conv.context.objectionsRaised.length > 0
      ? `\n\nOBJECIONES PLANTEADAS:\n${conv.context.objectionsRaised.map((o) => `- ${o}`).join('\n')}`
      : '';

  let prompt = `Sos el Community Manager senior de @${brand.name}. Generá la próxima respuesta de DM con criterio profesional.

PERFIL DE LA MARCA:
- Nombre: ${brand.name}
- Nicho: ${brand.niche}
- Tono de voz: ${brand.voice.tone.join(', ')}
- Palabras prohibidas: ${brand.voice.forbidden.join(', ') || '(ninguna)'}
- Audiencia: ${brand.audience.description}

CONTEXTO DE LA CONVERSACIÓN:
- Contacto: @${conv.contact.username}${conv.contact.followerCount ? ` (${conv.contact.followerCount} seguidores)` : ''}
- Es seguidor nuestro: ${conv.contact.isFollower ? 'sí' : 'no'}
- Intent detectado: ${conv.intent}
- Sentiment promedio: ${conv.sentiment.toFixed(2)}
- Customer journey: ${conv.customerJourney ?? 'desconocido'}
- Status actual: ${conv.status}${promesas}${objeciones}

CONVERSACIÓN COMPLETA:
${conversationLog}

${options.customInstructions ? `INSTRUCCIONES ESPECIALES:\n${options.customInstructions}\n` : ''}

Reglas:
- Hablá como un CM senior, no robótico
- Sé útil, NO vendedor agresivo
- Si es comercial y ya respondiste lo básico, llevá a una llamada/agendar / link en bio
- Si es soporte crítico, mostrá empatía y resolvé
- Si es troll, mantenete profesional, no muerdas el anzuelo
- Si es spam, sugerí no responder
- Si la respuesta requiere a un humano (legal, ventas complejas, escalada), sugerí escalar
- Máximo ${options.maxLength ?? 280} caracteres
- Cerrá con pregunta abierta SI corresponde para mantener viva la conversación

JSON:
{
  "text": "el mensaje completo a enviar",
  "intent": "${conv.intent}",
  "rationale": "1 línea explicando la lógica de esta respuesta",
  "followUpQuestion": "(opcional) pregunta de seguimiento",
  "confidence": 0.0-1.0,
  "shouldEscalate": boolean,
  "suggestedActions": ["acción 1", "acción 2"]
}`;

  // 🧠 Inject brain context
  prompt = await injectIntoDMPrompt(brand, conv.contact.username, prompt);

  let suggestion: SuggestedReply;
  try {
    suggestion = await routerAskJson<SuggestedReply>(prompt, {
      taskType: 'response',
      maxTokens: 1200,
      systemPrompt: 'Sos un CM senior. Tus respuestas son específicas, humanas y orientadas a la situación.',
    });
  } catch (err) {
    log.warn(`[DMInbox] askJson falló, usando ask: ${(err as Error).message}`);
    const fallback = await routerAsk(prompt, { taskType: 'response', maxTokens: 600 });
    suggestion = {
      text: fallback.text.trim().slice(0, options.maxLength ?? 280),
      intent: conv.intent,
      rationale: 'Generated via fallback',
      confidence: 0.5,
      shouldEscalate: false,
      suggestedActions: [],
    };
  }

  // ✅ APRENDER — el cerebro guarda CADA interacción DM
  await learnFromInteraction({
    handle: conv.contact.username,
    incoming: conv.messages[conv.messages.length - 1]?.text ?? '',
    outgoing: suggestion.text,
    channel: 'dm',
    intent: conv.intent,
    confidence: suggestion.confidence,
    brand,
    metadata: {
      autoReplied: options.autoSend ?? false,
      escalated: suggestion.shouldEscalate,
      sentiment: conv.sentiment > 0.3 ? 'positive' : conv.sentiment < -0.3 ? 'negative' : 'neutral',
    },
  });

  // Auto-send opcional
  if (options.autoSend && !suggestion.shouldEscalate) {
    appendOurReply(conversationId, suggestion.text, {
      isAutoGenerated: true,
      note: `Auto-respuesta. Rationale: ${suggestion.rationale}`,
    });
  }

  // Si hay que escalar, marcar la conversación
  if (suggestion.shouldEscalate) {
    conv.status = 'escalated';
    conv.assignedTo = 'human';
    conv.notes.push(`[${new Date().toISOString()}] Escalado por sugerencia AI: ${suggestion.rationale}`);
    saveInbox(store);
  }

  return suggestion;
};

// ── Procesamiento batch del inbox ─────────────────────────────────────────────

export interface InboxTickResult {
  processed: number;
  autoReplied: number;
  escalated: number;
  pendingHuman: number;
}

export const tickInbox = async (maxProcess = 15): Promise<InboxTickResult> => {
  const store = loadInbox();
  const now = Date.now();

  // Detectar conversaciones que pasaron a 'stalled'
  for (const conv of store.conversations) {
    if (conv.status === 'awaiting-reply' || conv.status === 'in-progress') {
      const lastMsgTime = new Date(conv.lastMessageAt).getTime();
      const hoursAgo = (now - lastMsgTime) / (60 * 60 * 1000);
      if (hoursAgo > 48) {
        conv.status = 'stalled';
      }
    }
    // Auto-archive después de 30 días sin actividad
    const sinceLast = (now - new Date(conv.lastMessageAt).getTime()) / (24 * 60 * 60 * 1000);
    if (sinceLast > 30 && conv.status !== 'escalated') {
      conv.status = 'archived';
    }
  }

  // Tomar las conversaciones 'new' y 'awaiting-reply' con prioridad
  const pending = store.conversations
    .filter((c) => c.status === 'new' && c.intent !== 'spam' && c.intent !== 'troll' && c.assignedTo !== 'human')
    .sort((a, b) => {
      const order: Record<ConversationPriority, number> = { critical: 0, high: 1, normal: 2, low: 3 };
      return order[a.priority] - order[b.priority];
    })
    .slice(0, maxProcess);

  let autoReplied = 0;
  let escalated = 0;

  for (const conv of pending) {
    try {
      const suggestion = await suggestReply(conv.id, { autoSend: !conv.contact.isFollower ? false : true });
      if (!suggestion) continue;
      if (suggestion.shouldEscalate) escalated++;
      else if (suggestion.confidence >= 0.7) autoReplied++;
    } catch (err) {
      log.warn(`[DMInbox] Error procesando conv ${conv.id}: ${(err as Error).message}`);
    }
  }

  saveInbox(store);

  const pendingHuman = store.conversations.filter((c) => c.status === 'escalated' || c.assignedTo === 'human').length;
  log.info(
    `[DMInbox] Tick: ${pending.length} procesadas, ${autoReplied} auto, ${escalated} escaladas, ${pendingHuman} esperan humano`,
  );
  return { processed: pending.length, autoReplied, escalated, pendingHuman };
};

// ── Vistas y consultas ───────────────────────────────────────────────────────

export const listConversations = (
  filters: {
    status?: ConversationStatus;
    intent?: ConversationIntent;
    priority?: ConversationPriority;
    assignedTo?: Conversation['assignedTo'];
    contactUsername?: string;
  } = {},
): Conversation[] => {
  let convs = loadInbox().conversations;
  if (filters.status) convs = convs.filter((c) => c.status === filters.status);
  if (filters.intent) convs = convs.filter((c) => c.intent === filters.intent);
  if (filters.priority) convs = convs.filter((c) => c.priority === filters.priority);
  if (filters.assignedTo) convs = convs.filter((c) => c.assignedTo === filters.assignedTo);
  if (filters.contactUsername) convs = convs.filter((c) => c.contact.username === filters.contactUsername);
  return convs.sort((a, b) => b.lastMessageAt.localeCompare(a.lastMessageAt));
};

export const getConversation = (conversationId: string): Conversation | null =>
  loadInbox().conversations.find((c) => c.id === conversationId) ?? null;

export const getInboxSnapshot = (): {
  totalActive: number;
  byStatus: Record<ConversationStatus, number>;
  byIntent: Record<string, number>;
  byPriority: Record<ConversationPriority, number>;
  needingResponse: number;
  escalatedToHuman: number;
  avgSentiment: number;
} => {
  const all = loadInbox().conversations;
  const byStatus: Record<string, number> = {};
  const byIntent: Record<string, number> = {};
  const byPriority: Record<string, number> = {};

  for (const c of all) {
    byStatus[c.status] = (byStatus[c.status] ?? 0) + 1;
    byIntent[c.intent] = (byIntent[c.intent] ?? 0) + 1;
    byPriority[c.priority] = (byPriority[c.priority] ?? 0) + 1;
  }

  const needingResponse = all.filter((c) => c.status === 'new' || c.status === 'in-progress').length;
  const escalated = all.filter((c) => c.status === 'escalated').length;
  const totalActive = all.filter((c) => c.status !== 'archived' && c.status !== 'resolved').length;
  const avgSentiment = all.length > 0 ? all.reduce((s, c) => s + c.sentiment, 0) / all.length : 0;

  return {
    totalActive,
    byStatus: byStatus as Record<ConversationStatus, number>,
    byIntent,
    byPriority: byPriority as Record<ConversationPriority, number>,
    needingResponse,
    escalatedToHuman: escalated,
    avgSentiment,
  };
};

// ── Mutaciones específicas ───────────────────────────────────────────────────

export const updateConversationStatus = (
  conversationId: string,
  status: ConversationStatus,
  note?: string,
): Conversation | null => {
  const store = loadInbox();
  const conv = store.conversations.find((c) => c.id === conversationId);
  if (!conv) return null;
  conv.status = status;
  if (status === 'resolved' && !conv.resolvedAt) conv.resolvedAt = new Date().toISOString();
  if (note) conv.notes.push(`[${new Date().toISOString()}] ${note}`);
  saveInbox(store);
  return conv;
};

export const addPromise = (conversationId: string, promise: string): Conversation | null => {
  const store = loadInbox();
  const conv = store.conversations.find((c) => c.id === conversationId);
  if (!conv) return null;
  conv.context.promisesMade.push(promise);
  saveInbox(store);
  return conv;
};

export const addObjection = (conversationId: string, objection: string): Conversation | null => {
  const store = loadInbox();
  const conv = store.conversations.find((c) => c.id === conversationId);
  if (!conv) return null;
  conv.context.objectionsRaised.push(objection);
  saveInbox(store);
  return conv;
};

export const escalateToHuman = (conversationId: string, reason: string): Conversation | null => {
  const store = loadInbox();
  const conv = store.conversations.find((c) => c.id === conversationId);
  if (!conv) return null;
  conv.status = 'escalated';
  conv.assignedTo = 'human';
  conv.notes.push(`[${new Date().toISOString()}] Escalado: ${reason}`);
  saveInbox(store);
  return conv;
};

export const exportInbox = (): InboxStore => loadInbox();
