/**
 * Caption Generator — generación multi-propósito de captions y subtítulos para Instagram.
 *
 * Módulos:
 *  • generateCaption          — caption completo con hook/body/cta/hashtags via Claude
 *  • generateCaptionVariants  — 5 variantes para A/B testing
 *  • generateSubtitles        — subtítulos con time-code (puro, sin API)
 *  • subtitleTrackToSRT       — exporta SubtitleTrack a formato SRT
 *  • subtitleTrackToVTT       — exporta SubtitleTrack a WebVTT
 *  • generateAltText          — alt-text accesible para imágenes/carruseles
 *  • optimizeCaptionForAlgorithm — post-proceso determinista para el algoritmo de IG
 */

import Anthropic from '@anthropic-ai/sdk';
import { log } from '../../agent/logger.js';
import type { BrandProfile } from '../../config/types.js';

// ── Cliente Anthropic ─────────────────────────────────────────────────────────

const client = new Anthropic();

// SDK v0.32 no tipa aún `claude-opus-4-7` ni `adaptive thinking` como literales;
// casteamos sólo en el sitio exacto de `messages.create`.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const clientAny = client as any;

// ── Tipos públicos ────────────────────────────────────────────────────────────

export interface CaptionLine {
  startMs: number;
  endMs: number;
  text: string;
  speaker?: string;
}

export interface SubtitleTrack {
  lines: CaptionLine[];
  format: 'srt' | 'vtt' | 'json';
  language: string;
  autoGenerated: boolean;
}

export interface InstagramCaption {
  main: string;
  hook: string;
  body: string;
  cta: string;
  hashtags: string[];
  emojis: string[];
  characterCount: number;
  readingTimeSeconds: number;
  accessibility: {
    altText: string;
    transcriptHint: string;
  };
}

export interface CaptionVariants {
  primary: InstagramCaption;
  casual: InstagramCaption;
  formal: InstagramCaption;
  short: InstagramCaption;
  engagement: InstagramCaption;
}

// ── Helpers internos ──────────────────────────────────────────────────────────

const WORDS_PER_MINUTE = 150;

const readingTimeSeconds = (text: string): number => {
  const wordCount = text.trim().split(/\s+/).length;
  return Math.ceil(wordCount / (WORDS_PER_MINUTE / 60));
};

const extractEmojis = (text: string): string[] => {
  const matches = text.match(
    /[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F700}-\u{1F77F}\u{1F780}-\u{1F7FF}\u{1F800}-\u{1F8FF}\u{1F900}-\u{1F9FF}\u{1FA00}-\u{1FA6F}\u{1FA70}-\u{1FAFF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu,
  );
  return matches ?? [];
};

const buildCaptionFromText = (raw: string): InstagramCaption => {
  const lines = raw.trim().split('\n').filter(Boolean);
  const hook = lines[0]?.slice(0, 125) ?? '';
  const hashtagLine = [...lines].reverse().find((l: string) => l.startsWith('#')) ?? '';
  const hashtags = hashtagLine.match(/#\w+/g) ?? [];
  const bodyLines = lines.filter((l) => l !== hashtagLine && l !== lines[0]);
  const cta = bodyLines.at(-1) ?? '';
  const body = bodyLines.slice(0, -1).join('\n');
  const main = raw.slice(0, 2200);
  const emojis = extractEmojis(main);

  return {
    main,
    hook,
    body,
    cta,
    hashtags,
    emojis,
    characterCount: main.length,
    readingTimeSeconds: readingTimeSeconds(main),
    accessibility: {
      altText: '',
      transcriptHint: '',
    },
  };
};

const parseCaptionJson = (raw: string, fallbackRaw?: string): InstagramCaption => {
  const cleaned = raw
    .replace(/^```json\s*/i, '')
    .replace(/^```\s*/i, '')
    .replace(/```\s*$/i, '')
    .trim();
  try {
    const parsed = JSON.parse(cleaned) as Partial<InstagramCaption>;
    const main = (parsed.main ?? '').slice(0, 2200);
    return {
      main,
      hook: parsed.hook ?? main.slice(0, 125),
      body: parsed.body ?? '',
      cta: parsed.cta ?? '',
      hashtags: parsed.hashtags ?? [],
      emojis: parsed.emojis ?? extractEmojis(main),
      characterCount: main.length,
      readingTimeSeconds: readingTimeSeconds(main),
      accessibility: {
        altText: parsed.accessibility?.altText ?? '',
        transcriptHint: parsed.accessibility?.transcriptHint ?? '',
      },
    };
  } catch {
    return buildCaptionFromText(fallbackRaw ?? cleaned);
  }
};

// ── 1. generateCaption ────────────────────────────────────────────────────────

export interface GenerateCaptionParams {
  topic: string;
  format: 'reel' | 'carrusel' | 'post-imagen' | 'historia';
  hook: string;
  body: string;
  cta?: string;
  brand: BrandProfile;
}

export const generateCaption = async (params: GenerateCaptionParams): Promise<InstagramCaption> => {
  const { topic, format, hook, body, cta, brand } = params;
  const locale = brand.audience.locale ?? 'es-AR';
  const tones = brand.voice.tone.join(', ');
  const forbidden = brand.voice.forbidden.length ? brand.voice.forbidden.join(', ') : 'ninguna';
  const hashtagHints =
    Object.values(brand.hashtagPools ?? {})
      .flat()
      .slice(0, 15)
      .join(' ') || '#instagram';

  const systemPrompt = `Sos un experto copywriter de Instagram especializado en marcas argentinas.
Escribís en español rioplatense (${locale}) con tono: ${tones}.
Palabras/frases PROHIBIDAS: ${forbidden}.
Siempre estructurás: hook impactante → desarrollo → CTA → hashtags.
El hook debe provocar una emoción fuerte (pregunta disruptiva, dato sorprendente o número concreto).
Respondés SIEMPRE con JSON válido, sin markdown adicional.`;

  const userPrompt = `Generá un caption para Instagram.

Marca: ${brand.name} (${brand.niche})
Formato: ${format}
Tema: ${topic}
Hook sugerido: ${hook}
Desarrollo: ${body}
${cta ? `CTA sugerido: ${cta}` : ''}
Hashtags disponibles: ${hashtagHints}

Reglas:
- Hook < 125 caracteres (lo que ve el usuario antes de "más")
- Total ≤ 2200 caracteres
- Entre 5 y 15 hashtags relevantes
- Emojis estratégicos (no más de 8)
- Sin links (Instagram no los vuelve clicables)
- Salto de línea después del hook

Respondé SOLO con este JSON (sin markdown):
{
  "main": "texto completo del caption",
  "hook": "primeros 125 chars",
  "body": "desarrollo principal",
  "cta": "llamado a la acción",
  "hashtags": ["#tag1", "#tag2"],
  "emojis": ["emoji1", "emoji2"],
  "accessibility": {
    "altText": "descripción accesible de la visual",
    "transcriptHint": "pista de transcripción para reel"
  }
}`;

  log.info(`[CaptionGenerator] Generando caption para "${topic}" (${format})`);

  try {
    const response = await clientAny.messages.create({
      model: 'claude-opus-4-7',
      max_tokens: 16000,
      thinking: { type: 'adaptive', budget_tokens: 8000 },
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
    });

    const textBlock = (response.content as Array<{ type: string; text?: string }>).find((b) => b.type === 'text');
    const raw = textBlock?.text ?? '';
    const caption = parseCaptionJson(raw, raw);
    log.success(`[CaptionGenerator] Caption generado (${caption.characterCount} chars)`);
    return caption;
  } catch (err) {
    log.error(`[CaptionGenerator] Error generando caption: ${(err as Error).message}`);
    return buildCaptionFromText(`${hook}\n\n${body}\n\n${cta ?? ''}\n\n${hashtagHints}`);
  }
};

// ── 2. generateCaptionVariants ────────────────────────────────────────────────

export interface GenerateCaptionVariantsParams {
  topic: string;
  format: string;
  brand: BrandProfile;
  baseCaption?: string;
}

const VARIANT_TONES: Record<keyof CaptionVariants, string> = {
  primary: 'equilibrado y auténtico, refleja exactamente el tono de marca',
  casual: 'muy conversacional, como un mensaje de WhatsApp a un amigo',
  formal: 'profesional y autorizado, sin perder cercanía',
  short: 'ultra-conciso, máximo 150 caracteres totales incluyendo hashtags',
  engagement: 'diseñado para generar comentarios: hace una pregunta provocadora al final',
};

export const generateCaptionVariants = async (params: GenerateCaptionVariantsParams): Promise<CaptionVariants> => {
  const { topic, format, brand, baseCaption } = params;
  const locale = brand.audience.locale ?? 'es-AR';
  const tones = brand.voice.tone.join(', ');
  const forbidden = brand.voice.forbidden.length ? brand.voice.forbidden.join(', ') : 'ninguna';

  const systemPrompt = `Sos un experto en copywriting de Instagram para marcas de ${locale}.
Tono de marca base: ${tones}. Palabras prohibidas: ${forbidden}.
Generás 5 variantes de caption para A/B testing.
Respondés SIEMPRE con JSON válido y sin markdown.`;

  const userPrompt = `Generá 5 variantes de caption para Instagram sobre este tema:
Marca: ${brand.name} | Tema: ${topic} | Formato: ${format}
${baseCaption ? `Caption base (podés usarlo como referencia): ${baseCaption}` : ''}

Variantes necesarias:
${Object.entries(VARIANT_TONES)
  .map(([key, tone]) => `- ${key}: ${tone}`)
  .join('\n')}

Reglas para todas:
- Rioplatense (${locale})
- Hook < 125 chars
- Total ≤ 2200 chars (excepto "short" que es ≤ 150)
- Sin links
- Hashtags al final

Respondé SOLO con este JSON:
{
  "primary": { "main":"","hook":"","body":"","cta":"","hashtags":[],"emojis":[],"accessibility":{"altText":"","transcriptHint":""}},
  "casual":  { "main":"","hook":"","body":"","cta":"","hashtags":[],"emojis":[],"accessibility":{"altText":"","transcriptHint":""}},
  "formal":  { "main":"","hook":"","body":"","cta":"","hashtags":[],"emojis":[],"accessibility":{"altText":"","transcriptHint":""}},
  "short":   { "main":"","hook":"","body":"","cta":"","hashtags":[],"emojis":[],"accessibility":{"altText":"","transcriptHint":""}},
  "engagement":{ "main":"","hook":"","body":"","cta":"","hashtags":[],"emojis":[],"accessibility":{"altText":"","transcriptHint":""}}
}`;

  log.info(`[CaptionGenerator] Generando 5 variantes para "${topic}"`);

  const buildFallbackVariant = (tone: string): InstagramCaption =>
    buildCaptionFromText(`[Variante ${tone}] ${topic} — ${brand.name}\n#${brand.niche.replace(/\s+/g, '')}`);

  try {
    const response = await clientAny.messages.create({
      model: 'claude-opus-4-7',
      max_tokens: 32000,
      thinking: { type: 'adaptive', budget_tokens: 10000 },
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
    });

    const textBlock = (response.content as Array<{ type: string; text?: string }>).find((b) => b.type === 'text');
    const raw = (textBlock?.text ?? '')
      .replace(/^```json\s*/i, '')
      .replace(/```\s*$/i, '')
      .trim();

    const parsed = JSON.parse(raw) as Record<string, Partial<InstagramCaption>>;
    const hydrate = (v: Partial<InstagramCaption>): InstagramCaption => {
      const main = (v.main ?? '').slice(0, 2200);
      return {
        main,
        hook: v.hook ?? main.slice(0, 125),
        body: v.body ?? '',
        cta: v.cta ?? '',
        hashtags: v.hashtags ?? [],
        emojis: v.emojis ?? extractEmojis(main),
        characterCount: main.length,
        readingTimeSeconds: readingTimeSeconds(main),
        accessibility: {
          altText: v.accessibility?.altText ?? '',
          transcriptHint: v.accessibility?.transcriptHint ?? '',
        },
      };
    };

    log.success('[CaptionGenerator] 5 variantes generadas');
    return {
      primary: hydrate(parsed['primary'] ?? {}),
      casual: hydrate(parsed['casual'] ?? {}),
      formal: hydrate(parsed['formal'] ?? {}),
      short: hydrate(parsed['short'] ?? {}),
      engagement: hydrate(parsed['engagement'] ?? {}),
    };
  } catch (err) {
    log.error(`[CaptionGenerator] Error generando variantes: ${(err as Error).message}`);
    return {
      primary: buildFallbackVariant('primary'),
      casual: buildFallbackVariant('casual'),
      formal: buildFallbackVariant('formal'),
      short: buildFallbackVariant('short'),
      engagement: buildFallbackVariant('engagement'),
    };
  }
};

// ── 3. generateSubtitles ──────────────────────────────────────────────────────

export interface GenerateSubtitlesParams {
  transcript: string;
  durationMs: number;
  language?: string;
  wordsPerMinute?: number;
}

const splitIntoPhrases = (text: string, wordsPerPhrase: number): string[] => {
  const words = text.trim().split(/\s+/);
  const phrases: string[] = [];
  for (let i = 0; i < words.length; i += wordsPerPhrase) {
    phrases.push(words.slice(i, i + wordsPerPhrase).join(' '));
  }
  return phrases;
};

export const generateSubtitles = (params: GenerateSubtitlesParams): SubtitleTrack => {
  const { transcript, durationMs, language = 'es', wordsPerMinute = 150 } = params;

  const wordsPerMs = wordsPerMinute / (60 * 1000);
  const phrases = splitIntoPhrases(transcript, 6); // 5-8 words target, use 6

  const totalWords = transcript.trim().split(/\s+/).length;
  const msPerWord = totalWords > 0 ? durationMs / totalWords : 500;

  let cursor = 0;
  const lines: CaptionLine[] = phrases.map((phrase, _idx) => {
    const wordCount = phrase.split(/\s+/).length;
    const phraseDurationMs = Math.round(wordCount / wordsPerMs);
    const startMs = cursor;
    const endMs = Math.min(cursor + phraseDurationMs, durationMs);
    cursor = endMs;
    return { startMs, endMs, text: phrase };
  });

  // Adjust last line to exactly match durationMs
  if (lines.length > 0) {
    const last = lines[lines.length - 1];
    if (last) {
      lines[lines.length - 1] = { ...last, endMs: durationMs };
    }
  }

  // Suppress unused variable warning — msPerWord used above
  void msPerWord;

  return {
    lines,
    format: 'srt',
    language,
    autoGenerated: true,
  };
};

// ── 4. subtitleTrackToSRT ─────────────────────────────────────────────────────

const msToSRTTime = (ms: number): string => {
  const totalSeconds = Math.floor(ms / 1000);
  const milliseconds = ms % 1000;
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  return (
    [String(hours).padStart(2, '0'), String(minutes).padStart(2, '0'), String(seconds).padStart(2, '00')].join(':') +
    `,${String(milliseconds).padStart(3, '0')}`
  );
};

export const subtitleTrackToSRT = (track: SubtitleTrack): string =>
  track.lines
    .map((line, idx) => `${idx + 1}\n${msToSRTTime(line.startMs)} --> ${msToSRTTime(line.endMs)}\n${line.text}\n`)
    .join('\n');

// ── 5. subtitleTrackToVTT ─────────────────────────────────────────────────────

const msToVTTTime = (ms: number): string => {
  const totalSeconds = Math.floor(ms / 1000);
  const milliseconds = ms % 1000;
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  return (
    [String(hours).padStart(2, '0'), String(minutes).padStart(2, '00'), String(seconds).padStart(2, '00')].join(':') +
    `.${String(milliseconds).padStart(3, '0')}`
  );
};

export const subtitleTrackToVTT = (track: SubtitleTrack): string => {
  const header = `WEBVTT\n\n`;
  const body = track.lines
    .map((line, idx) => `${idx + 1}\n${msToVTTTime(line.startMs)} --> ${msToVTTTime(line.endMs)}\n${line.text}\n`)
    .join('\n');
  return header + body;
};

// ── 6. generateAltText ────────────────────────────────────────────────────────

export interface GenerateAltTextParams {
  visualDescription: string;
  brand: BrandProfile;
  context: string;
}

export const generateAltText = async (params: GenerateAltTextParams): Promise<string> => {
  const { visualDescription, brand, context } = params;

  const systemPrompt = `Sos un especialista en accesibilidad digital para redes sociales.
Escribís alt-text descriptivo, conciso y alineado con la marca.
Máximo 300 caracteres. Sin hashtags. Sin emojis. Idioma: ${brand.audience.locale ?? 'es-AR'}.`;

  const userPrompt = `Generá el alt-text para esta imagen de Instagram.

Marca: ${brand.name} (${brand.niche})
Contexto del post: ${context}
Descripción visual: ${visualDescription}

Reglas:
- Máximo 300 caracteres
- Describí lo más importante primero
- Mencioná la marca si aparece visualmente
- Tono: ${brand.voice.tone.slice(0, 2).join(', ')}
- Sin hashtags ni emojis

Respondé SOLO el texto del alt-text, sin comillas ni explicaciones.`;

  log.info('[CaptionGenerator] Generando alt-text accesible');

  try {
    const response = await clientAny.messages.create({
      model: 'claude-opus-4-7',
      max_tokens: 500,
      thinking: { type: 'adaptive', budget_tokens: 2000 },
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
    });

    const textBlock = (response.content as Array<{ type: string; text?: string }>).find((b) => b.type === 'text');
    const altText = (textBlock?.text ?? '').trim().slice(0, 300);
    log.success(`[CaptionGenerator] Alt-text generado (${altText.length} chars)`);
    return altText;
  } catch (err) {
    log.error(`[CaptionGenerator] Error generando alt-text: ${(err as Error).message}`);
    return `Imagen de ${brand.name}: ${visualDescription.slice(0, 250)}`.slice(0, 300);
  }
};

// ── 7. optimizeCaptionForAlgorithm ───────────────────────────────────────────

export const optimizeCaptionForAlgorithm = (caption: InstagramCaption, brand: BrandProfile): InstagramCaption => {
  let { main, hook, body, cta } = caption;
  const { hashtags, emojis } = caption;

  // 1. Ensure hook < 125 chars
  if (hook.length > 125) {
    hook = hook.slice(0, 122) + '...';
  }

  // 2. Remove any links (Instagram ignores them)
  const linkRegex = /https?:\/\/\S+/g;
  main = main.replace(linkRegex, '[link en bio]');
  hook = hook.replace(linkRegex, '[link en bio]');
  body = body.replace(linkRegex, '[link en bio]');
  cta = cta.replace(linkRegex, '[link en bio]');

  // 3. Ensure line break after hook so it's visually separated
  const hookInMain = main.indexOf(hook);
  if (hookInMain !== -1) {
    const afterHook = main.slice(hookInMain + hook.length);
    if (!afterHook.startsWith('\n\n')) {
      main = hook + '\n\n' + afterHook.replace(/^\n+/, '');
    }
  }

  // 4. Move hashtags to end (first-comment style note) — mark them for external handling
  const hashtagBlock = hashtags.join(' ');
  // Strip inline hashtags from body/hook
  const stripInlineHashtags = (text: string): string =>
    text
      .replace(/#\w+/g, '')
      .replace(/\s{2,}/g, ' ')
      .trim();

  if (brand.goals.primary === 'engagement' || brand.goals.primary === 'awareness') {
    // Keep hashtags inline for discovery
    if (!main.includes(hashtagBlock) && hashtagBlock) {
      main = `${stripInlineHashtags(main)}\n\n${hashtagBlock}`.trim();
    }
  } else {
    // Remove from main caption, note they should go to first comment
    main = stripInlineHashtags(main);
    if (!main.includes('[Hashtags → primer comentario]')) {
      main = `${main}\n\n[Hashtags → primer comentario]`.trim();
    }
  }

  // 5. Clamp total to 2200 chars
  if (main.length > 2200) {
    main = main.slice(0, 2197) + '...';
  }

  return {
    ...caption,
    main,
    hook,
    body,
    cta,
    hashtags,
    emojis,
    characterCount: main.length,
    readingTimeSeconds: readingTimeSeconds(main),
  };
};
