/**
 * FeedIA + Computer Use Orchestrator
 * Full integration: Brain → Vision → Browser → Action
 */

import { BrowserAutomationManager } from './BROWSER_AUTOMATION_LAYER';
import {
  generateCarouselWithAgents,
  generateVideoWithAgents,
  generatePhotoWithAgents,
  generateReelWithAgents,
} from '../api/agentIntegrationLayer';
import { analyzeScreenshot, type ScreenshotAnalysis } from './COMPUTER_VISION_LAYER';

interface AutomationBrief {
  task: 'post_carousel' | 'post_reel' | 'post_story' | 'respond_comments' | 'analyze_account';
  platform: 'instagram' | 'tiktok' | 'both';
  topic?: string;
  content?: any;
  targetAudience?: string;
  style?: string;
}

interface AutomationResult {
  success: boolean;
  action: string;
  platform: string;
  output?: any;
  metrics?: any;
  errors?: string[];
}

// ── ORCHESTRATOR ──────────────────────────────────────

class FeedIAComputerUseOrchestrator {
  private browser: BrowserAutomationManager;
  private actionLog: AutomationResult[] = [];

  constructor() {
    this.browser = new BrowserAutomationManager();
  }

  async executeAutomation(brief: AutomationBrief): Promise<AutomationResult> {
    try {
      console.log(`[FeedIA Orchestrator] Starting task: ${brief.task}`);

      // Step 1: Analyze current screen (Computer Vision)
      const screenAnalysis = await analyzeScreenshot();
      console.log(`[FeedIA] Screen analysis confidence: ${screenAnalysis.confidence}`);

      // Step 2: Route to appropriate workflow
      let result: AutomationResult;

      switch (brief.task) {
        case 'post_carousel':
          result = await this.workflowPostCarousel(brief, screenAnalysis);
          break;

        case 'post_reel':
          result = await this.workflowPostReel(brief, screenAnalysis);
          break;

        case 'post_story':
          result = await this.workflowPostStory(brief, screenAnalysis);
          break;

        case 'respond_comments':
          result = await this.workflowRespondComments(brief, screenAnalysis);
          break;

        case 'analyze_account':
          result = await this.workflowAnalyzeAccount(brief, screenAnalysis);
          break;

        default:
          throw new Error(`Unknown task: ${brief.task}`);
      }

      this.actionLog.push(result);
      return result;
    } catch (error) {
      return {
        success: false,
        action: brief.task,
        platform: brief.platform,
        errors: [String(error)],
      };
    }
  }

  // ── WORKFLOW: POST CAROUSEL ──────────────────────

  private async workflowPostCarousel(
    brief: AutomationBrief,
    vision: ScreenshotAnalysis,
  ): Promise<AutomationResult> {
    console.log('[FeedIA] Workflow: Post Carousel');

    // Step 1: FeedIA Brain generates carousel content
    const carouselContent = await generateCarouselWithAgents({
      topic: brief.topic || 'general',
      emotion: brief.style || 'aspirational',
      audience: brief.targetAudience || 'professional',
      targetSlideCount: 5,
    }) as any;

    console.log('[FeedIA] Carousel generated by Brain');

    // Step 2: Computer Vision analyzes best posting time from account data
    const postingTime = this.analyzeBestPostingTime(vision);
    console.log(`[FeedIA] Best posting time: ${postingTime}`);

    // Step 3: Browser automation posts carousel
    if (brief.platform === 'instagram' || brief.platform === 'both') {
      await this.browser.initializeBrowser();
      await this.browser.navigateToInstagram();
      await this.browser.createInstagramCarousel({
        images: carouselContent.images || [],
        captions: carouselContent.captions || [],
        hashtags: carouselContent.hashtags || '',
      });
      await this.browser.closeBrowser();

      console.log('[FeedIA] Carousel posted to Instagram');
    }

    if (brief.platform === 'tiktok' || brief.platform === 'both') {
      // Convert carousel to video for TikTok
      const videoContent = await this.convertCarouselToVideo(carouselContent);

      await this.browser.initializeBrowser();
      await this.browser.navigateToTikTok();
      await this.browser.createTikTokVideo(videoContent);
      await this.browser.closeBrowser();

      console.log('[FeedIA] Carousel converted to video and posted to TikTok');
    }

    return {
      success: true,
      action: 'post_carousel',
      platform: brief.platform,
      output: carouselContent,
    };
  }

  // ── WORKFLOW: POST REEL ──────────────────────────

  private async workflowPostReel(brief: AutomationBrief, vision: ScreenshotAnalysis): Promise<AutomationResult> {
    console.log('[FeedIA] Workflow: Post Reel');

    // Step 1: FeedIA generates viral reel
    const reelContent = await generateReelWithAgents({
      topic: brief.topic || 'trending',
      duration: 30,
      platform: 'instagram',
    }) as any;

    console.log('[FeedIA] Reel generated by Brain');

    // Step 2: Computer Vision checks trending audio
    const trendingAudio = await this.analyzeTrendingAudio(vision);
    console.log(`[FeedIA] Trending audio: ${trendingAudio}`);

    // Step 3: Browser automation posts reel
    if (brief.platform === 'instagram' || brief.platform === 'both') {
      await this.browser.initializeBrowser();
      await this.browser.navigateToInstagram();
      await this.browser.createInstagramCarousel({
        images: [reelContent.video],
        captions: [reelContent.caption],
        hashtags: reelContent.hashtags,
      });
      await this.browser.closeBrowser();
    }

    return {
      success: true,
      action: 'post_reel',
      platform: brief.platform,
      output: reelContent,
    };
  }

  // ── WORKFLOW: POST STORY ─────────────────────────

  private async workflowPostStory(brief: AutomationBrief, vision: ScreenshotAnalysis): Promise<AutomationResult> {
    console.log('[FeedIA] Workflow: Post Story');

    // Step 1: Generate story image
    const storyContent = await generatePhotoWithAgents({
      subject: brief.topic || 'behind-scenes',
      mood: brief.style || 'authentic',
      format: '9:16',
    }) as any;

    console.log('[FeedIA] Story image generated');

    // Step 2: Post to Instagram Stories
    if (brief.platform === 'instagram' || brief.platform === 'both') {
      await this.browser.initializeBrowser();
      await this.browser.navigateToInstagram();
      await this.browser.createInstagramStory(storyContent.image, storyContent.text);
      await this.browser.closeBrowser();

      console.log('[FeedIA] Story posted to Instagram');
    }

    return {
      success: true,
      action: 'post_story',
      platform: brief.platform,
      output: storyContent,
    };
  }

  // ── WORKFLOW: RESPOND TO COMMENTS ────────────────

  private async workflowRespondComments(
    brief: AutomationBrief,
    vision: ScreenshotAnalysis,
  ): Promise<AutomationResult> {
    console.log('[FeedIA] Workflow: Respond to Comments');

    // Step 1: Extract comments from vision analysis (stub: no comments in ScreenshotAnalysis)
    const comments: any[] = [];
    console.log(`[FeedIA] Found ${comments.length} comments to respond to`);

    // Step 2: FeedIA Copy Engine generates personalized responses
    const responses = [];
    for (const comment of comments) {
      const response = await this.generateCommentResponse(comment);
      responses.push({
        commentId: comment.id,
        response,
      });
    }

    console.log(`[FeedIA] Generated ${responses.length} response(s)`);

    // Step 3: Browser automation posts responses
    if (brief.platform === 'instagram' || brief.platform === 'both') {
      await this.browser.initializeBrowser();
      await this.browser.navigateToInstagram();
      await this.browser.respondToComments(responses);
      await this.browser.closeBrowser();
    }

    return {
      success: true,
      action: 'respond_comments',
      platform: brief.platform,
      output: { responsesGenerated: responses.length },
    };
  }

  // ── WORKFLOW: ANALYZE ACCOUNT ────────────────────

  private async workflowAnalyzeAccount(
    brief: AutomationBrief,
    vision: ScreenshotAnalysis,
  ): Promise<AutomationResult> {
    console.log('[FeedIA] Workflow: Analyze Account');

    // Step 1: Browser automation retrieves metrics
    await this.browser.initializeBrowser();
    await this.browser.navigateToInstagram();
    const metrics = await this.browser.analyzeAccountMetrics();
    await this.browser.closeBrowser();

    console.log(`[FeedIA] Account metrics: ${JSON.stringify(metrics)}`);

    // Step 2: FeedIA Content Strategy Agent analyzes data
    const recommendations = await this.generateAccountRecommendations(metrics, vision);

    console.log('[FeedIA] Generated recommendations for growth');

    return {
      success: true,
      action: 'analyze_account',
      platform: brief.platform,
      metrics,
      output: recommendations,
    };
  }

  // ── HELPER FUNCTIONS ─────────────────────────────

  private analyzeBestPostingTime(vision: ScreenshotAnalysis): string {
    // Analyze when audience is most active from vision data
    return '9:00 AM'; // Placeholder
  }

  private async analyzeTrendingAudio(vision: ScreenshotAnalysis): Promise<string> {
    // Extract trending sounds from TikTok/Instagram
    return 'current_trending_audio'; // Placeholder
  }

  private async convertCarouselToVideo(carousel: any): Promise<any> {
    // Convert carousel slides to video format
    return {
      videoPath: '/tmp/carousel_video.mp4',
      caption: carousel.captions?.[0] || '',
      hashtags: carousel.hashtags || '',
    };
  }

  private async generateCommentResponse(comment: any): Promise<string> {
    // Use FeedIA Copy Engine to generate personalized response
    const response = await (await import('../api/agentIntegrationLayer')).generateCarouselWithAgents({
      topic: `respond to: ${comment.text}`,
      emotion: 'engaging',
      targetSlideCount: 1, // Single response
    });

    return response.content?.split('\n')[0] || 'Thanks for the comment!';
  }

  private async generateAccountRecommendations(metrics: any, vision: ScreenshotAnalysis): Promise<string[]> {
    // Analyze metrics + vision, generate growth recommendations
    const recommendations: string[] = [];

    if (metrics.engagement < 5) {
      recommendations.push('Increase posting frequency - engagement is below average');
    }

    if (metrics.followers < 10000) {
      recommendations.push('Focus on viral content - use trending formats');
    }

    recommendations.push('Optimize posting time based on audience activity');

    return recommendations;
  }

  getActionLog(): AutomationResult[] {
    return this.actionLog;
  }
}

// ── PUBLIC API ──────────────────────────────────────

export async function automateInstagramCarousel(topic: string, style: string): Promise<AutomationResult> {
  const orchestrator = new FeedIAComputerUseOrchestrator();
  return await orchestrator.executeAutomation({
    task: 'post_carousel',
    platform: 'instagram',
    topic,
    style,
  });
}

export async function automateInstagramAndTikTok(topic: string): Promise<AutomationResult> {
  const orchestrator = new FeedIAComputerUseOrchestrator();
  return await orchestrator.executeAutomation({
    task: 'post_carousel',
    platform: 'both',
    topic,
  });
}

export async function automateInstagramEngagement(): Promise<AutomationResult> {
  const orchestrator = new FeedIAComputerUseOrchestrator();
  return await orchestrator.executeAutomation({
    task: 'respond_comments',
    platform: 'instagram',
  });
}

export async function analyzeAccountAndOptimize(): Promise<AutomationResult> {
  const orchestrator = new FeedIAComputerUseOrchestrator();
  return await orchestrator.executeAutomation({
    task: 'analyze_account',
    platform: 'instagram',
  });
}

export { FeedIAComputerUseOrchestrator };
