const NEXT_HOST="https://feedia-next.vercel.app",HASH_TO_PATH={home:"/welcome",imperio:"/imperio",mission:"/dashboard",agenda:"/agenda",calendar:"/calendar",feed:"/feed",predictor:"/predictor","brand-os":"/brand-os","cu-queue":"/cu-queue",brain:"/brain",approvals:"/approvals",equipo:"/growth-team",computeruse:"/cu-queue",simulator:"/simulator",tiktok:"/studio/tiktok-script"},targetPathFromHash=()=>{const t=(location.hash||"#home").replace(/^#/,"").split("?")[0];return HASH_TO_PATH[t]||"/welcome"},issuePassport=async t=>{try{const e=await fetch("/api/bridge/passport",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({targetRoute:t})});if(!e.ok)throw new Error(`passport ${e.status}`);return(await e.json()).redirect}catch{return`${NEXT_HOST}${t}`}},pingTwin=async()=>{try{return(await(await fetch("/api/bridge/twin-status",{cache:"no-store"})).json()).twinAlive===!0}catch{return!1}},mount=()=>{if(document.querySelector("#siamese-switcher"))return;const t=document.createElement("div");t.id="siamese-switcher",t.innerHTML=`
    <button class="ss-btn" id="ss-go" title="Abrir vista equivalente en FeedIA Next (sesi\xF3n compartida)">
      <span class="ss-dot" data-state="check"></span>
      <span class="ss-text">Next \u2197</span>
    </button>
    <style>
      #siamese-switcher{position:fixed;bottom:18px;left:18px;z-index:9998;font-family:inherit;}
      .ss-btn{display:inline-flex;align-items:center;gap:8px;padding:8px 12px;border-radius:999px;background:rgba(10,10,10,.85);backdrop-filter:blur(10px);box-shadow:inset 0 0 0 1px rgba(255,255,255,.12), 0 8px 24px rgba(0,0,0,.4);color:#fafafa;font-size:12px;font-weight:600;letter-spacing:-.005em;cursor:pointer;border:0;transition:box-shadow .15s, transform .12s;}
      .ss-btn:hover{box-shadow:inset 0 0 0 1px rgba(255,255,255,.22), 0 10px 28px rgba(0,0,0,.5);transform:translateY(-1px);}
      .ss-dot{width:7px;height:7px;border-radius:50%;background:#a1a1aa;box-shadow:0 0 8px rgba(161,161,170,.5);transition:background .2s,box-shadow .2s;}
      .ss-dot[data-state="ok"]{background:#10b981;box-shadow:0 0 10px rgba(16,185,129,.7);}
      .ss-dot[data-state="off"]{background:#ef4444;box-shadow:0 0 10px rgba(239,68,68,.6);}
      :root[data-theme="light"] .ss-btn{background:rgba(255,255,255,.92);color:#16171c;box-shadow:inset 0 0 0 1px rgba(17,18,22,.14), 0 8px 24px rgba(20,22,30,.15);}
      :root[data-theme="light"] .ss-btn:hover{box-shadow:inset 0 0 0 1px rgba(17,18,22,.28), 0 10px 28px rgba(20,22,30,.22);}
      @media (max-width: 720px){ #siamese-switcher{bottom:18px;left:12px;} }
    </style>
  `,document.body.appendChild(t);const e=t.querySelector(".ss-dot"),a=t.querySelector("#ss-go");a.addEventListener("click",async()=>{a.disabled=!0;const o=targetPathFromHash(),r=await issuePassport(o);window.open(r,"_blank","noopener"),a.disabled=!1});const s=async()=>{const o=await pingTwin();e.setAttribute("data-state",o?"ok":"off"),a.title=o?"Abrir vista equivalente en FeedIA Next":"FeedIA Next no responde \u2014 reintentando\u2026"};s(),setInterval(s,6e4)},consumePassport=async()=>{const t=new URL(location.href),e=t.searchParams.get("passport");if(e)try{const a=await fetch(`/api/twin/bridge/passport?id=${encodeURIComponent(e)}`,{cache:"no-store"});if(!a.ok)return;const s=await a.json();if(s.brandSnapshot)try{localStorage.setItem("feedia.brand",JSON.stringify(s.brandSnapshot))}catch{}if(s.identitySnapshot)try{localStorage.setItem("feedia.identity",JSON.stringify(s.identitySnapshot))}catch{}try{sessionStorage.setItem("feedia.siamese.synced",JSON.stringify({at:Date.now(),from:s.from}))}catch{}}catch{}finally{t.searchParams.delete("passport"),history.replaceState({},"",t.toString())}};document.readyState==="loading"?document.addEventListener("DOMContentLoaded",()=>{mount(),consumePassport()}):(mount(),consumePassport());
