/**
 * Calendar Editorial Auto-Generated — Pro+ feature.
 *
 * Genera calendario semanal de publicaciones balanceado por:
 *   - Formato (reel/carrusel/story) según plan strategist matrix
 *   - Goal mix (engagement/awareness/conversion)
 *   - Posting windows óptimos por platform
 *   - Cadencia plan-tier (Starter 5/sem, Pro 21/sem, Gold 35/sem, Premium 100/sem)
 *
 * Sin LLM call — heurístico determinístico. Free fallback = sin calendario.
 */

import { hasFeature, getFeature } from './_planFeatures.js';
import { getSessionFromReq } from './_users.js';
import * as store from './_store.js';

const CADENCE_PER_WEEK = {
  free: { posts: 2, stories: 7 },
  starter: { posts: 5, stories: 14 },
  pro: { posts: 21, stories: 35 },
  gold: { posts: 35, stories: 70 },
  premium: { posts: 100, stories: 140 },
};

const FORMAT_MIX = {
  // Por plan: distribución óptima del mix de formatos
  free: { reels: 0.4, carousel: 0.35, story: 0.25, photo: 0 },
  starter: { reels: 0.45, carousel: 0.3, story: 0.2, photo: 0.05 },
  pro: { reels: 0.5, carousel: 0.25, story: 0.2, photo: 0.05 },
  gold: { reels: 0.55, carousel: 0.2, story: 0.15, photo: 0.05, live: 0.05 },
  premium: { reels: 0.55, carousel: 0.18, story: 0.12, photo: 0.05, live: 0.05, video: 0.05 },
};

const GOAL_ROTATION = ['engagement', 'awareness', 'community', 'conversion', 'sales'];

const POSTING_WINDOWS = {
  instagram: {
    reels: ['18:00', '20:00', '12:00', '15:00'],
    carousel: ['11:00', '13:00', '19:00', '20:00'],
    story: ['08:00', '12:00', '18:00', '21:00'],
    photo: ['13:00', '19:00'],
  },
  tiktok: {
    reels: ['09:00', '14:00', '19:00', '21:00'],
    video: ['09:00', '14:00', '19:00'],
    photo: ['19:00'],
    live: ['20:00'],
  },
};

const dayNames = ['domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado'];

const pickFormat = (mix) => {
  const r = Math.random();
  let acc = 0;
  for (const [fmt, weight] of Object.entries(mix)) {
    acc += weight;
    if (r <= acc) return fmt;
  }
  return Object.keys(mix)[0];
};

const pickTime = (windows) => windows[Math.floor(Math.random() * windows.length)];

export const generateWeeklyCalendar = ({
  planId,
  platform = 'instagram',
  brandNiche = '',
  goal = 'engagement',
  startDateIso,
}) => {
  const plan = planId || 'free';
  if (!hasFeature(plan, 'contentGeneration.calendarAutoGenerated')) {
    return {
      enabled: false,
      reason: `Feature 'calendarAutoGenerated' requiere plan Pro o superior. Plan actual: ${plan}.`,
      upgradeUrl: '/pricing.html',
    };
  }
  const cadence = CADENCE_PER_WEEK[plan] || CADENCE_PER_WEEK.free;
  const mix = FORMAT_MIX[plan] || FORMAT_MIX.free;
  const start = startDateIso ? new Date(startDateIso) : new Date();

  const slots = [];
  const totalPosts = cadence.posts;
  const totalStories = cadence.stories;

  // Distribuir posts entre 7 días
  for (let i = 0; i < totalPosts; i++) {
    const dayOffset = Math.floor(i / (totalPosts / 7));
    const date = new Date(start.getTime() + dayOffset * 86_400_000);
    const fmt = pickFormat(mix);
    const platformWindows = POSTING_WINDOWS[platform] || POSTING_WINDOWS.instagram;
    const windows = platformWindows[fmt] || platformWindows.reels || ['18:00'];
    slots.push({
      type: 'post',
      day: dayNames[date.getDay()],
      date: date.toISOString().slice(0, 10),
      time: pickTime(windows),
      format: fmt,
      platform,
      goal: GOAL_ROTATION[i % GOAL_ROTATION.length],
      topicHint: `${brandNiche || 'tu marca'} — ángulo ${i + 1}`,
      requiresAssetGeneration: true,
    });
  }

  // Stories: 1-2 por día
  for (let day = 0; day < 7; day++) {
    const storiesPerDay = Math.ceil(totalStories / 7);
    const date = new Date(start.getTime() + day * 86_400_000);
    for (let s = 0; s < storiesPerDay; s++) {
      slots.push({
        type: 'story',
        day: dayNames[date.getDay()],
        date: date.toISOString().slice(0, 10),
        time: pickTime(POSTING_WINDOWS[platform]?.story || ['12:00']),
        format: 'story',
        platform,
        goal: 'community',
        topicHint: `behind-the-scenes / poll / tip rápido`,
      });
    }
  }

  return {
    enabled: true,
    planId: plan,
    weekStart: start.toISOString().slice(0, 10),
    totalSlots: slots.length,
    cadence,
    slots: slots.sort((a, b) => (a.date + a.time).localeCompare(b.date + b.time)),
    generatedAt: new Date().toISOString(),
  };
};

export const handleCalendar = async (req, res, path, m, body) => {
  if (path === '/api/calendar/generate' && m === 'POST') {
    const ctx = await getSessionFromReq(req);
    if (!ctx) {
      res.statusCode = 401;
      res.setHeader('content-type', 'application/json');
      res.end(JSON.stringify({ error: 'no session' }));
      return true;
    }
    const planId = ctx.user.plan || 'free';
    const b = body || {};
    const cal = generateWeeklyCalendar({
      planId,
      platform: b.platform || 'instagram',
      brandNiche: b.brandNiche || '',
      goal: b.goal || 'engagement',
      startDateIso: b.startDateIso || null,
    });
    if (cal.enabled) {
      await store.set(`feedia:user:${ctx.user.id}:calendar:latest`, cal);
    }
    res.statusCode = cal.enabled ? 200 : 402;
    res.setHeader('content-type', 'application/json');
    res.end(JSON.stringify(cal));
    return true;
  }
  if (path === '/api/calendar/latest' && m === 'GET') {
    const ctx = await getSessionFromReq(req);
    if (!ctx) {
      res.statusCode = 401;
      res.end(JSON.stringify({ error: 'no session' }));
      return true;
    }
    const cal = await store.get(`feedia:user:${ctx.user.id}:calendar:latest`);
    res.statusCode = 200;
    res.setHeader('content-type', 'application/json');
    res.end(JSON.stringify(cal || { enabled: false, slots: [] }));
    return true;
  }
  return false;
};
