/**
 * Computer Use Recipe Library — IG/TikTok/Canva/CapCut + video tools.
 *
 * Recipes determinísticos (sin LLM cost) que CU ejecuta.
 * Disponibilidad por plan tier:
 *   - Free: recipes básicos IG/TT (engage, watch, scroll)
 *   - Starter: + publish básico + Canva templates + CapCut import
 *   - Pro: + edición avanzada Canva/CapCut + DMs masivos + analytics scrape
 *   - Gold: + Runway/Pika web automation + HeyGen avatares + multi-app workflows
 *   - Premium: + todo + scheduling avanzado + multi-account orchestration
 *
 * Cost a vos: $0 (recipes son JSON, no consumen LLM tokens).
 */

export const CU_RECIPES = {
  // ════════════════ INSTAGRAM ════════════════
  'ig-engage-feed': {
    id: 'ig-engage-feed',
    tool: 'instagram',
    category: 'engagement',
    label: '📷 IG · Engagement feed (like + comment nicho)',
    estimatedMin: 3,
    minPlan: 'free',
    riskLevel: 'low',
    steps: [
      { n: 1, action: 'open', target: 'instagram.com', icon: '🌐' },
      { n: 2, action: 'scroll-feed', detail: '10 posts lentos anti-bot', icon: '📜' },
      { n: 3, action: 'like-relevant', detail: '5-7 posts del nicho', icon: '❤️' },
      { n: 4, action: 'comment-soft', detail: 'comment template no spam en 2-3', icon: '💬' },
      { n: 5, action: 'pause', detail: '30-90s entre acciones', icon: '⏱️' },
    ],
    rateLimit: '30 likes/h, 10 comments/h max',
  },
  'ig-stories-watch': {
    id: 'ig-stories-watch',
    tool: 'instagram',
    category: 'relationship',
    label: '📷 IG · Ver stories de followers (retention)',
    estimatedMin: 2,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'instagram.com home', icon: '🏠' },
      { n: 2, action: 'tap-stories-bar', detail: 'avatars top feed', icon: '👁️' },
      { n: 3, action: 'watch-sequential', detail: '8-12 stories completas', icon: '⏭️' },
    ],
    rateLimit: 'sin límite',
  },
  'ig-dm-respond-leads': {
    id: 'ig-dm-respond-leads',
    tool: 'instagram',
    category: 'sales',
    label: '📷 IG · Responder DMs leads (template + personalización)',
    estimatedMin: 4,
    minPlan: 'starter',
    riskLevel: 'medium',
    steps: [
      { n: 1, action: 'open-inbox', target: 'instagram.com inbox', icon: '✉️' },
      { n: 2, action: 'detect-unread-leads', detail: 'filter por palabras clave', icon: '🔍' },
      { n: 3, action: 'classify-intent', detail: 'lead vs spam vs soporte', icon: '🧠' },
      { n: 4, action: 'send-personalized', detail: 'template + variables', icon: '📤' },
      { n: 5, action: 'tag-lead', detail: 'star + label "lead-warm"', icon: '⭐' },
    ],
    rateLimit: '20 DMs/día sin warming',
  },
  'ig-publish-carousel': {
    id: 'ig-publish-carousel',
    tool: 'instagram',
    category: 'publish',
    label: '📷 IG · Publicar carrusel (7 slides)',
    estimatedMin: 5,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'instagram.com', icon: '🌐' },
      { n: 2, action: 'tap-new-post', detail: 'botón + arriba', icon: '➕' },
      { n: 3, action: 'select-from-pc', detail: '"Seleccionar del ordenador"', icon: '📁' },
      { n: 4, action: 'upload-multiple', detail: 'N assets, ctrl+click', icon: '🖼️' },
      { n: 5, action: 'verify-order', detail: 'thumbnails inferior', icon: '✅' },
      { n: 6, action: 'crop-4-5', detail: 'aspect ratio 4:5 todos', icon: '✂️' },
      { n: 7, action: 'next', detail: 'skip filtros', icon: '➡️' },
      { n: 8, action: 'type-caption', detail: 'caption + hashtags', icon: '📝' },
      { n: 9, action: 'share', detail: 'publish', icon: '📤' },
      { n: 10, action: 'verify-published', detail: 'profile grid', icon: '🎉' },
    ],
    rateLimit: 'sin límite normal',
  },
  'ig-publish-reel': {
    id: 'ig-publish-reel',
    tool: 'instagram',
    category: 'publish',
    label: '📷 IG · Publicar Reel (video vertical)',
    estimatedMin: 4,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'instagram.com', icon: '🌐' },
      { n: 2, action: 'tap-new-post', icon: '➕' },
      { n: 3, action: 'upload-video', detail: '.mp4 9:16', icon: '🎬' },
      { n: 4, action: 'toggle-reel', detail: 'IG detecta vertical', icon: '🎞️' },
      { n: 5, action: 'select-cover-frame', detail: 'frame 0.5s', icon: '🖼️' },
      { n: 6, action: 'add-trending-audio', detail: 'biblioteca sonidos', icon: '🎵' },
      { n: 7, action: 'next-caption', icon: '➡️' },
      { n: 8, action: 'type-caption', detail: 'caption + hashtags + remix on', icon: '📝' },
      { n: 9, action: 'toggle-share-feed', detail: 'compartir también en feed', icon: '🔄' },
      { n: 10, action: 'share', icon: '📤' },
    ],
    rateLimit: '5 reels/día max recomendado',
  },
  'ig-publish-story-series': {
    id: 'ig-publish-story-series',
    tool: 'instagram',
    category: 'publish',
    label: '📷 IG · Publicar serie de stories (5 frames + stickers)',
    estimatedMin: 5,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'instagram.com', icon: '🌐' },
      { n: 2, action: 'tap-your-story', detail: 'avatar + propio', icon: '👤' },
      { n: 3, action: 'loop-5-frames', detail: 'subir 5 frames secuencial', icon: '🔄' },
      { n: 4, action: 'add-stickers', detail: 'poll/quiz/question por frame', icon: '🎯' },
      { n: 5, action: 'add-music', detail: 'audio overlay', icon: '🎵' },
      { n: 6, action: 'publish-each', detail: 'tap "Tu story"', icon: '📤' },
      { n: 7, action: 'verify-in-bar', detail: 'top feed stories bar', icon: '✅' },
    ],
  },
  'ig-insights-scrape': {
    id: 'ig-insights-scrape',
    tool: 'instagram',
    category: 'analytics',
    label: '📷 IG · Capturar insights último post',
    estimatedMin: 2,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'navigate-profile', icon: '👤' },
      { n: 2, action: 'tap-first-post', icon: '👆' },
      { n: 3, action: 'tap-view-insights', detail: '"Ver estadísticas"', icon: '📊' },
      { n: 4, action: 'screenshot-overview', detail: 'alcance + impresiones', icon: '📸' },
      { n: 5, action: 'scroll-engagement', detail: 'likes/comments/saves/shares', icon: '⬇️' },
      { n: 6, action: 'screenshot-engagement', icon: '📸' },
      { n: 7, action: 'extract-numbers', detail: 'OCR + structured output', icon: '🔢' },
    ],
  },
  'ig-collab-invite': {
    id: 'ig-collab-invite',
    tool: 'instagram',
    category: 'growth',
    label: '📷 IG · Invitar collaborator (2× alcance)',
    estimatedMin: 3,
    minPlan: 'pro',
    riskLevel: 'low',
    steps: [
      { n: 1, action: 'open-post-draft', icon: '📝' },
      { n: 2, action: 'tap-tag-people', icon: '🏷️' },
      { n: 3, action: 'tap-invite-collaborator', icon: '🤝' },
      { n: 4, action: 'search-handle', detail: '@cuenta_collab', icon: '🔍' },
      { n: 5, action: 'send-invite', icon: '📤' },
    ],
  },

  // ════════════════ TIKTOK ════════════════
  'tt-fyp-warming': {
    id: 'tt-fyp-warming',
    tool: 'tiktok',
    category: 'algorithm',
    label: '🎵 TT · Scroll FYP + warming algoritmo',
    estimatedMin: 5,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'tiktok.com', icon: '🌐' },
      { n: 2, action: 'scroll-fyp', detail: '5 min completos', icon: '📜' },
      { n: 3, action: 'like-nicho', detail: '5-10 videos nicho', icon: '❤️' },
      { n: 4, action: 'follow-creators', detail: '2-3 del nicho', icon: '👤' },
      { n: 5, action: 'save-favorites', detail: '3 a colección', icon: '🔖' },
    ],
    rateLimit: 'recomendado diario',
  },
  'tt-trending-sound-research': {
    id: 'tt-trending-sound-research',
    tool: 'tiktok',
    category: 'research',
    label: '🎵 TT · Research sonidos trending (24-72h)',
    estimatedMin: 3,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-discover', icon: '🔍' },
      { n: 2, action: 'tap-trending-sounds', icon: '🎶' },
      { n: 3, action: 'filter-recent-24h', icon: '⏰' },
      { n: 4, action: 'save-top-5', icon: '🔖' },
      { n: 5, action: 'export-list', detail: 'JSON con URLs + creators', icon: '📋' },
    ],
  },
  'tt-publish-video': {
    id: 'tt-publish-video',
    tool: 'tiktok',
    category: 'publish',
    label: '🎵 TT · Publicar video (con sonido + hashtags + caption)',
    estimatedMin: 5,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'tiktok.com/upload', icon: '🌐' },
      { n: 2, action: 'upload-mp4', detail: '9:16 vertical', icon: '🎬' },
      { n: 3, action: 'add-sound', detail: 'trending sound from research', icon: '🎵' },
      { n: 4, action: 'select-cover-frame', icon: '🖼️' },
      { n: 5, action: 'type-caption', detail: 'hook + hashtags + mentions', icon: '📝' },
      { n: 6, action: 'select-niche-category', icon: '📂' },
      { n: 7, action: 'allow-stitch-duet', icon: '🔄' },
      { n: 8, action: 'post', icon: '📤' },
      { n: 9, action: 'verify-profile', icon: '✅' },
    ],
    rateLimit: 'recomendado 1-3 videos/día',
  },
  'tt-publish-photo-mode': {
    id: 'tt-publish-photo-mode',
    tool: 'tiktok',
    category: 'publish',
    label: '🎵 TT · Publicar Photo Mode (carousel TT)',
    estimatedMin: 4,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-create', icon: '➕' },
      { n: 2, action: 'switch-photo-mode', icon: '📸' },
      { n: 3, action: 'upload-3-to-12-images', icon: '🖼️' },
      { n: 4, action: 'add-sound-mandatory', detail: 'sound es obligatorio', icon: '🎵' },
      { n: 5, action: 'add-text-overlay-first', detail: 'hook brutal slide 1', icon: '🔥' },
      { n: 6, action: 'caption-and-publish', icon: '📤' },
    ],
  },
  'tt-go-live': {
    id: 'tt-go-live',
    tool: 'tiktok',
    category: 'engagement',
    label: '🎵 TT · Iniciar Live',
    estimatedMin: 3,
    minPlan: 'pro',
    riskLevel: 'low',
    steps: [
      { n: 1, action: 'tap-create-plus', icon: '➕' },
      { n: 2, action: 'select-live', detail: 'tab Live', icon: '🔴' },
      { n: 3, action: 'add-title', detail: 'hook directo', icon: '📝' },
      { n: 4, action: 'select-category', icon: '📂' },
      { n: 5, action: 'start-broadcast', icon: '🎥' },
    ],
    rateLimit: '1.000 followers mínimo IG, sin minimum TT desde 2024',
  },
  'tt-dm-leads': {
    id: 'tt-dm-leads',
    tool: 'tiktok',
    category: 'sales',
    label: '🎵 TT · DMs leads (template + lead scoring)',
    estimatedMin: 4,
    minPlan: 'pro',
    riskLevel: 'medium',
    steps: [
      { n: 1, action: 'open-inbox-tt', icon: '✉️' },
      { n: 2, action: 'filter-unread', icon: '🔍' },
      { n: 3, action: 'classify-intent', icon: '🧠' },
      { n: 4, action: 'send-personalized', icon: '📤' },
    ],
    rateLimit: '15 DMs/día sin warming TT',
  },
  'tt-comments-respond': {
    id: 'tt-comments-respond',
    tool: 'tiktok',
    category: 'community',
    label: '🎵 TT · Responder comentarios último video',
    estimatedMin: 3,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-last-video', icon: '🎬' },
      { n: 2, action: 'expand-comments', icon: '💬' },
      { n: 3, action: 'classify-each', detail: 'positive/question/troll', icon: '🏷️' },
      { n: 4, action: 'reply-positive', detail: 'heart + reply', icon: '❤️' },
      { n: 5, action: 'reply-questions', detail: 'value-add', icon: '💡' },
      { n: 6, action: 'pin-best', detail: 'engagement amplifier', icon: '📌' },
    ],
  },

  // ════════════════ TIKTOK NATIVE EDITOR ════════════════
  'tt-editor-text-overlay': {
    id: 'tt-editor-text-overlay',
    tool: 'tiktok',
    category: 'native-editor',
    label: '🎵 TT · Editor nativo · Text overlay con timing exacto',
    estimatedMin: 4,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-create', detail: 'tap + bottom center', icon: '➕' },
      { n: 2, action: 'upload-or-record', detail: 'video desde galería', icon: '🎬' },
      { n: 3, action: 'tap-text-tool', detail: 'side icon Aa', icon: '📝' },
      { n: 4, action: 'type-hook-frame-1', detail: 'palabras 1-3 segundo 0', icon: '🔥' },
      { n: 5, action: 'set-text-duration', detail: 'duración 0-2s', icon: '⏱️' },
      { n: 6, action: 'add-text-frame-2', detail: 'segundo 2-5 payoff', icon: '➕' },
      { n: 7, action: 'pick-font-style', detail: 'serif bold + outline blanco', icon: '🔤' },
      { n: 8, action: 'position-safe-area', detail: 'centro-medio anti-crop', icon: '🎯' },
    ],
  },
  'tt-editor-voiceover': {
    id: 'tt-editor-voiceover',
    tool: 'tiktok',
    category: 'native-editor',
    label: '🎵 TT · Editor nativo · Grabar voiceover',
    estimatedMin: 3,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'tap-voiceover-tool', detail: 'mic icon side panel', icon: '🎙️' },
      { n: 2, action: 'tap-record-button', detail: 'hold para grabar', icon: '🔴' },
      { n: 3, action: 'record-narration', detail: 'sincronizar con visual', icon: '🎤' },
      { n: 4, action: 'preview-playback', icon: '▶️' },
      { n: 5, action: 'apply-effects', detail: 'echo / chipmunk / robot opcional', icon: '✨' },
      { n: 6, action: 'mix-original-audio', detail: 'lower original to 20%', icon: '🎚️' },
    ],
  },
  'tt-editor-text-to-speech': {
    id: 'tt-editor-text-to-speech',
    tool: 'tiktok',
    category: 'native-editor',
    label: '🎵 TT · Editor nativo · Text-to-Speech (voz IA TT)',
    estimatedMin: 2,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'add-text-overlay', icon: '📝' },
      { n: 2, action: 'long-press-text', detail: 'menu emerge', icon: '👆' },
      { n: 3, action: 'tap-text-to-speech', icon: '🗣️' },
      { n: 4, action: 'pick-voice', detail: 'Jessie / narrador / story / etc', icon: '🎭' },
      { n: 5, action: 'verify-sync', icon: '🔄' },
    ],
  },
  'tt-editor-effects-library': {
    id: 'tt-editor-effects-library',
    tool: 'tiktok',
    category: 'native-editor',
    label: '🎵 TT · Editor nativo · Aplicar effects (filters/AR/green-screen)',
    estimatedMin: 4,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-editor', icon: '✏️' },
      { n: 2, action: 'tap-effects-button', detail: 'sidebar Effects', icon: '✨' },
      { n: 3, action: 'browse-trending-effects', detail: 'tab Trending', icon: '🔥' },
      { n: 4, action: 'apply-green-screen', detail: 'fondo cambia con imagen subida', icon: '🟢' },
      { n: 5, action: 'apply-beauty-filter', detail: 'sutil 20% intensity', icon: '✨' },
      { n: 6, action: 'apply-transition-effect', detail: 'entre clips: zoom/flip/glitch', icon: '🔄' },
    ],
  },
  'tt-editor-sound-library': {
    id: 'tt-editor-sound-library',
    tool: 'tiktok',
    category: 'native-editor',
    label: '🎵 TT · Editor nativo · Buscar + aplicar sonido trending',
    estimatedMin: 3,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'tap-add-sound', detail: 'top-center "Agregar sonido"', icon: '🎵' },
      { n: 2, action: 'browse-trending-tab', detail: 'top trending últimas 7 días', icon: '📈' },
      { n: 3, action: 'preview-sound', detail: 'tap para escuchar', icon: '🔊' },
      { n: 4, action: 'select-sound', icon: '✅' },
      { n: 5, action: 'trim-to-clip-section', detail: 'seleccionar segundo de inicio', icon: '✂️' },
      { n: 6, action: 'sync-with-visual', detail: 'beat-drop = transition', icon: '🥁' },
    ],
  },
  'tt-editor-speed-control': {
    id: 'tt-editor-speed-control',
    tool: 'tiktok',
    category: 'native-editor',
    label: '🎵 TT · Editor nativo · Speed control (slow-mo / fast-forward)',
    estimatedMin: 2,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'tap-clip-timeline', detail: 'select clip individual', icon: '👆' },
      { n: 2, action: 'tap-speed-icon', detail: 'bottom toolbar', icon: '⚡' },
      { n: 3, action: 'pick-multiplier', detail: '0.3x / 0.5x / 1x / 2x / 3x', icon: '📊' },
      { n: 4, action: 'preview-result', icon: '▶️' },
      { n: 5, action: 'apply-curve-speed-pro', detail: 'curva acelera-desacelera (pro creator)', icon: '📈' },
    ],
  },
  'tt-editor-transitions': {
    id: 'tt-editor-transitions',
    tool: 'tiktok',
    category: 'native-editor',
    label: '🎵 TT · Editor nativo · Transitions entre clips',
    estimatedMin: 3,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'tap-between-clips', detail: 'small icon entre 2 clips', icon: '🔗' },
      { n: 2, action: 'browse-transitions', icon: '🎬' },
      { n: 3, action: 'select-zoom-in', detail: 'beat-drop = zoom', icon: '🔍' },
      { n: 4, action: 'select-vertical-flip', detail: 'verse change', icon: '🔄' },
      { n: 5, action: 'adjust-duration', detail: '0.2s default', icon: '⏱️' },
    ],
  },
  'tt-editor-captions-auto': {
    id: 'tt-editor-captions-auto',
    tool: 'tiktok',
    category: 'native-editor',
    label: '🎵 TT · Editor nativo · Auto-captions (subtítulos hablados)',
    estimatedMin: 3,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'tap-captions-button', detail: 'sidebar Captions/CC', icon: '📝' },
      { n: 2, action: 'wait-auto-transcription', detail: '5-15s typical', icon: '⏳' },
      { n: 3, action: 'review-text-errors', icon: '👁️' },
      { n: 4, action: 'fix-words', detail: 'tap palabra para editar', icon: '✏️' },
      { n: 5, action: 'pick-caption-style', detail: 'classic / dynamic / typewriter', icon: '🎨' },
      { n: 6, action: 'set-position-bottom', detail: 'evitar safe-area UI', icon: '📍' },
    ],
  },
  'tt-editor-stitch-mode': {
    id: 'tt-editor-stitch-mode',
    tool: 'tiktok',
    category: 'collaboration',
    label: '🎵 TT · Stitch video de otra cuenta',
    estimatedMin: 4,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'find-source-video', detail: 'video original a stitchear', icon: '🔍' },
      { n: 2, action: 'tap-share-icon', detail: 'right side arrow', icon: '↗️' },
      { n: 3, action: 'tap-stitch', icon: '🔗' },
      { n: 4, action: 'select-clip-portion', detail: '5s del original máximo', icon: '✂️' },
      { n: 5, action: 'record-your-response', detail: 'cámara propia + reacción', icon: '🎬' },
      { n: 6, action: 'add-text-context', icon: '📝' },
      { n: 7, action: 'publish', icon: '📤' },
    ],
    rateLimit: 'creator del original debe tener stitch habilitado',
  },
  'tt-editor-duet-mode': {
    id: 'tt-editor-duet-mode',
    tool: 'tiktok',
    category: 'collaboration',
    label: '🎵 TT · Duet (split-screen con otro creador)',
    estimatedMin: 4,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'find-source-video', icon: '🔍' },
      { n: 2, action: 'tap-share-icon', icon: '↗️' },
      { n: 3, action: 'tap-duet', icon: '👯' },
      { n: 4, action: 'pick-layout', detail: 'left-right / top-bottom / green-screen', icon: '📐' },
      { n: 5, action: 'record-your-side', icon: '🎥' },
      { n: 6, action: 'sync-timing', icon: '🔄' },
      { n: 7, action: 'add-caption', icon: '📝' },
      { n: 8, action: 'publish-with-credit', detail: '@original autor en caption', icon: '📤' },
    ],
  },
  'tt-symphony-ai-script': {
    id: 'tt-symphony-ai-script',
    tool: 'tiktok',
    category: 'ai-tools',
    label: '🎵 TT · Symphony AI (script + avatar TT nativo)',
    estimatedMin: 5,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'TikTok Symphony Creative Studio', icon: '🤖' },
      { n: 2, action: 'tap-symphony-assistant', icon: '🎼' },
      { n: 3, action: 'type-product-topic', icon: '📝' },
      { n: 4, action: 'generate-script-variants', detail: 'AI sugiere 3 hooks', icon: '✨' },
      { n: 5, action: 'pick-script', icon: '✅' },
      { n: 6, action: 'select-AI-avatar', detail: 'biblioteca avatars TT', icon: '👤' },
      { n: 7, action: 'render-video', icon: '🎬' },
      { n: 8, action: 'edit-result-in-app', icon: '✏️' },
    ],
  },
  'tt-creative-center-trends': {
    id: 'tt-creative-center-trends',
    tool: 'tiktok',
    category: 'research',
    label: '🎵 TT · Creative Center · Research trends por país/categoría',
    estimatedMin: 4,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'ads.tiktok.com/business/creativecenter', icon: '🌐' },
      { n: 2, action: 'tab-trending-creators', icon: '🌟' },
      { n: 3, action: 'tab-trending-hashtags', detail: 'filter por industria + país', icon: '#️⃣' },
      { n: 4, action: 'tab-trending-songs', detail: 'last 7 days', icon: '🎶' },
      { n: 5, action: 'tab-keyword-insights', detail: 'volume + growth %', icon: '📊' },
      { n: 6, action: 'export-report-pdf', icon: '📥' },
    ],
  },
  'tt-publish-schedule': {
    id: 'tt-publish-schedule',
    tool: 'tiktok',
    category: 'publish',
    label: '🎵 TT · Schedule post (TikTok Studio)',
    estimatedMin: 3,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'finish-video-edit', icon: '✅' },
      { n: 2, action: 'tap-next-to-publish', icon: '➡️' },
      { n: 3, action: 'tap-more-options', icon: '⚙️' },
      { n: 4, action: 'enable-schedule-toggle', icon: '⏰' },
      { n: 5, action: 'pick-date-time', detail: 'best window según research', icon: '📅' },
      { n: 6, action: 'confirm-schedule', icon: '✅' },
      { n: 7, action: 'verify-in-studio', detail: 'TikTok Studio → Scheduled', icon: '👁️' },
    ],
    rateLimit: 'max 10 días adelante',
  },
  'tt-shop-product-link': {
    id: 'tt-shop-product-link',
    tool: 'tiktok',
    category: 'monetization',
    label: '🎵 TT · Vincular producto Shop a video',
    estimatedMin: 3,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-publish-screen', icon: '📤' },
      { n: 2, action: 'tap-add-link', icon: '🔗' },
      { n: 3, action: 'select-shop-product', detail: 'desde catálogo TikTok Shop', icon: '🛍️' },
      { n: 4, action: 'preview-cta-overlay', icon: '👁️' },
      { n: 5, action: 'publish', icon: '📤' },
    ],
    rateLimit: 'cuenta TikTok Shop seller required',
  },
  'tt-live-shopping': {
    id: 'tt-live-shopping',
    tool: 'tiktok',
    category: 'monetization',
    label: '🎵 TT · Iniciar Live Shopping con productos',
    estimatedMin: 5,
    minPlan: 'gold',
    riskLevel: 'low',
    steps: [
      { n: 1, action: 'tap-create-plus', icon: '➕' },
      { n: 2, action: 'select-live', icon: '🔴' },
      { n: 3, action: 'enable-shop-mode', detail: 'toggle Live Shopping', icon: '🛍️' },
      { n: 4, action: 'add-product-cards', detail: 'hasta 50 productos', icon: '📦' },
      { n: 5, action: 'start-broadcast', icon: '🎥' },
      { n: 6, action: 'feature-product-during-live', detail: 'pin one at a time', icon: '📌' },
    ],
  },
  'tt-analytics-studio': {
    id: 'tt-analytics-studio',
    tool: 'tiktok',
    category: 'analytics',
    label: '🎵 TT · TikTok Studio · Capturar analytics completos',
    estimatedMin: 3,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'tiktok.com/tiktokstudio/analytics', icon: '📊' },
      { n: 2, action: 'tap-overview-tab', detail: '7/28/60/365 días', icon: '📈' },
      { n: 3, action: 'screenshot-engagement', icon: '📸' },
      { n: 4, action: 'tab-content', detail: 'top videos + completion rate', icon: '🎬' },
      { n: 5, action: 'tab-followers', detail: 'demographics + activity hours', icon: '👥' },
      { n: 6, action: 'tab-live-replay-analytics', detail: 'si Live activado', icon: '🎙️' },
      { n: 7, action: 'export-csv', icon: '📥' },
    ],
  },
  'tt-photo-mode-batch': {
    id: 'tt-photo-mode-batch',
    tool: 'tiktok',
    category: 'publish',
    label: '🎵 TT · Photo Mode batch (12 carousels desde 1 idea)',
    estimatedMin: 8,
    minPlan: 'pro',
    riskLevel: 'medium',
    steps: [
      { n: 1, action: 'prep-12-images', detail: 'misma marca + tema variado', icon: '🖼️' },
      { n: 2, action: 'open-create-photo', icon: '📸' },
      { n: 3, action: 'upload-first-set', detail: '4-8 imágenes', icon: '📁' },
      { n: 4, action: 'add-sound-pattern', detail: 'mismo sonido + caption pattern', icon: '🎵' },
      { n: 5, action: 'add-text-overlay-hook', icon: '🔥' },
      { n: 6, action: 'schedule-each-spaced', detail: '1 cada 6-12hs', icon: '📅' },
      { n: 7, action: 'verify-12-scheduled', icon: '✅' },
    ],
    rateLimit: 'evitar burst → TT puede flag spam',
  },
  'tt-repost-strategy': {
    id: 'tt-repost-strategy',
    tool: 'tiktok',
    category: 'algorithm',
    label: '🎵 TT · Repost de top performer a tu audiencia (Reposts feature)',
    estimatedMin: 2,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'find-relevant-creator-video', icon: '🔍' },
      { n: 2, action: 'tap-share-icon', icon: '↗️' },
      { n: 3, action: 'tap-repost-button', icon: '🔁' },
      { n: 4, action: 'add-text-thoughts', detail: 'tu take + value-add', icon: '💭' },
      { n: 5, action: 'repost', icon: '📤' },
    ],
  },

  // ════════════════ CANVA ════════════════
  'canva-open-template': {
    id: 'canva-open-template',
    tool: 'canva',
    category: 'design',
    label: '🎨 Canva · Abrir template (carrusel/reel/story)',
    estimatedMin: 2,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'canva.com', icon: '🌐' },
      { n: 2, action: 'search-template', detail: 'query: instagram carousel modern', icon: '🔍' },
      { n: 3, action: 'select-template', icon: '👆' },
      { n: 4, action: 'open-editor', icon: '✏️' },
    ],
  },
  'canva-apply-brand-kit': {
    id: 'canva-apply-brand-kit',
    tool: 'canva',
    category: 'branding',
    label: '🎨 Canva · Aplicar Brand Kit (colores + fonts + logo)',
    estimatedMin: 3,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-design', icon: '🖼️' },
      { n: 2, action: 'tap-brand-kit', detail: 'sidebar Brand', icon: '🎨' },
      { n: 3, action: 'apply-colors', detail: 'palette user', icon: '🌈' },
      { n: 4, action: 'apply-fonts', detail: 'pairing pro', icon: '🔤' },
      { n: 5, action: 'insert-logo', detail: 'esquina inf-der', icon: '🏷️' },
    ],
  },
  'canva-edit-text-all-pages': {
    id: 'canva-edit-text-all-pages',
    tool: 'canva',
    category: 'edit',
    label: '🎨 Canva · Editar texto en todas las páginas (carrusel completo)',
    estimatedMin: 5,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'select-text-layer', detail: 'page 1 headline', icon: '🖱️' },
      { n: 2, action: 'replace-text', detail: 'nuevo headline', icon: '✏️' },
      { n: 3, action: 'next-page', icon: '➡️' },
      { n: 4, action: 'loop-all', detail: 'repetir para N páginas', icon: '🔄' },
    ],
  },
  'canva-magic-resize': {
    id: 'canva-magic-resize',
    tool: 'canva',
    category: 'multi-format',
    label: '🎨 Canva · Magic Resize (carrusel → reel + story)',
    estimatedMin: 2,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'tap-resize', icon: '↔️' },
      { n: 2, action: 'select-formats', detail: '9:16 + 1:1 + 4:5', icon: '📐' },
      { n: 3, action: 'tap-magic-resize', icon: '✨' },
      { n: 4, action: 'review-each-format', icon: '👁️' },
    ],
  },
  'canva-export-png-batch': {
    id: 'canva-export-png-batch',
    tool: 'canva',
    category: 'export',
    label: '🎨 Canva · Export PNG batch (todos slides)',
    estimatedMin: 2,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'tap-share', icon: '📤' },
      { n: 2, action: 'tap-download', icon: '⬇️' },
      { n: 3, action: 'select-png', detail: 'high quality', icon: '🖼️' },
      { n: 4, action: 'select-all-pages', icon: '☑️' },
      { n: 5, action: 'download-zip', icon: '📦' },
    ],
  },
  'canva-export-mp4': {
    id: 'canva-export-mp4',
    tool: 'canva',
    category: 'export',
    label: '🎨 Canva · Export Reel MP4',
    estimatedMin: 3,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'tap-share', icon: '📤' },
      { n: 2, action: 'download-mp4', detail: '1080p 30fps', icon: '🎬' },
      { n: 3, action: 'wait-render', detail: '30-60s typical', icon: '⏳' },
      { n: 4, action: 'auto-download', icon: '⬇️' },
    ],
  },

  // ════════════════ CAPCUT ════════════════
  'capcut-import-clip': {
    id: 'capcut-import-clip',
    tool: 'capcut',
    category: 'edit',
    label: '🎞️ CapCut · Importar clip + setup proyecto',
    estimatedMin: 2,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'capcut.com online editor', icon: '🌐' },
      { n: 2, action: 'new-project', icon: '➕' },
      { n: 3, action: 'set-9-16', detail: 'aspect ratio vertical', icon: '📐' },
      { n: 4, action: 'import-media', detail: 'upload .mp4', icon: '📁' },
    ],
  },
  'capcut-auto-captions': {
    id: 'capcut-auto-captions',
    tool: 'capcut',
    category: 'captions',
    label: '🎞️ CapCut · Auto-captions (subtítulos automáticos)',
    estimatedMin: 3,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'select-clip', icon: '👆' },
      { n: 2, action: 'tap-text-tab', detail: 'sidebar Texto', icon: '📝' },
      { n: 3, action: 'tap-auto-captions', icon: '⚡' },
      { n: 4, action: 'select-language', detail: 'español/inglés', icon: '🌍' },
      { n: 5, action: 'apply-style', detail: 'preset viral', icon: '🎨' },
      { n: 6, action: 'review-fix-errors', icon: '✅' },
    ],
  },
  'capcut-beat-sync': {
    id: 'capcut-beat-sync',
    tool: 'capcut',
    category: 'audio',
    label: '🎞️ CapCut · Beat-sync cortes con música',
    estimatedMin: 4,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'add-audio', detail: 'trending sound', icon: '🎵' },
      { n: 2, action: 'tap-beat-detect', detail: 'auto-detect BPM', icon: '🥁' },
      { n: 3, action: 'split-on-beats', detail: 'cuts cada beat fuerte', icon: '✂️' },
      { n: 4, action: 'apply-transitions', detail: 'zoom/cut por beat', icon: '⚡' },
    ],
  },
  'capcut-add-b-roll': {
    id: 'capcut-add-b-roll',
    tool: 'capcut',
    category: 'edit',
    label: '🎞️ CapCut · Insertar b-roll automático',
    estimatedMin: 4,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-stock-tab', icon: '🎬' },
      { n: 2, action: 'search-by-keyword', detail: 'topic-based', icon: '🔍' },
      { n: 3, action: 'drag-clips-timeline', detail: 'overlay layer', icon: '🖱️' },
      { n: 4, action: 'set-opacity-blend', icon: '🌫️' },
    ],
  },
  'capcut-color-grading': {
    id: 'capcut-color-grading',
    tool: 'capcut',
    category: 'vfx',
    label: '🎞️ CapCut · Color grading cinematic',
    estimatedMin: 4,
    minPlan: 'gold',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'select-all-clips', icon: '☑️' },
      { n: 2, action: 'tap-adjust', icon: '🎨' },
      { n: 3, action: 'apply-lut', detail: 'teal-orange preset', icon: '🎞️' },
      { n: 4, action: 'tune-curves', detail: 'lift shadows, crush blacks', icon: '📈' },
      { n: 5, action: 'finalize-look', icon: '✨' },
    ],
  },
  'capcut-export-1080': {
    id: 'capcut-export-1080',
    tool: 'capcut',
    category: 'export',
    label: '🎞️ CapCut · Export 1080p sin watermark',
    estimatedMin: 3,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'tap-export', icon: '📤' },
      { n: 2, action: 'set-1080p-30fps', icon: '⚙️' },
      { n: 3, action: 'toggle-watermark-off', detail: 'CapCut Pro feature', icon: '🚫' },
      { n: 4, action: 'start-render', icon: '⏳' },
      { n: 5, action: 'auto-download-mp4', icon: '⬇️' },
    ],
  },

  // ════════════════ RUNWAY ════════════════
  'runway-text-to-video': {
    id: 'runway-text-to-video',
    tool: 'runway',
    category: 'video-gen',
    label: '🎥 Runway · Text-to-Video Gen-3 Alpha',
    estimatedMin: 3,
    minPlan: 'gold',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'runwayml.com', icon: '🌐' },
      { n: 2, action: 'login', icon: '🔐' },
      { n: 3, action: 'select-gen3-alpha', icon: '🎯' },
      { n: 4, action: 'paste-prompt', icon: '📝' },
      { n: 5, action: 'set-duration', detail: '5-10s', icon: '⏱️' },
      { n: 6, action: 'generate', icon: '✨' },
      { n: 7, action: 'wait-render', detail: '~60-90s', icon: '⏳' },
      { n: 8, action: 'download-mp4', icon: '⬇️' },
    ],
  },
  'runway-image-to-video': {
    id: 'runway-image-to-video',
    tool: 'runway',
    category: 'video-gen',
    label: '🎥 Runway · Image-to-Video (anima estática)',
    estimatedMin: 3,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-tool', target: 'runwayml.com/image-to-video', icon: '🌐' },
      { n: 2, action: 'upload-image', icon: '🖼️' },
      { n: 3, action: 'describe-motion', icon: '📝' },
      { n: 4, action: 'generate', icon: '✨' },
    ],
  },

  // ════════════════ PIKA ════════════════
  'pika-create-video': {
    id: 'pika-create-video',
    tool: 'pika',
    category: 'video-gen',
    label: '🎥 Pika · Crear video stylized',
    estimatedMin: 3,
    minPlan: 'gold',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'pika.art', icon: '🌐' },
      { n: 2, action: 'select-style', detail: 'pikaffect preset', icon: '🎨' },
      { n: 3, action: 'paste-prompt', icon: '📝' },
      { n: 4, action: 'generate', icon: '✨' },
      { n: 5, action: 'download', icon: '⬇️' },
    ],
  },

  // ════════════════ LUMA ════════════════
  'luma-dream-machine': {
    id: 'luma-dream-machine',
    tool: 'luma',
    category: 'video-gen',
    label: '🎥 Luma · Dream Machine cinematic',
    estimatedMin: 4,
    minPlan: 'gold',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'lumalabs.ai/dream-machine', icon: '🌐' },
      { n: 2, action: 'paste-prompt-cinematic', icon: '📝' },
      { n: 3, action: 'set-loop-mode', detail: 'opcional para reels', icon: '🔄' },
      { n: 4, action: 'generate-9s', icon: '✨' },
      { n: 5, action: 'extend-video', detail: 'extends en chunks', icon: '➕' },
      { n: 6, action: 'export-1080', icon: '⬇️' },
    ],
  },

  // ════════════════ KLING ════════════════
  'kling-pro-video': {
    id: 'kling-pro-video',
    tool: 'kling',
    category: 'video-gen',
    label: '🎥 Kling · Pro video 1080p',
    estimatedMin: 4,
    minPlan: 'gold',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'klingai.com', icon: '🌐' },
      { n: 2, action: 'select-pro-mode', icon: '🏆' },
      { n: 3, action: 'paste-prompt', icon: '📝' },
      { n: 4, action: 'set-duration', detail: '5 o 10s', icon: '⏱️' },
      { n: 5, action: 'select-aspect', detail: '9:16/1:1/16:9', icon: '📐' },
      { n: 6, action: 'generate', icon: '✨' },
      { n: 7, action: 'download-1080', icon: '⬇️' },
    ],
  },

  // ════════════════ HEYGEN ════════════════
  'heygen-avatar-talking': {
    id: 'heygen-avatar-talking',
    tool: 'heygen',
    category: 'avatar',
    label: '🎥 HeyGen · Avatar talking head (script → video)',
    estimatedMin: 5,
    minPlan: 'premium',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'heygen.com', icon: '🌐' },
      { n: 2, action: 'select-avatar', detail: 'biblioteca o custom', icon: '👤' },
      { n: 3, action: 'paste-script', detail: 'texto a hablar', icon: '📝' },
      { n: 4, action: 'select-voice', detail: 'voz cloned o preset', icon: '🎙️' },
      { n: 5, action: 'select-background', icon: '🌆' },
      { n: 6, action: 'generate', icon: '✨' },
      { n: 7, action: 'download-mp4', icon: '⬇️' },
    ],
  },

  // ════════════════ INVIDEO ════════════════
  'invideo-quick-edit': {
    id: 'invideo-quick-edit',
    tool: 'invideo',
    category: 'edit',
    label: '🎞️ InVideo · Edit rápido con template + AI',
    estimatedMin: 4,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'invideo.io', icon: '🌐' },
      { n: 2, action: 'select-template', icon: '📋' },
      { n: 3, action: 'replace-text-ai', icon: '🤖' },
      { n: 4, action: 'export', icon: '⬇️' },
    ],
  },

  // ════════════════ IG ADVANCED ════════════════
  'ig-broadcast-channel': {
    id: 'ig-broadcast-channel',
    tool: 'instagram',
    category: 'community',
    label: '📷 IG · Crear + administrar Broadcast Channel',
    estimatedMin: 3,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-profile', icon: '👤' },
      { n: 2, action: 'tap-create-broadcast', detail: 'top right + Broadcast', icon: '📢' },
      { n: 3, action: 'name-channel', detail: 'inner circle / sub-tribe', icon: '✏️' },
      { n: 4, action: 'invite-rules', detail: 'public/private/followers only', icon: '🔐' },
      { n: 5, action: 'post-welcome-message', detail: 'set tone + frecuencia', icon: '💬' },
      { n: 6, action: 'pin-channel-link-bio', icon: '📌' },
    ],
  },
  'ig-collab-post': {
    id: 'ig-collab-post',
    tool: 'instagram',
    category: 'growth',
    label: '📷 IG · Collab post (Instagram Collaborator feature)',
    estimatedMin: 5,
    minPlan: 'starter',
    riskLevel: 'low',
    steps: [
      { n: 1, action: 'create-post-draft', icon: '📝' },
      { n: 2, action: 'tap-tag-people', icon: '🏷️' },
      { n: 3, action: 'tap-invite-collaborator', icon: '🤝' },
      { n: 4, action: 'search-handle', detail: '@cuenta-collab', icon: '🔍' },
      { n: 5, action: 'wait-acceptance', detail: '24-72h typical', icon: '⏳' },
      { n: 6, action: 'publish-once-accepted', detail: 'aparece en ambos feeds = doble reach', icon: '📤' },
    ],
    rateLimit: 'colab debe aceptar. Best practice: confirmar antes',
  },
  'ig-notes-text': {
    id: 'ig-notes-text',
    tool: 'instagram',
    category: 'engagement',
    label: '📷 IG · Notes (notas top inbox)',
    estimatedMin: 1,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-inbox', icon: '✉️' },
      { n: 2, action: 'tap-your-note', detail: 'avatar arriba inbox', icon: '➕' },
      { n: 3, action: 'type-60-chars', detail: 'pregunta/teaser/cliffhanger', icon: '✏️' },
      { n: 4, action: 'select-audience', detail: 'close-friends o all', icon: '🔐' },
      { n: 5, action: 'post-24h-visible', icon: '⏰' },
    ],
  },
  'ig-template-reel-trend': {
    id: 'ig-template-reel-trend',
    tool: 'instagram',
    category: 'publish',
    label: '📷 IG · Usar template trending de otro reel',
    estimatedMin: 3,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'find-trending-reel', detail: 'reel popular nicho', icon: '🔍' },
      { n: 2, action: 'tap-three-dots', icon: '⋯' },
      { n: 3, action: 'tap-use-template', icon: '📋' },
      { n: 4, action: 'replace-clips-yours', icon: '🎬' },
      { n: 5, action: 'edit-text-style', icon: '✏️' },
      { n: 6, action: 'publish', icon: '📤' },
    ],
  },
  'ig-add-music-story-photo': {
    id: 'ig-add-music-story-photo',
    tool: 'instagram',
    category: 'native-editor',
    label: '📷 IG · Story con música overlay (foto/video)',
    estimatedMin: 2,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-story-camera', icon: '📷' },
      { n: 2, action: 'upload-photo-or-video', icon: '🖼️' },
      { n: 3, action: 'tap-music-sticker', icon: '🎵' },
      { n: 4, action: 'search-trending-song', icon: '🔍' },
      { n: 5, action: 'select-clip-section', detail: 'best 5-15s del song', icon: '✂️' },
      { n: 6, action: 'choose-visual-style', detail: 'lyrics overlay style', icon: '🎨' },
      { n: 7, action: 'post-story', icon: '📤' },
    ],
  },
  'ig-pin-best-comments': {
    id: 'ig-pin-best-comments',
    tool: 'instagram',
    category: 'engagement',
    label: '📷 IG · Pin best comments primeros 60min',
    estimatedMin: 2,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-post-fresh', detail: '<60min publicado', icon: '🕐' },
      { n: 2, action: 'identify-best-comment', detail: 'high engagement-spark', icon: '👁️' },
      { n: 3, action: 'swipe-left-comment', icon: '👈' },
      { n: 4, action: 'tap-pin-icon', icon: '📌' },
      { n: 5, action: 'pin-top-3', detail: 'max 3 pinned', icon: '☑️' },
    ],
  },

  // ════════════════ TT ADVANCED ════════════════
  'tt-effect-house-custom': {
    id: 'tt-effect-house-custom',
    tool: 'tiktok',
    category: 'native-editor',
    label: '🎵 TT · Crear AR Effect personalizado (Effect House)',
    estimatedMin: 25,
    minPlan: 'gold',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'effecthouse.tiktok.com', icon: '🌐' },
      { n: 2, action: 'download-app', detail: 'Effect House desktop app', icon: '⬇️' },
      { n: 3, action: 'create-new-project', icon: '➕' },
      { n: 4, action: 'pick-template', detail: 'face-tracking / world-AR', icon: '📋' },
      { n: 5, action: 'add-assets-3d', detail: 'modelo + texturas', icon: '🎨' },
      { n: 6, action: 'configure-triggers', detail: 'gestos/audio/touch', icon: '⚡' },
      { n: 7, action: 'test-preview', icon: '👁️' },
      { n: 8, action: 'submit-review', detail: '3-7 días aprobación', icon: '📤' },
      { n: 9, action: 'distribute-to-creators', icon: '🌟' },
    ],
    rateLimit: 'aprobación TT requerida. 1 submission cada review cycle.',
  },
  'tt-series-paywall': {
    id: 'tt-series-paywall',
    tool: 'tiktok',
    category: 'monetization',
    label: '🎵 TT · TikTok Series (contenido pago)',
    estimatedMin: 10,
    minPlan: 'gold',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'check-eligibility', detail: 'requires creator next gen', icon: '✅' },
      { n: 2, action: 'open-tiktok-studio', icon: '🎬' },
      { n: 3, action: 'tap-series-tab', icon: '📋' },
      { n: 4, action: 'create-new-series', icon: '➕' },
      { n: 5, action: 'set-title-thumbnail-price', detail: 'price $0.99-$190', icon: '💰' },
      { n: 6, action: 'upload-episodes', detail: '1-80 episodes max', icon: '🎞️' },
      { n: 7, action: 'publish-promo-clip', detail: 'free teaser 60s', icon: '📤' },
    ],
  },
  'tt-grow-with-friends': {
    id: 'tt-grow-with-friends',
    tool: 'tiktok',
    category: 'growth',
    label: '🎵 TT · Grow With Friends + tag creators',
    estimatedMin: 5,
    minPlan: 'starter',
    riskLevel: 'low',
    steps: [
      { n: 1, action: 'finish-video', icon: '🎬' },
      { n: 2, action: 'add-mention-tag-creator', detail: '@cuenta-mayor-del-nicho relevante', icon: '🏷️' },
      { n: 3, action: 'add-strategic-hashtag', detail: 'hashtag campaign si participa', icon: '#️⃣' },
      { n: 4, action: 'publish-then-comment-on-original', detail: 'comment con video link', icon: '💬' },
      { n: 5, action: 'monitor-response', icon: '👁️' },
    ],
  },
  'tt-poll-quiz-sticker': {
    id: 'tt-poll-quiz-sticker',
    tool: 'tiktok',
    category: 'native-editor',
    label: '🎵 TT · Poll/Quiz stickers en video',
    estimatedMin: 2,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'enter-edit-mode', icon: '✏️' },
      { n: 2, action: 'tap-stickers', icon: '🎯' },
      { n: 3, action: 'pick-poll-or-quiz', icon: '📊' },
      { n: 4, action: 'type-question', detail: 'cierre con cliffhanger', icon: '❓' },
      { n: 5, action: 'set-options', icon: '☑️' },
      { n: 6, action: 'position-frame-safe', icon: '📍' },
    ],
  },
  'tt-green-screen-with-image': {
    id: 'tt-green-screen-with-image',
    tool: 'tiktok',
    category: 'native-editor',
    label: '🎵 TT · Green Screen con imagen/video como fondo',
    estimatedMin: 3,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-camera', icon: '📷' },
      { n: 2, action: 'tap-effects', icon: '✨' },
      { n: 3, action: 'select-green-screen', icon: '🟢' },
      { n: 4, action: 'upload-bg-image', detail: 'screenshot/meme/dato', icon: '🖼️' },
      { n: 5, action: 'frame-yourself-properly', detail: 'top-left mejor', icon: '🎯' },
      { n: 6, action: 'record-react-explain', icon: '🎬' },
      { n: 7, action: 'caption-publish', icon: '📤' },
    ],
  },

  // ════════════════ MULTI-PLATFORM ════════════════
  'cross-platform-repurpose': {
    id: 'cross-platform-repurpose',
    tool: 'multi-platform',
    category: 'compounding',
    label: '🔄 Multi · 1 idea → 5 plataformas (IG/TT/YT Shorts/LinkedIn/Threads)',
    estimatedMin: 30,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'create-master-content', detail: 'reel 30s en plataforma primaria', icon: '🎬' },
      { n: 2, action: 'adapt-aspect-ratio', detail: '9:16 → 1:1 → 16:9 según destino', icon: '📐' },
      { n: 3, action: 'adapt-caption-tone', detail: 'IG cercano / LinkedIn pro / Threads suelto', icon: '✏️' },
      { n: 4, action: 'adapt-hashtags', detail: 'nicho hashtags por platform', icon: '#️⃣' },
      { n: 5, action: 'stagger-publish-time', detail: '6-12h offset entre platforms', icon: '⏰' },
      { n: 6, action: 'measure-cross-platform-roi', icon: '📊' },
    ],
  },
  'cross-platform-saga-arc': {
    id: 'cross-platform-saga-arc',
    tool: 'multi-platform',
    category: 'narrative',
    label: '🔄 Multi · Saga arc multi-mes cross-platform',
    estimatedMin: 60,
    minPlan: 'gold',
    riskLevel: 'low',
    steps: [
      { n: 1, action: 'design-arc-7-parts', detail: 'historia mensual creciente', icon: '📚' },
      { n: 2, action: 'production-batch-parts', detail: 'grabar todos los frames + b-roll', icon: '🎬' },
      { n: 3, action: 'release-part-1-multi', detail: 'IG + TT + YT shorts mismo día', icon: '📤' },
      { n: 4, action: 'wait-engagement-spike-48h', icon: '📈' },
      { n: 5, action: 'release-part-2-different-platform-cliffhanger', icon: '🔁' },
      { n: 6, action: 'monitor-audience-migration', icon: '👥' },
      { n: 7, action: 'recap-final-part-summary-carousel', icon: '🎯' },
    ],
  },

  // ════════════════ ANALYTICS ════════════════
  'analytics-deep-dive-monthly': {
    id: 'analytics-deep-dive-monthly',
    tool: 'multi-platform',
    category: 'analytics',
    label: '📊 Multi · Analytics deep-dive mensual + decisiones',
    estimatedMin: 60,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'ig-insights-export', detail: 'IG Business Suite full', icon: '📷' },
      { n: 2, action: 'tt-studio-export', detail: 'TikTok Studio CSV', icon: '🎵' },
      { n: 3, action: 'identify-top-10-posts', icon: '⭐' },
      { n: 4, action: 'extract-winning-patterns', detail: 'hook/format/length/timing', icon: '🧠' },
      { n: 5, action: 'identify-bottom-10-posts', icon: '🚫' },
      { n: 6, action: 'kill-list-creation', detail: 'qué descartar próximo mes', icon: '✂️' },
      { n: 7, action: 'double-down-plan', detail: 'qué multiplicar', icon: '🚀' },
    ],
  },

  // ════════════════ IDEOGRAM ════════════════
  'ideogram-typography-design': {
    id: 'ideogram-typography-design',
    tool: 'ideogram',
    category: 'design',
    label: '🎨 Ideogram · Typography poster (texto legible en imagen)',
    estimatedMin: 3,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'ideogram.ai', icon: '🌐' },
      { n: 2, action: 'login', icon: '🔐' },
      { n: 3, action: 'paste-prompt-with-text', detail: 'prompt + "text: HEADLINE EXACTO"', icon: '📝' },
      { n: 4, action: 'select-style-typographic', detail: 'editorial / poster / typography focused', icon: '🔤' },
      { n: 5, action: 'set-aspect-4-5-ig', icon: '📐' },
      { n: 6, action: 'magic-prompt-enhance', detail: 'AI enriquece prompt', icon: '✨' },
      { n: 7, action: 'generate-4-variants', icon: '🎬' },
      { n: 8, action: 'pick-best-for-brand', icon: '✅' },
      { n: 9, action: 'remix-best-2x', detail: 'iterate on winner', icon: '🔁' },
      { n: 10, action: 'download-png', icon: '⬇️' },
    ],
  },
  'ideogram-logo-design': {
    id: 'ideogram-logo-design',
    tool: 'ideogram',
    category: 'branding',
    label: '🎨 Ideogram · Logo design con texto exacto',
    estimatedMin: 4,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', icon: '🌐' },
      {
        n: 2,
        action: 'prompt-logo-style',
        detail: 'prompt: "minimalist logo of [brand] with text [NAME EXACT], flat, modern"',
        icon: '📝',
      },
      { n: 3, action: 'select-style-vector-logo', icon: '🎯' },
      { n: 4, action: 'generate-set', icon: '✨' },
      { n: 5, action: 'pick-best-3-variants', icon: '✅' },
      { n: 6, action: 'download-each', detail: 'PNG + SVG si Pro', icon: '⬇️' },
    ],
  },
  'ideogram-magic-fill': {
    id: 'ideogram-magic-fill',
    tool: 'ideogram',
    category: 'edit',
    label: '🎨 Ideogram · Magic Fill (inpaint zona)',
    estimatedMin: 4,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'upload-image', icon: '🖼️' },
      { n: 2, action: 'tap-magic-fill', icon: '🪄' },
      { n: 3, action: 'paint-mask-area', detail: 'zona a reemplazar', icon: '🖌️' },
      { n: 4, action: 'prompt-replacement', detail: 'qué generar en mask', icon: '📝' },
      { n: 5, action: 'generate', icon: '✨' },
      { n: 6, action: 'iterate-or-accept', icon: '✅' },
    ],
  },
  'ideogram-remix-brand-kit': {
    id: 'ideogram-remix-brand-kit',
    tool: 'ideogram',
    category: 'branding',
    label: '🎨 Ideogram · Remix con brand kit consistency',
    estimatedMin: 5,
    minPlan: 'gold',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'upload-winning-design', detail: 'design previo que funcionó', icon: '⭐' },
      { n: 2, action: 'tap-remix', icon: '🔁' },
      { n: 3, action: 'change-only-text', detail: 'mantener style, swap text', icon: '✏️' },
      { n: 4, action: 'lock-style-strength', detail: 'high consistency', icon: '🔒' },
      { n: 5, action: 'generate-series', detail: '5 variantes con brand kit', icon: '🎨' },
      { n: 6, action: 'batch-download', icon: '⬇️' },
    ],
  },
  'ideogram-carousel-series': {
    id: 'ideogram-carousel-series',
    tool: 'ideogram',
    category: 'series',
    label: '🎨 Ideogram · Generar serie consistente para carrusel',
    estimatedMin: 8,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'design-first-slide', detail: 'slide 1 = hook con typography brutal', icon: '🔥' },
      { n: 2, action: 'save-style-seed', detail: 'seed = X para consistency', icon: '🌱' },
      { n: 3, action: 'remix-slides-2-to-7', detail: 'mismo seed + style + different text', icon: '🔁' },
      { n: 4, action: 'verify-visual-consistency', icon: '👁️' },
      { n: 5, action: 'download-all-7', icon: '📦' },
    ],
  },

  // ════════════════ FREEPIK ════════════════
  'freepik-stock-search-download': {
    id: 'freepik-stock-search-download',
    tool: 'freepik',
    category: 'stock',
    label: '🖼️ Freepik · Buscar stock + download (vectores/fotos/illustrations)',
    estimatedMin: 3,
    minPlan: 'free',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'freepik.com', icon: '🌐' },
      { n: 2, action: 'search-keyword', detail: 'topic-specific', icon: '🔍' },
      { n: 3, action: 'filter-vector-photo-illustration', icon: '🏷️' },
      { n: 4, action: 'filter-license-free', detail: 'free para no-Premium', icon: '🆓' },
      { n: 5, action: 'preview-top-10', icon: '👁️' },
      { n: 6, action: 'download-3-best', icon: '⬇️' },
      { n: 7, action: 'add-attribution-if-required', icon: '📝' },
    ],
  },
  'freepik-ai-image-gen': {
    id: 'freepik-ai-image-gen',
    tool: 'freepik',
    category: 'ai-gen',
    label: '🖼️ Freepik · AI Image Generator (Flux + Mystic)',
    estimatedMin: 4,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-ai-image-gen', target: 'freepik.com/ai/image-generator', icon: '🤖' },
      { n: 2, action: 'paste-prompt', icon: '📝' },
      { n: 3, action: 'select-flux-or-mystic', detail: 'Flux fast / Mystic high-quality', icon: '🎯' },
      { n: 4, action: 'select-style', detail: 'photo / illustration / 3D / cinematic', icon: '🎨' },
      { n: 5, action: 'generate-4-variants', icon: '✨' },
      { n: 6, action: 'upscale-best', detail: '2K/4K upscaler', icon: '⬆️' },
      { n: 7, action: 'download-png-jpg', icon: '⬇️' },
    ],
  },
  'freepik-magnific-upscale': {
    id: 'freepik-magnific-upscale',
    tool: 'freepik',
    category: 'upscale',
    label: '🖼️ Freepik · Magnific upscale (1080p → 8K)',
    estimatedMin: 3,
    minPlan: 'pro',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-upscaler', icon: '⬆️' },
      { n: 2, action: 'upload-image', icon: '🖼️' },
      { n: 3, action: 'select-scale-4x-or-8x', icon: '📊' },
      { n: 4, action: 'optional-add-detail', detail: 'add detail prompt', icon: '✨' },
      { n: 5, action: 'process-upscale', icon: '⏳' },
      { n: 6, action: 'download-hd', icon: '⬇️' },
    ],
  },
  'freepik-video-gen-kling-runway': {
    id: 'freepik-video-gen-kling-runway',
    tool: 'freepik',
    category: 'video-gen',
    label: '🖼️ Freepik · Video gen (Kling + Runway + Pika via Freepik)',
    estimatedMin: 5,
    minPlan: 'gold',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-ai-video', target: 'freepik.com/ai/video', icon: '🎥' },
      { n: 2, action: 'select-engine', detail: 'Kling 1.6 / Runway / Pika', icon: '🎯' },
      { n: 3, action: 'paste-prompt-or-image', icon: '📝' },
      { n: 4, action: 'set-duration-5s-or-10s', icon: '⏱️' },
      { n: 5, action: 'generate', icon: '✨' },
      { n: 6, action: 'download-mp4', icon: '⬇️' },
    ],
  },
  'freepik-icon-pack': {
    id: 'freepik-icon-pack',
    tool: 'freepik',
    category: 'icons',
    label: '🖼️ Freepik · Icon pack consistente (Flaticon integration)',
    estimatedMin: 4,
    minPlan: 'starter',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-flaticon-via-freepik', target: 'flaticon.com', icon: '🔗' },
      { n: 2, action: 'search-icon-family', detail: 'misma family/style', icon: '🔍' },
      { n: 3, action: 'select-10-icons-consistent', icon: '☑️' },
      { n: 4, action: 'pick-format-svg', icon: '📐' },
      { n: 5, action: 'pick-color-customize', icon: '🎨' },
      { n: 6, action: 'batch-download-zip', icon: '📦' },
    ],
  },

  // ════════════════ KLING (más recipes) ════════════════
  'kling-image-to-video': {
    id: 'kling-image-to-video',
    tool: 'kling',
    category: 'video-gen',
    label: '🎥 Kling · Image-to-Video con motion brush',
    estimatedMin: 5,
    minPlan: 'gold',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'klingai.com', icon: '🌐' },
      { n: 2, action: 'tap-image-to-video', icon: '🖼️' },
      { n: 3, action: 'upload-source-image', icon: '📁' },
      { n: 4, action: 'use-motion-brush', detail: 'pintar zonas que se animan', icon: '🖌️' },
      { n: 5, action: 'paste-motion-prompt', icon: '📝' },
      { n: 6, action: 'select-pro-or-standard', icon: '🎯' },
      { n: 7, action: 'generate-5s', icon: '✨' },
      { n: 8, action: 'extend-to-10s', detail: 'extend on result', icon: '➕' },
      { n: 9, action: 'download-1080p', icon: '⬇️' },
    ],
  },
  'kling-lip-sync': {
    id: 'kling-lip-sync',
    tool: 'kling',
    category: 'lip-sync',
    label: '🎥 Kling · Lip-sync (audio → mouth movement)',
    estimatedMin: 5,
    minPlan: 'premium',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-lip-sync-tool', icon: '👄' },
      { n: 2, action: 'upload-character-video', detail: 'persona/character video base', icon: '🎥' },
      { n: 3, action: 'upload-audio-or-tts', detail: 'voice clone o TTS', icon: '🎙️' },
      { n: 4, action: 'process', icon: '⏳' },
      { n: 5, action: 'download-synced', icon: '⬇️' },
    ],
  },
  'kling-virtual-tryon': {
    id: 'kling-virtual-tryon',
    tool: 'kling',
    category: 'product',
    label: '🎥 Kling · Virtual Try-On (e-commerce product on model)',
    estimatedMin: 4,
    minPlan: 'gold',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open-virtual-tryon', icon: '👗' },
      { n: 2, action: 'upload-model-image', detail: 'persona base', icon: '👤' },
      { n: 3, action: 'upload-product-image', detail: 'ropa/accesorio', icon: '👕' },
      { n: 4, action: 'generate-tryon-image', icon: '✨' },
      { n: 5, action: 'generate-video-from-image', detail: 'imagen → video con motion', icon: '🎬' },
      { n: 6, action: 'download', icon: '⬇️' },
    ],
  },

  // ════════════════ VEED ════════════════
  'veed-subtitle-translate': {
    id: 'veed-subtitle-translate',
    tool: 'veed',
    category: 'localization',
    label: '🎞️ Veed · Subtítulos + traducción multi-idioma',
    estimatedMin: 4,
    minPlan: 'gold',
    riskLevel: 'safe',
    steps: [
      { n: 1, action: 'open', target: 'veed.io', icon: '🌐' },
      { n: 2, action: 'upload-video', icon: '📁' },
      { n: 3, action: 'auto-subtitle', icon: '⚡' },
      { n: 4, action: 'translate-target', detail: 'EN/PT/FR', icon: '🌍' },
      { n: 5, action: 'export-burned', detail: 'subs hardcoded', icon: '⬇️' },
    ],
  },
};

/**
 * Tools meta info — tooling registry.
 */
export const CU_TOOLS = {
  instagram: { id: 'instagram', label: 'Instagram', icon: '📷', baseUrl: 'instagram.com', authRequired: true },
  tiktok: { id: 'tiktok', label: 'TikTok', icon: '🎵', baseUrl: 'tiktok.com', authRequired: true },
  canva: { id: 'canva', label: 'Canva', icon: '🎨', baseUrl: 'canva.com', authRequired: true, freeAccountOk: true },
  capcut: { id: 'capcut', label: 'CapCut', icon: '🎞️', baseUrl: 'capcut.com', authRequired: true, freeAccountOk: true },
  runway: {
    id: 'runway',
    label: 'Runway',
    icon: '🎥',
    baseUrl: 'runwayml.com',
    authRequired: true,
    freeTier: '125 credits/mes',
  },
  pika: { id: 'pika', label: 'Pika', icon: '🎥', baseUrl: 'pika.art', authRequired: true, freeTier: 'limited' },
  ideogram: {
    id: 'ideogram',
    label: 'Ideogram',
    icon: '🎨',
    baseUrl: 'ideogram.ai',
    authRequired: true,
    freeTier: '25 prompts/día',
  },
  freepik: {
    id: 'freepik',
    label: 'Freepik',
    icon: '🖼️',
    baseUrl: 'freepik.com',
    authRequired: true,
    freeTier: 'limited downloads',
  },
  luma: {
    id: 'luma',
    label: 'Luma Dream Machine',
    icon: '🎥',
    baseUrl: 'lumalabs.ai/dream-machine',
    authRequired: true,
    freeTier: '30 vids/mes',
  },
  kling: {
    id: 'kling',
    label: 'Kling AI',
    icon: '🎥',
    baseUrl: 'klingai.com',
    authRequired: true,
    freeTier: 'daily credits',
  },
  heygen: {
    id: 'heygen',
    label: 'HeyGen',
    icon: '🎥',
    baseUrl: 'heygen.com',
    authRequired: true,
    freeTier: '1 min/mes',
  },
  invideo: {
    id: 'invideo',
    label: 'InVideo',
    icon: '🎞️',
    baseUrl: 'invideo.io',
    authRequired: true,
    freeTier: 'unlimited free',
  },
  veed: { id: 'veed', label: 'Veed', icon: '🎞️', baseUrl: 'veed.io', authRequired: true, freeTier: '10 min/mes' },
};

const PLAN_ORDER = ['free', 'starter', 'pro', 'gold', 'premium'];

export const isPlanGteRequired = (userPlan, minPlan) => {
  return PLAN_ORDER.indexOf(userPlan) >= PLAN_ORDER.indexOf(minPlan);
};

export const listRecipesForPlan = (planId, opts = {}) => {
  const all = Object.values(CU_RECIPES);
  let filtered = all.filter((r) => isPlanGteRequired(planId, r.minPlan));
  if (opts.tool) filtered = filtered.filter((r) => r.tool === opts.tool);
  if (opts.category) filtered = filtered.filter((r) => r.category === opts.category);
  return filtered;
};

export const getRecipe = (id) => CU_RECIPES[id] || null;

export const handleCuRecipes = async (req, res, path, m) => {
  const json = (code, body) => {
    res.statusCode = code;
    res.setHeader('content-type', 'application/json');
    res.end(JSON.stringify(body));
  };
  const url = new URL(req.url || '/', 'http://x');

  if (path === '/api/cu/recipes' && m === 'GET') {
    const planId = url.searchParams.get('planId') || 'free';
    const tool = url.searchParams.get('tool');
    const category = url.searchParams.get('category');
    json(200, {
      planId,
      tools: CU_TOOLS,
      recipes: listRecipesForPlan(planId, { tool, category }),
      totalAvailable: listRecipesForPlan(planId).length,
      totalLibrary: Object.keys(CU_RECIPES).length,
    });
    return true;
  }

  if (path && path.startsWith('/api/cu/recipes/') && m === 'GET') {
    const id = path.split('/').pop();
    const recipe = getRecipe(id);
    if (!recipe) return json(404, { error: 'recipe not found' });
    json(200, recipe);
    return true;
  }

  return false;
};
